-- ============================================================
-- Entity: concat4bit_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: concat4bit_8bit

entity concat4bit_8bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(3 downto 0);
    rhs : in  STD_LOGIC_VECTOR(3 downto 0);
    out8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end concat4bit_8bit;

architecture Behavioral of concat4bit_8bit is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= lhs(3);
  n2_y <= lhs(2);
  n3_y <= lhs(1);
  n4_y <= lhs(0);
  n5_y <= rhs(3);
  n6_y <= rhs(2);
  n7_y <= rhs(1);
  n8_y <= rhs(0);

  -- output drivers
  out8bit(7) <= n1_y;
  out8bit(6) <= n2_y;
  out8bit(5) <= n3_y;
  out8bit(4) <= n4_y;
  out8bit(3) <= n5_y;
  out8bit(2) <= n6_y;
  out8bit(1) <= n7_y;
  out8bit(0) <= n8_y;

end Behavioral;