-- ============================================================
-- Entity: counter00_99_bcd
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter00_99_bcd

entity counter00_99_bcd is
  Port (
    clk_20hz : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0);
    bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0)
  );
end counter00_99_bcd;

architecture Behavioral of counter00_99_bcd is
  component counter0_9
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      current_bcd : out STD_LOGIC_VECTOR(3 downto 0);
      limit_reach : out STD_LOGIC
    );
  end component;
  signal n1_limit_reach, n2_limit_reach : STD_LOGIC;
  signal n1_current_bcd : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_current_bcd : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- sub-component instantiations
  u_0_c8578 : counter0_9 port map (
    last_output => STD_LOGIC'('0'),
    clk => STD_LOGIC'('0'),
    reset => STD_LOGIC'('0'),
    current_bcd => n1_current_bcd,
    limit_reach => n1_limit_reach
  );
  u_1_c8581 : counter0_9 port map (
    last_output => STD_LOGIC'('0'),
    clk => STD_LOGIC'('0'),
    reset => STD_LOGIC'('0'),
    current_bcd => n2_current_bcd,
    limit_reach => n2_limit_reach
  );

  -- output drivers
  bcd_d0 <= (others => '0');
  bcd_d1 <= (others => '0');

end Behavioral;

-- ============================================================
-- Entity: counter0_9
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter0_9

entity counter0_9 is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    current_bcd : out STD_LOGIC_VECTOR(3 downto 0);
    limit_reach : out STD_LOGIC
  );
end counter0_9;

architecture Behavioral of counter0_9 is
  signal n2_o, n5_o, n8_o, n11_o, n20_o, n23_o, n27_o, n31_o, n35_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n7_q : STD_LOGIC := '0';
  signal n7_qn : STD_LOGIC := '1';
  signal n10_q : STD_LOGIC := '0';
  signal n10_qn : STD_LOGIC := '1';
  signal n13_q : STD_LOGIC := '0';
  signal n13_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= last_output and n1_q;
  n5_o <= n2_o and n4_q;
  n8_o <= n5_o and n7_q;
  n11_o <= n10_q and n7_qn and n4_qn and n1_q;
  n20_o <= n10_q;
  n23_o <= n7_q;
  n27_o <= n4_q;
  n31_o <= n1_q;
  n35_o <= n11_o or reset;

  -- sequential logic (flip-flops)
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (last_output='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif rising_edge(clk) then
      if (n2_o='1') then n4_q <= not n4_q; n4_qn <= not n4_qn; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n7_q <= '0';
      n7_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n7_q <= not n7_q; n7_qn <= not n7_qn; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n10_q <= '0';
      n10_qn <= '1';
    elsif rising_edge(clk) then
      if (n8_o='1') then n10_q <= not n10_q; n10_qn <= not n10_qn; end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n13_q  <= n35_o;
      n13_qn <= not (n35_o);
    end if;
  end process;

  -- output drivers
  limit_reach <= n35_o;
  current_bcd(3) <= n20_o;
  current_bcd(2) <= n23_o;
  current_bcd(1) <= n27_o;
  current_bcd(0) <= n31_o;

end Behavioral;
