library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter00_99_bcd

entity counter00_99_bcd is
  Port (
    clk_20hz : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0);
    bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0)
  );
end counter00_99_bcd;

architecture Behavioral of counter00_99_bcd is
  component counter0_9
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      current_bcd : out STD_LOGIC_VECTOR(3 downto 0);
      limit_reach : out STD_LOGIC
    );
  end component;
  signal n1_limit_reach, n2_limit_reach : STD_LOGIC;
  signal n1_current_bcd : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_current_bcd : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- sub-component instantiations
  u_lsb : counter0_9 port map (
    last_output => STD_LOGIC'('1'),
    clk => clk_20hz,
    reset => reset,
    current_bcd => n1_current_bcd,
    limit_reach => n1_limit_reach
  );
  u_msb : counter0_9 port map (
    last_output => n1_limit_reach,
    clk => clk_20hz,
    reset => reset,
    current_bcd => n2_current_bcd,
    limit_reach => n2_limit_reach
  );

  -- output drivers
  bcd_d1 <= n2_current_bcd;
  bcd_d0 <= n1_current_bcd;

end Behavioral;
