-- ============================================================
-- Entity: debounce_toggle
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_toggle

entity debounce_toggle is
  Port (
    clk : in  STD_LOGIC;
    sw_in : in  STD_LOGIC;
    toggle_output : out STD_LOGIC
  );
end debounce_toggle;

architecture Behavioral of debounce_toggle is
  signal n5_o, n6_o, n13_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n14_q : STD_LOGIC := '0';
  signal n14_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n5_o <= n2_q xor n3_q;
  n6_o <= n2_q and n5_o;
  n13_o <= n4_q xor n6_o;

  -- sequential logic (flip-flops)
  process(clk, n14_qn)
  begin
    if n14_qn = '1' then
      n1_q  <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      n1_q  <= sw_in;
      n1_qn <= not (sw_in);
    end if;
  end process;
  process(clk, n14_qn)
  begin
    if n14_qn = '1' then
      n2_q  <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      n2_q  <= n1_q;
      n2_qn <= not (n1_q);
    end if;
  end process;
  process(clk, n14_qn)
  begin
    if n14_qn = '1' then
      n3_q  <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      n3_q  <= n2_q;
      n3_qn <= not (n2_q);
    end if;
  end process;
  process(clk, n14_qn)
  begin
    if n14_qn = '1' then
      n4_q  <= '0';
      n4_qn <= '1';
    elsif rising_edge(clk) then
      n4_q  <= n13_o;
      n4_qn <= not (n13_o);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('0')='1') then n14_q <= '0'; n14_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='0') then n14_q <= '1'; n14_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='1') then n14_q <= not n14_q; n14_qn <= n14_q;
      end if;
    end if;
  end process;

  -- output drivers
  toggle_output <= n4_q;

end Behavioral;
