-- ============================================================
-- Entity: debounce_button
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_button

entity debounce_button is
  Port (
    button_signal : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    debounce_signal : out STD_LOGIC
  );
end debounce_button;

architecture Behavioral of debounce_button is
  component n_8_bit_sync_counter_with_target
    Port (
      trigger : in  STD_LOGIC;
      target : in  STD_LOGIC_VECTOR(7 downto 0);
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      limit_reached : out STD_LOGIC;
      current : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n4_limit_reached, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o : STD_LOGIC;
  signal n4_current : STD_LOGIC_VECTOR(7 downto 0);
  signal sch_sch8629_target_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n6_o <= STD_LOGIC'('0');
  n7_o <= STD_LOGIC'('0');
  n8_o <= STD_LOGIC'('1');
  n9_o <= STD_LOGIC'('1');
  n10_o <= STD_LOGIC'('0');
  n11_o <= STD_LOGIC'('0');
  n12_o <= STD_LOGIC'('1');
  n13_o <= STD_LOGIC'('0');

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n1_q  <= button_signal;
      n1_qn <= not (button_signal);
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n2_q  <= n1_q;
      n2_qn <= not (n1_q);
    end if;
  end process;
  process(clk_50mhz, n2_qn)
  begin
    if n2_qn = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk_50mhz) then
      if    (n4_limit_reached='0' and STD_LOGIC'('0')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n4_limit_reached='1' and STD_LOGIC'('0')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n4_limit_reached='1' and STD_LOGIC'('0')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c8869 : n_8_bit_sync_counter_with_target port map (
    trigger => clk_1khz,
    target => sch_sch8629_target_bus,
    clk => clk_50mhz,
    reset => n2_qn,
    limit_reached => n4_limit_reached,
    current => n4_current
  );

  -- output drivers
  debounce_signal <= n3_q;
  sch_sch8629_target_bus(7) <= n6_o;
  sch_sch8629_target_bus(6) <= n7_o;
  sch_sch8629_target_bus(5) <= n8_o;
  sch_sch8629_target_bus(4) <= n9_o;
  sch_sch8629_target_bus(3) <= n10_o;
  sch_sch8629_target_bus(2) <= n11_o;
  sch_sch8629_target_bus(1) <= n12_o;
  sch_sch8629_target_bus(0) <= n13_o;

end Behavioral;