-- ============================================================
-- Entity: debounce_toggle
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_toggle

entity debounce_toggle is
  Port (
    sw_in : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    toggle_output : out STD_LOGIC
  );
end debounce_toggle;

architecture Behavioral of debounce_toggle is
  component debounce_button
    Port (
      button_signal : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      debounce_signal : out STD_LOGIC
    );
  end component;
  signal n1_debounce_signal, n6_o : STD_LOGIC;
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n6_o <= n1_debounce_signal and n3_qn;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if (n6_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n3_q  <= n1_debounce_signal;
      n3_qn <= not (n1_debounce_signal);
    end if;
  end process;

  -- sub-component instantiations
  u_0_c8970 : debounce_button port map (
    button_signal => sw_in,
    clk_50mhz => clk_50mhz,
    clk_1khz => clk_1khz,
    debounce_signal => n1_debounce_signal
  );

  -- output drivers
  toggle_output <= n2_q;

end Behavioral;