-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
  Port (
    in1_msb : in  STD_LOGIC;
    in2 : in  STD_LOGIC;
    in3 : in  STD_LOGIC;
    in4_lsb : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC
  );
end hex_7seg;

architecture Behavioral of hex_7seg is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in1_msb and in2 and n40_o and in4_lsb;
  n2_o <= in1_msb and n39_o and in3 and in4_lsb;
  n3_o <= n36_o and in2 and n37_o and n38_o;
  n4_o <= n33_o and n34_o and n35_o and in4_lsb;
  n5_o <= n4_o or n3_o or n2_o or n1_o;
  n6_o <= in2 and in3 and n44_o;
  n7_o <= in1_msb and in3 and in4_lsb;
  n8_o <= in1_msb and in2 and n43_o;
  n9_o <= n41_o and in2 and n42_o and in4_lsb;
  n10_o <= n9_o or n8_o or n7_o or n6_o;
  n11_o <= in1_msb and in2 and n48_o;
  n12_o <= in1_msb and in2 and in3;
  n13_o <= n45_o and n46_o and in3 and n47_o;
  n14_o <= n13_o or n12_o or n11_o;
  n15_o <= in2 and in3 and in4_lsb;
  n16_o <= in1_msb and n55_o and in3 and n56_o;
  n17_o <= n52_o and in2 and n53_o and n54_o;
  n18_o <= n49_o and n50_o and n51_o and in4_lsb;
  n19_o <= n18_o or n17_o or n16_o or n15_o;
  n20_o <= n60_o and n61_o and in4_lsb;
  n21_o <= n59_o and in4_lsb;
  n22_o <= n57_o and in2 and n58_o;
  n23_o <= n22_o or n21_o or n20_o;
  n24_o <= in1_msb and in2 and n67_o and in4_lsb;
  n25_o <= n66_o and in3 and in4_lsb;
  n26_o <= n64_o and n65_o and in4_lsb;
  n27_o <= n62_o and n63_o and in3;
  n28_o <= n27_o or n26_o or n25_o or n24_o;
  n29_o <= in1_msb and in2 and n72_o and n73_o;
  n30_o <= n71_o and in2 and in3 and in4_lsb;
  n31_o <= n68_o and n69_o and n70_o;
  n32_o <= n31_o or n30_o or n29_o;
  n33_o <= not in1_msb;
  n34_o <= not in2;
  n35_o <= not in3;
  n36_o <= not in1_msb;
  n37_o <= not in3;
  n38_o <= not in4_lsb;
  n39_o <= not in2;
  n40_o <= not in3;
  n41_o <= not in1_msb;
  n42_o <= not in3;
  n43_o <= not in4_lsb;
  n44_o <= not in4_lsb;
  n45_o <= not in1_msb;
  n46_o <= not in2;
  n47_o <= not in4_lsb;
  n48_o <= not in4_lsb;
  n49_o <= not in1_msb;
  n50_o <= not in2;
  n51_o <= not in3;
  n52_o <= not in1_msb;
  n53_o <= not in3;
  n54_o <= not in4_lsb;
  n55_o <= not in2;
  n56_o <= not in4_lsb;
  n57_o <= not in1_msb;
  n58_o <= not in3;
  n59_o <= not in1_msb;
  n60_o <= not in2;
  n61_o <= not in3;
  n62_o <= not in1_msb;
  n63_o <= not in2;
  n64_o <= not in1_msb;
  n65_o <= not in2;
  n66_o <= not in1_msb;
  n67_o <= not in3;
  n68_o <= not in1_msb;
  n69_o <= not in2;
  n70_o <= not in3;
  n71_o <= not in1_msb;
  n72_o <= not in3;
  n73_o <= not in4_lsb;

  -- output drivers
  a <= n5_o;
  b <= n10_o;
  c <= n14_o;
  d <= n19_o;
  e <= n23_o;
  f <= n28_o;
  g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n4_o, n5_o, n7_o, n9_o, n10_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n3_qn;
  n5_o <= trigger and n1_q;
  n7_o <= n2_q and n1_q;
  n9_o <= n3_q or n7_o;
  n10_o <= trigger and n9_o;
  n12_o <= trigger and n3_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (n4_o='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      if (n10_o='1') then n3_q <= not n3_q; n3_qn <= not n3_qn; end if;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod2_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod5_sync port map (
    trigger => n2_mod2_out,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c10682 : mod2_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod2_out => n2_mod2_out
  );

  -- output drivers
  mod10_out <= n1_mod5_out;

end Behavioral;

-- ============================================================
-- Entity: lab6
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab6

entity lab6 is
  Port (
    clk_50mhz : in  STD_LOGIC;
    sw_target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    btn_start_stop : in  STD_LOGIC;
    led_status : out STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab6;

architecture Behavioral of lab6 is
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component main_controller
    Port (
      target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      btn_start_stop : in  STD_LOGIC;
      clk50mhz : in  STD_LOGIC;
      current_d1 : out STD_LOGIC_VECTOR(3 downto 0);
      current_d0 : out STD_LOGIC_VECTOR(3 downto 0);
      led_status : out STD_LOGIC
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      mod50k_out : out STD_LOGIC
    );
  end component;
  component n_2_digit_bcd_7seg_decoder
    Port (
      current_d1 : in  STD_LOGIC_VECTOR(3 downto 0);
      current_d0 : in  STD_LOGIC_VECTOR(3 downto 0);
      clk_1khz : in  STD_LOGIC;
      clk50_mhz : in  STD_LOGIC;
      segment_d3 : out STD_LOGIC;
      segment_d2 : out STD_LOGIC;
      segment_d1 : out STD_LOGIC;
      segment_d0 : out STD_LOGIC;
      d0 : out STD_LOGIC;
      d1 : out STD_LOGIC
    );
  end component;
  signal n1_a, n1_b, n1_c, n1_d, n1_e, n1_f, n1_g, n2_led_status, n3_mod50k_out, n5_segment_d3, n5_segment_d2, n5_segment_d1, n5_segment_d0, n5_d0, n5_d1 : STD_LOGIC;
  signal n2_current_d1 : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_current_d0 : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- sub-component instantiations
  u_0_c7328 : hex_7seg port map (
    in1_msb => n5_segment_d3,
    in2 => n5_segment_d2,
    in3 => n5_segment_d1,
    in4_lsb => n5_segment_d0,
    a => n1_a,
    b => n1_b,
    c => n1_c,
    d => n1_d,
    e => n1_e,
    f => n1_f,
    g => n1_g
  );
  u_1_c8259 : main_controller port map (
    target_bcd => sw_target_bcd,
    btn_start_stop => btn_start_stop,
    clk50mhz => clk_50mhz,
    current_d1 => n2_current_d1,
    current_d0 => n2_current_d0,
    led_status => n2_led_status
  );
  u_2_c9312 : mod50k_sync port map (
    clk => clk_50mhz,
    mod50k_out => n3_mod50k_out
  );
  u_3_c9404 : n_2_digit_bcd_7seg_decoder port map (
    current_d1 => n2_current_d1,
    current_d0 => n2_current_d0,
    clk_1khz => n3_mod50k_out,
    clk50_mhz => clk_50mhz,
    segment_d3 => n5_segment_d3,
    segment_d2 => n5_segment_d2,
    segment_d1 => n5_segment_d1,
    segment_d0 => n5_segment_d0,
    d0 => n5_d0,
    d1 => n5_d1
  );

  -- output drivers
  led_status <= n2_led_status;
  a <= n1_a;
  b <= n1_b;
  c <= n1_c;
  d <= n1_d;
  e <= n1_e;
  f <= n1_f;
  g <= n1_g;
  d0 <= n5_d0;
  d1 <= n5_d1;
  d2 <= STD_LOGIC'('0');
  d3 <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: mod2_5m_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_5m_sync

entity mod2_5m_sync is
  Port (
    clk : in  STD_LOGIC;
    mod2_5m_out : out STD_LOGIC
  );
end mod2_5m_sync;

architecture Behavioral of mod2_5m_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod5_out, n6_mod10_out, n7_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c7433 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n1_mod5_out
  );
  u_1_c7437 : mod10_sync port map (
    trigger => n7_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n2_mod10_out
  );
  u_2_c7438 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n3_mod10_out
  );
  u_3_c7439 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n4_mod10_out
  );
  u_4_c7442 : mod5_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n5_mod5_out
  );
  u_5_c7443 : mod10_sync port map (
    trigger => n5_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n6_mod10_out
  );
  u_6_c7444 : mod10_sync port map (
    trigger => n6_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n7_mod10_out
  );

  -- output drivers
  mod2_5m_out <= n4_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: main_controller
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: main_controller

entity main_controller is
  Port (
    target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    btn_start_stop : in  STD_LOGIC;
    clk50mhz : in  STD_LOGIC;
    current_d1 : out STD_LOGIC_VECTOR(3 downto 0);
    current_d0 : out STD_LOGIC_VECTOR(3 downto 0);
    led_status : out STD_LOGIC
  );
end main_controller;

architecture Behavioral of main_controller is
  component debounce_toggle
    Port (
      sw_in : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      toggle_output : out STD_LOGIC
    );
  end component;
  component mod2_5m_sync
    Port (
      clk : in  STD_LOGIC;
      mod2_5m_out : out STD_LOGIC
    );
  end component;
  component start_stop_controller
    Port (
      target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      toggle_output : in  STD_LOGIC;
      current_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      start_flag : out STD_LOGIC;
      error_flag : out STD_LOGIC
    );
  end component;
  component main_counter
    Port (
      target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      clk_20hz : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      current_d1 : out STD_LOGIC_VECTOR(3 downto 0);
      current_d0 : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      mod50k_out : out STD_LOGIC
    );
  end component;
  component concat4bit
    Port (
      msb : in  STD_LOGIC_VECTOR(3 downto 0);
      lsb : in  STD_LOGIC_VECTOR(3 downto 0);
      out8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component n_8bit_1_clk_delay
    Port (
      n_8bit_in : in  STD_LOGIC_VECTOR(7 downto 0);
      clk : in  STD_LOGIC;
      n_8bit_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_toggle_output, n2_mod2_5m_out, n3_start_flag, n3_error_flag, n4_o, n7_mod50k_out : STD_LOGIC;
  signal n5_current_d1 : STD_LOGIC_VECTOR(3 downto 0);
  signal n5_current_d0 : STD_LOGIC_VECTOR(3 downto 0);
  signal n10_out8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n13_n_8bit_out : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n4_o <= n3_start_flag and n2_mod2_5m_out;

  -- sub-component instantiations
  u_0_c7683 : debounce_toggle port map (
    sw_in => btn_start_stop,
    clk_1khz => n7_mod50k_out,
    clk_50mhz => clk50mhz,
    toggle_output => n1_toggle_output
  );
  u_1_c7685 : mod2_5m_sync port map (
    clk => clk50mhz,
    mod2_5m_out => n2_mod2_5m_out
  );
  u_2_c7732 : start_stop_controller port map (
    target_bcd => target_bcd,
    toggle_output => n1_toggle_output,
    current_bcd => n13_n_8bit_out,
    start_flag => n3_start_flag,
    error_flag => n3_error_flag
  );
  u_3_c8251 : main_counter port map (
    target_bcd => target_bcd,
    clk_20hz => n4_o,
    clk_50mhz => clk50mhz,
    current_d1 => n5_current_d1,
    current_d0 => n5_current_d0
  );
  u_4_c9263 : mod50k_sync port map (
    clk => clk50mhz,
    mod50k_out => n7_mod50k_out
  );
  u_5_c9279 : concat4bit port map (
    msb => n5_current_d1,
    lsb => n5_current_d0,
    out8bit => n10_out8bit
  );
  u_6_c9531 : n_8bit_1_clk_delay port map (
    n_8bit_in => n10_out8bit,
    clk => clk50mhz,
    n_8bit_out => n13_n_8bit_out
  );

  -- output drivers
  current_d1 <= n5_current_d1;
  current_d0 <= n5_current_d0;
  led_status <= n3_error_flag;

end Behavioral;

-- ============================================================
-- Entity: debounce_toggle
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_toggle

entity debounce_toggle is
  Port (
    sw_in : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    toggle_output : out STD_LOGIC
  );
end debounce_toggle;

architecture Behavioral of debounce_toggle is
  component debounce_button
    Port (
      button_signal : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      debounce_signal : out STD_LOGIC
    );
  end component;
  signal n1_debounce_signal : STD_LOGIC;
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if (n1_debounce_signal='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c8970 : debounce_button port map (
    button_signal => sw_in,
    clk_50mhz => clk_50mhz,
    clk_1khz => clk_1khz,
    debounce_signal => n1_debounce_signal
  );

  -- output drivers
  toggle_output <= n2_q;

end Behavioral;

-- ============================================================
-- Entity: start_stop_controller
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: start_stop_controller

entity start_stop_controller is
  Port (
    target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    toggle_output : in  STD_LOGIC;
    current_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    start_flag : out STD_LOGIC;
    error_flag : out STD_LOGIC
  );
end start_stop_controller;

architecture Behavioral of start_stop_controller is
  signal n1_gt, n1_lt, n2_o, n3_o, n4_gt, n4_lt, n5_o, n7_gt, n7_lt, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y : STD_LOGIC;
begin

  -- combinational logic
  n1_gt <= '1' when unsigned(target_bcd) > unsigned(current_bcd) else '0';
  n1_lt <= '1' when unsigned(target_bcd) < unsigned(current_bcd) else '0';
  n2_o <= not n5_o;
  n3_o <= n2_o and toggle_output;
  n4_gt <= '1' when unsigned'(n12_y & n11_y & n10_y & n9_y) > unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n4_lt <= '1' when unsigned'(n12_y & n11_y & n10_y & n9_y) < unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n5_o <= n1_lt or n8_o;
  n7_gt <= '1' when unsigned'(n16_y & n15_y & n14_y & n13_y) > unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n7_lt <= '1' when unsigned'(n16_y & n15_y & n14_y & n13_y) < unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n8_o <= n4_gt or n7_gt;
  n9_y <= target_bcd(0);
  n10_y <= target_bcd(1);
  n11_y <= target_bcd(2);
  n12_y <= target_bcd(3);
  n13_y <= target_bcd(4);
  n14_y <= target_bcd(5);
  n15_y <= target_bcd(6);
  n16_y <= target_bcd(7);

  -- output drivers
  start_flag <= n3_o;
  error_flag <= n5_o;

end Behavioral;

-- ============================================================
-- Entity: main_counter
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: main_counter

entity main_counter is
  Port (
    target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    clk_20hz : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    current_d1 : out STD_LOGIC_VECTOR(3 downto 0);
    current_d0 : out STD_LOGIC_VECTOR(3 downto 0)
  );
end main_counter;

architecture Behavioral of main_counter is
  component counter00_99_bcd
    Port (
      clk_20hz : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0);
      bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component concat4bit
    Port (
      msb : in  STD_LOGIC_VECTOR(3 downto 0);
      lsb : in  STD_LOGIC_VECTOR(3 downto 0);
      out8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component n_8bit_1_clk_delay
    Port (
      n_8bit_in : in  STD_LOGIC_VECTOR(7 downto 0);
      clk : in  STD_LOGIC;
      n_8bit_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_eq, n8_o : STD_LOGIC;
  signal n2_bcd_d1 : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_bcd_d0 : STD_LOGIC_VECTOR(3 downto 0);
  signal n3_out8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n4_n_8bit_out : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_eq <= '1' when target_bcd = n4_n_8bit_out else '0';
  n8_o <= clk_20hz and n1_eq;

  -- sub-component instantiations
  u_0_c8599 : counter00_99_bcd port map (
    clk_20hz => clk_20hz,
    clk_50mhz => clk_50mhz,
    reset => n8_o,
    bcd_d1 => n2_bcd_d1,
    bcd_d0 => n2_bcd_d0
  );
  u_1_c9045 : concat4bit port map (
    msb => n2_bcd_d1,
    lsb => n2_bcd_d0,
    out8bit => n3_out8bit
  );
  u_2_c9565 : n_8bit_1_clk_delay port map (
    n_8bit_in => n3_out8bit,
    clk => clk_50mhz,
    n_8bit_out => n4_n_8bit_out
  );

  -- output drivers
  current_d1 <= n2_bcd_d1;
  current_d0 <= n2_bcd_d0;

end Behavioral;

-- ============================================================
-- Entity: counter00_99_bcd
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter00_99_bcd

entity counter00_99_bcd is
  Port (
    clk_20hz : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0);
    bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0)
  );
end counter00_99_bcd;

architecture Behavioral of counter00_99_bcd is
  component counter0_9
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      current_bcd : out STD_LOGIC_VECTOR(3 downto 0);
      limit_reach : out STD_LOGIC
    );
  end component;
  signal n1_limit_reach, n2_limit_reach : STD_LOGIC;
  signal n1_current_bcd : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_current_bcd : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- sub-component instantiations
  u_lsb : counter0_9 port map (
    trigger => clk_20hz,
    clk => clk_50mhz,
    reset => reset,
    current_bcd => n1_current_bcd,
    limit_reach => n1_limit_reach
  );
  u_msb : counter0_9 port map (
    trigger => n1_limit_reach,
    clk => clk_50mhz,
    reset => reset,
    current_bcd => n2_current_bcd,
    limit_reach => n2_limit_reach
  );

  -- output drivers
  bcd_d1 <= n2_current_bcd;
  bcd_d0 <= n1_current_bcd;

end Behavioral;

-- ============================================================
-- Entity: counter0_9
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter0_9

entity counter0_9 is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    current_bcd : out STD_LOGIC_VECTOR(3 downto 0);
    limit_reach : out STD_LOGIC
  );
end counter0_9;

architecture Behavioral of counter0_9 is
  signal n1_o, n3_o, n5_o, n7_o, n13_o, n14_o, n19_o, n23_o, n24_o, n42_o, n46_o : STD_LOGIC;
  signal n9_q : STD_LOGIC := '0';
  signal n9_qn : STD_LOGIC := '1';
  signal n10_q : STD_LOGIC := '0';
  signal n10_qn : STD_LOGIC := '1';
  signal n11_q : STD_LOGIC := '0';
  signal n11_qn : STD_LOGIC := '1';
  signal n12_q : STD_LOGIC := '0';
  signal n12_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n1_o <= n12_q;
  n3_o <= n10_q;
  n5_o <= n11_q;
  n7_o <= n9_q;
  n13_o <= trigger and n9_q and n12_qn;
  n14_o <= trigger and n9_q;
  n19_o <= trigger and n9_q and n10_q;
  n23_o <= trigger and n9_q;
  n24_o <= trigger and n9_q and n10_q and n11_q;
  n42_o <= n12_q and n11_qn and n10_qn and n9_q;
  n46_o <= n42_o and trigger;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n9_q <= '0';
      n9_qn <= '1';
    elsif rising_edge(clk) then
      if    (trigger='0' and trigger='1') then n9_q <= '0'; n9_qn <= '1';
      elsif (trigger='1' and trigger='0') then n9_q <= '1'; n9_qn <= '0';
      elsif (trigger='1' and trigger='1') then n9_q <= not n9_q; n9_qn <= n9_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n10_q <= '0';
      n10_qn <= '1';
    elsif rising_edge(clk) then
      if    (n13_o='0' and n14_o='1') then n10_q <= '0'; n10_qn <= '1';
      elsif (n13_o='1' and n14_o='0') then n10_q <= '1'; n10_qn <= '0';
      elsif (n13_o='1' and n14_o='1') then n10_q <= not n10_q; n10_qn <= n10_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n11_q <= '0';
      n11_qn <= '1';
    elsif rising_edge(clk) then
      if    (n19_o='0' and n19_o='1') then n11_q <= '0'; n11_qn <= '1';
      elsif (n19_o='1' and n19_o='0') then n11_q <= '1'; n11_qn <= '0';
      elsif (n19_o='1' and n19_o='1') then n11_q <= not n11_q; n11_qn <= n11_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n12_q <= '0';
      n12_qn <= '1';
    elsif rising_edge(clk) then
      if    (n24_o='0' and n23_o='1') then n12_q <= '0'; n12_qn <= '1';
      elsif (n24_o='1' and n23_o='0') then n12_q <= '1'; n12_qn <= '0';
      elsif (n24_o='1' and n23_o='1') then n12_q <= not n12_q; n12_qn <= n12_q;
      end if;
    end if;
  end process;

  -- output drivers
  limit_reach <= n46_o;
  current_bcd(3) <= n1_o;
  current_bcd(1) <= n3_o;
  current_bcd(2) <= n5_o;
  current_bcd(0) <= n7_o;

end Behavioral;

-- ============================================================
-- Entity: debounce_button
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_button

entity debounce_button is
  Port (
    button_signal : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    debounce_signal : out STD_LOGIC
  );
end debounce_button;

architecture Behavioral of debounce_button is
  component mod50_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod50_out : out STD_LOGIC
    );
  end component;
  signal n7_o, n9_mod50_out : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n7_o <= n3_q and n6_qn;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n1_q  <= button_signal;
      n1_qn <= not (button_signal);
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n2_q  <= n1_q;
      n2_qn <= not (n1_q);
    end if;
  end process;
  process(clk_50mhz, n2_qn)
  begin
    if n2_qn = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk_50mhz) then
      if    (n9_mod50_out='0' and STD_LOGIC'('0')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n9_mod50_out='1' and STD_LOGIC'('0')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n9_mod50_out='1' and STD_LOGIC'('0')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n6_q  <= n3_q;
      n6_qn <= not (n3_q);
    end if;
  end process;

  -- sub-component instantiations
  u_0_c16763 : mod50_sync port map (
    trigger => clk_1khz,
    clk => clk_50mhz,
    reset => n2_qn,
    mod50_out => n9_mod50_out
  );

  -- output drivers
  debounce_signal <= n7_o;

end Behavioral;

-- ============================================================
-- Entity: concat4bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: concat4bit

entity concat4bit is
  Port (
    msb : in  STD_LOGIC_VECTOR(3 downto 0);
    lsb : in  STD_LOGIC_VECTOR(3 downto 0);
    out8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end concat4bit;

architecture Behavioral of concat4bit is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= msb(3);
  n2_y <= msb(2);
  n3_y <= msb(1);
  n4_y <= msb(0);
  n5_y <= lsb(3);
  n6_y <= lsb(2);
  n7_y <= lsb(1);
  n8_y <= lsb(0);

  -- output drivers
  out8bit(7) <= n1_y;
  out8bit(6) <= n2_y;
  out8bit(5) <= n3_y;
  out8bit(4) <= n4_y;
  out8bit(3) <= n5_y;
  out8bit(2) <= n6_y;
  out8bit(1) <= n7_y;
  out8bit(0) <= n8_y;

end Behavioral;

-- ============================================================
-- Entity: mod50k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50k_sync

entity mod50k_sync is
  Port (
    clk : in  STD_LOGIC;
    mod50k_out : out STD_LOGIC
  );
end mod50k_sync;

architecture Behavioral of mod50k_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c9232 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n1_mod5_out
  );
  u_1_c9233 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n2_mod10_out
  );
  u_2_c9234 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n3_mod10_out
  );
  u_3_c9235 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n4_mod10_out
  );
  u_4_c9236 : mod10_sync port map (
    trigger => n4_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n5_mod10_out
  );

  -- output drivers
  mod50k_out <= n5_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: n_2_digit_bcd_7seg_decoder
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: n_2_digit_bcd_7seg_decoder

entity n_2_digit_bcd_7seg_decoder is
  Port (
    current_d1 : in  STD_LOGIC_VECTOR(3 downto 0);
    current_d0 : in  STD_LOGIC_VECTOR(3 downto 0);
    clk_1khz : in  STD_LOGIC;
    clk50_mhz : in  STD_LOGIC;
    segment_d3 : out STD_LOGIC;
    segment_d2 : out STD_LOGIC;
    segment_d1 : out STD_LOGIC;
    segment_d0 : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC
  );
end n_2_digit_bcd_7seg_decoder;

architecture Behavioral of n_2_digit_bcd_7seg_decoder is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y : STD_LOGIC;
  signal n22_q : STD_LOGIC := '0';
  signal n22_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n1_y <= n5_y when n22_q = '0' else
             n6_y when n22_q = '1' else '0';
  n2_y <= n7_y when n22_q = '0' else
             n8_y when n22_q = '1' else '0';
  n3_y <= n9_y when n22_q = '0' else
             n10_y when n22_q = '1' else '0';
  n4_y <= n11_y when n22_q = '0' else
             n12_y when n22_q = '1' else '0';
  n5_y <= current_d1(3);
  n6_y <= current_d0(3);
  n7_y <= current_d1(2);
  n8_y <= current_d0(2);
  n9_y <= current_d1(1);
  n10_y <= current_d0(1);
  n11_y <= current_d1(0);
  n12_y <= current_d0(0);

  -- sequential logic (flip-flops)
  process(clk50_mhz)
  begin
    if rising_edge(clk50_mhz) then
      if (clk_1khz='1') then n22_q <= not n22_q; n22_qn <= not n22_qn; end if;
    end if;
  end process;

  -- output drivers
  segment_d3 <= n1_y;
  segment_d2 <= n2_y;
  segment_d1 <= n3_y;
  segment_d0 <= n4_y;
  d0 <= n22_qn;
  d1 <= n22_q;

end Behavioral;

-- ============================================================
-- Entity: n_8bit_1_clk_delay
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: n_8bit_1_clk_delay

entity n_8bit_1_clk_delay is
  Port (
    n_8bit_in : in  STD_LOGIC_VECTOR(7 downto 0);
    clk : in  STD_LOGIC;
    n_8bit_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end n_8bit_1_clk_delay;

architecture Behavioral of n_8bit_1_clk_delay is
  signal n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n5_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
  signal n7_q : STD_LOGIC := '0';
  signal n7_qn : STD_LOGIC := '1';
  signal n8_q : STD_LOGIC := '0';
  signal n8_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n9_y <= n_8bit_in(7);
  n10_y <= n_8bit_in(6);
  n11_y <= n_8bit_in(5);
  n12_y <= n_8bit_in(4);
  n13_y <= n_8bit_in(3);
  n14_y <= n_8bit_in(2);
  n15_y <= n_8bit_in(1);
  n16_y <= n_8bit_in(0);

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      n1_q  <= n9_y;
      n1_qn <= not (n9_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n2_q  <= n10_y;
      n2_qn <= not (n10_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n3_q  <= n11_y;
      n3_qn <= not (n11_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n4_q  <= n12_y;
      n4_qn <= not (n12_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n5_q  <= n13_y;
      n5_qn <= not (n13_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n6_q  <= n14_y;
      n6_qn <= not (n14_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n7_q  <= n15_y;
      n7_qn <= not (n15_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n8_q  <= n16_y;
      n8_qn <= not (n16_y);
    end if;
  end process;

  -- output drivers
  n_8bit_out(7) <= n1_q;
  n_8bit_out(6) <= n2_q;
  n_8bit_out(5) <= n3_q;
  n_8bit_out(4) <= n4_q;
  n_8bit_out(3) <= n5_q;
  n_8bit_out(2) <= n6_q;
  n_8bit_out(1) <= n7_q;
  n_8bit_out(0) <= n8_q;

end Behavioral;

-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= trigger and n1_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: mod50_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50_sync

entity mod50_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod50_out : out STD_LOGIC
  );
end mod50_sync;

architecture Behavioral of mod50_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c16652 : mod5_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c16653 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => reset,
    mod10_out => n2_mod10_out
  );

  -- output drivers
  mod50_out <= n2_mod10_out;

end Behavioral;
