library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab6

entity lab6 is
  Port (
    clk50mhz : in  STD_LOGIC;
    sw_target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    btn_start_stop : in  STD_LOGIC;
    led_status : out STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab6;

architecture Behavioral of lab6 is
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component main_controller
    Port (
      clk50mhz : in  STD_LOGIC;
      target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      btn_start_stop : in  STD_LOGIC;
      current_bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0);
      current_bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0);
      led_status : out STD_LOGIC
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      clk_mod50k : out STD_LOGIC
    );
  end component;
  component n_2_digit_bcd_7seg_decoder
    Port (
      current_bcd_d1 : in  STD_LOGIC_VECTOR(3 downto 0);
      current_bcd_d0 : in  STD_LOGIC_VECTOR(3 downto 0);
      clk_1khz : in  STD_LOGIC;
      segment_d3 : out STD_LOGIC;
      segment_d2 : out STD_LOGIC;
      segment_d1 : out STD_LOGIC;
      segment_d0 : out STD_LOGIC;
      d0 : out STD_LOGIC;
      d1 : out STD_LOGIC
    );
  end component;
  signal n1_a, n1_b, n1_c, n1_d, n1_e, n1_f, n1_g, n2_led_status, n3_clk_mod50k, n5_segment_d3, n5_segment_d2, n5_segment_d1, n5_segment_d0, n5_d0, n5_d1 : STD_LOGIC;
  signal n2_current_bcd_d1 : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_current_bcd_d0 : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- sub-component instantiations
  u_0_c7328 : hex_7seg port map (
    in1_msb => n5_segment_d3,
    in2 => n5_segment_d2,
    in3 => n5_segment_d1,
    in4_lsb => n5_segment_d0,
    a => n1_a,
    b => n1_b,
    c => n1_c,
    d => n1_d,
    e => n1_e,
    f => n1_f,
    g => n1_g
  );
  u_1_c8259 : main_controller port map (
    clk50mhz => clk50mhz,
    target_bcd => sw_target_bcd,
    btn_start_stop => btn_start_stop,
    current_bcd_d1 => n2_current_bcd_d1,
    current_bcd_d0 => n2_current_bcd_d0,
    led_status => n2_led_status
  );
  u_2_c9312 : mod50k_sync port map (
    clk => clk50mhz,
    clk_mod50k => n3_clk_mod50k
  );
  u_3_c9404 : n_2_digit_bcd_7seg_decoder port map (
    current_bcd_d1 => n2_current_bcd_d1,
    current_bcd_d0 => n2_current_bcd_d0,
    clk_1khz => n3_clk_mod50k,
    segment_d3 => n5_segment_d3,
    segment_d2 => n5_segment_d2,
    segment_d1 => n5_segment_d1,
    segment_d0 => n5_segment_d0,
    d0 => n5_d0,
    d1 => n5_d1
  );

  -- output drivers
  led_status <= n2_led_status;
  a <= n1_a;
  b <= n1_b;
  c <= n1_c;
  d <= n1_d;
  e <= n1_e;
  f <= n1_f;
  g <= n1_g;
  d0 <= n5_d0;
  d1 <= n5_d1;
  d2 <= STD_LOGIC'('0');
  d3 <= STD_LOGIC'('0');

end Behavioral;
