-- ============================================================
-- Entity: main_controller
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: main_controller

entity main_controller is
  Port (
    clk50mhz : in  STD_LOGIC;
    target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    btn_start_stop : in  STD_LOGIC;
    current_bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0);
    current_bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0);
    led_status : out STD_LOGIC
  );
end main_controller;

architecture Behavioral of main_controller is
  component debounce_toggle
    Port (
      sw_in : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      toggle_output : out STD_LOGIC
    );
  end component;
  component mod2_5m_sync
    Port (
      clk : in  STD_LOGIC;
      clk_mod25m : out STD_LOGIC
    );
  end component;
  component start_stop_controller
    Port (
      target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      toggle_output : in  STD_LOGIC;
      current_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      start_flag : out STD_LOGIC;
      error_flag : out STD_LOGIC
    );
  end component;
  component main_counter
    Port (
      target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
      clk_20hz : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      current_d1 : out STD_LOGIC_VECTOR(3 downto 0);
      current_d0 : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      clk_mod50k : out STD_LOGIC
    );
  end component;
  component concat4bit_8bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(3 downto 0);
      rhs : in  STD_LOGIC_VECTOR(3 downto 0);
      out8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component n_8bit_1_clk_delay
    Port (
      n_8bit_in : in  STD_LOGIC_VECTOR(7 downto 0);
      clk : in  STD_LOGIC;
      n_8bit_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_toggle_output, n2_clk_mod25m, n3_start_flag, n3_error_flag, n5_o, n8_clk_mod50k : STD_LOGIC;
  signal n6_current_d1 : STD_LOGIC_VECTOR(3 downto 0);
  signal n6_current_d0 : STD_LOGIC_VECTOR(3 downto 0);
  signal n11_out8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n14_n_8bit_out : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n5_o <= n3_start_flag and n2_clk_mod25m;

  -- sub-component instantiations
  u_0_c7683 : debounce_toggle port map (
    sw_in => btn_start_stop,
    clk_50mhz => clk50mhz,
    clk_1khz => n8_clk_mod50k,
    toggle_output => n1_toggle_output
  );
  u_1_c7685 : mod2_5m_sync port map (
    clk => clk50mhz,
    clk_mod25m => n2_clk_mod25m
  );
  u_2_c7732 : start_stop_controller port map (
    target_bcd => target_bcd,
    toggle_output => n1_toggle_output,
    current_bcd => n14_n_8bit_out,
    start_flag => n3_start_flag,
    error_flag => n3_error_flag
  );
  u_3_c8251 : main_counter port map (
    target_bcd => target_bcd,
    clk_20hz => n5_o,
    clk_50mhz => clk50mhz,
    current_d1 => n6_current_d1,
    current_d0 => n6_current_d0
  );
  u_4_c9263 : mod50k_sync port map (
    clk => clk50mhz,
    clk_mod50k => n8_clk_mod50k
  );
  u_5_c9279 : concat4bit_8bit port map (
    lhs => n6_current_d1,
    rhs => n6_current_d0,
    out8bit => n11_out8bit
  );
  u_6_c9531 : n_8bit_1_clk_delay port map (
    n_8bit_in => n11_out8bit,
    clk => clk50mhz,
    n_8bit_out => n14_n_8bit_out
  );

  -- output drivers
  current_bcd_d1 <= n6_current_d1;
  current_bcd_d0 <= n6_current_d0;
  led_status <= n3_error_flag;

end Behavioral;