-- ============================================================
-- Entity: main_counter
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: main_counter

entity main_counter is
  Port (
    target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    clk_20hz : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    current_d1 : out STD_LOGIC_VECTOR(3 downto 0);
    current_d0 : out STD_LOGIC_VECTOR(3 downto 0)
  );
end main_counter;

architecture Behavioral of main_counter is
  component counter00_99_bcd
    Port (
      clk_20hz : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      bcd_d1 : out STD_LOGIC_VECTOR(3 downto 0);
      bcd_d0 : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component concat4bit_8bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(3 downto 0);
      rhs : in  STD_LOGIC_VECTOR(3 downto 0);
      out8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component n_8bit_1_clk_delay
    Port (
      n_8bit_in : in  STD_LOGIC_VECTOR(7 downto 0);
      clk : in  STD_LOGIC;
      n_8bit_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_eq : STD_LOGIC;
  signal n2_bcd_d1 : STD_LOGIC_VECTOR(3 downto 0);
  signal n2_bcd_d0 : STD_LOGIC_VECTOR(3 downto 0);
  signal n3_out8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n4_n_8bit_out : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_eq <= '1' when target_bcd = n4_n_8bit_out else '0';

  -- sub-component instantiations
  u_0_c8599 : counter00_99_bcd port map (
    clk_20hz => clk_20hz,
    reset => n1_eq,
    bcd_d1 => n2_bcd_d1,
    bcd_d0 => n2_bcd_d0
  );
  u_1_c9045 : concat4bit_8bit port map (
    lhs => n2_bcd_d1,
    rhs => n2_bcd_d0,
    out8bit => n3_out8bit
  );
  u_2_c9565 : n_8bit_1_clk_delay port map (
    n_8bit_in => n3_out8bit,
    clk => clk_50mhz,
    n_8bit_out => n4_n_8bit_out
  );

  -- output drivers
  current_d1 <= n2_bcd_d1;
  current_d0 <= n2_bcd_d0;

end Behavioral;