-- ============================================================
-- Entity: mod50k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50k_sync

entity mod50k_sync is
  Port (
    clk : in  STD_LOGIC;
    clk_mod50k : out STD_LOGIC
  );
end mod50k_sync;

architecture Behavioral of mod50k_sync is
  component mod5_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c9232 : mod5_sync port map (
    last_output => STD_LOGIC'('1'),
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c9233 : mod10_sync port map (
    last_output => n1_mod5_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );
  u_2_c9234 : mod10_sync port map (
    last_output => n2_mod10_out,
    clk => clk,
    mod10_out => n3_mod10_out
  );
  u_3_c9235 : mod10_sync port map (
    last_output => n3_mod10_out,
    clk => clk,
    mod10_out => n4_mod10_out
  );
  u_4_c9236 : mod10_sync port map (
    last_output => n4_mod10_out,
    clk => clk,
    mod10_out => n5_mod10_out
  );

  -- output drivers
  clk_mod50k <= n5_mod10_out;

end Behavioral;