library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n3_o, n6_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n5_qn : STD_LOGIC := '1';
  signal n13_q : STD_LOGIC := '0';
  signal n13_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n3_o <= last_output and n1_q;
  n6_o <= n3_o and n2_q;
  n12_o <= n5_q and n2_qn and n1_q;

  -- sequential logic (flip-flops)
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (last_output='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n3_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n5_q <= '0';
      n5_qn <= '1';
    elsif rising_edge(clk) then
      if (n6_o='1') then n5_q <= not n5_q; n5_qn <= not n5_qn; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n13_q  <= '0';
      n13_qn <= '1';
    elsif rising_edge(clk) then
      n13_q  <= n12_o;
      n13_qn <= not (n12_o);
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;
