-- ============================================================
-- Entity: n_8_bit_sync_counter_with_target
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: n_8_bit_sync_counter_with_target

entity n_8_bit_sync_counter_with_target is
  Port (
    trigger : in  STD_LOGIC;
    target : in  STD_LOGIC_VECTOR(7 downto 0);
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    limit_reached : out STD_LOGIC;
    current : out STD_LOGIC_VECTOR(7 downto 0)
  );
end n_8_bit_sync_counter_with_target;

architecture Behavioral of n_8_bit_sync_counter_with_target is
  signal n3_o, n5_o, n7_o, n9_o, n11_o, n13_o, n15_o, n30_eq, n31_o, n34_o, n37_o, n40_o, n43_o, n46_o, n49_o, n52_o, n54_o, n71_o, n74_o, n77_o, n80_o, n83_o, n86_o, n89_o, n92_o : STD_LOGIC;
  signal comp_b_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
  signal n8_q : STD_LOGIC := '0';
  signal n8_qn : STD_LOGIC := '1';
  signal n10_q : STD_LOGIC := '0';
  signal n10_qn : STD_LOGIC := '1';
  signal n12_q : STD_LOGIC := '0';
  signal n12_qn : STD_LOGIC := '1';
  signal n14_q : STD_LOGIC := '0';
  signal n14_qn : STD_LOGIC := '1';
  signal n55_q : STD_LOGIC := '0';
  signal n55_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n3_o <= trigger and n1_q;
  n5_o <= n3_o and n2_q;
  n7_o <= n5_o and n4_q;
  n9_o <= n7_o and n6_q;
  n11_o <= n9_o and n8_q;
  n13_o <= n11_o and n10_q;
  n15_o <= n13_o and n12_q;
  n30_eq <= '1' when target = comp_b_bus else '0';
  n31_o <= n1_q;
  n34_o <= n2_q;
  n37_o <= n4_q;
  n40_o <= n6_q;
  n43_o <= n8_q;
  n46_o <= n10_q;
  n49_o <= n12_q;
  n52_o <= n14_q;
  n54_o <= n30_eq or reset;
  n71_o <= n1_q;
  n74_o <= n2_q;
  n77_o <= n4_q;
  n80_o <= n6_q;
  n83_o <= n8_q;
  n86_o <= n10_q;
  n89_o <= n12_q;
  n92_o <= n14_q;

  -- sequential logic (flip-flops)
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n3_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n4_q <= not n4_q; n4_qn <= not n4_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n6_q <= '0';
      n6_qn <= '1';
    elsif rising_edge(clk) then
      if (n7_o='1') then n6_q <= not n6_q; n6_qn <= not n6_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n8_q <= '0';
      n8_qn <= '1';
    elsif rising_edge(clk) then
      if (n9_o='1') then n8_q <= not n8_q; n8_qn <= not n8_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n10_q <= '0';
      n10_qn <= '1';
    elsif rising_edge(clk) then
      if (n11_o='1') then n10_q <= not n10_q; n10_qn <= not n10_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n12_q <= '0';
      n12_qn <= '1';
    elsif rising_edge(clk) then
      if (n13_o='1') then n12_q <= not n12_q; n12_qn <= not n12_qn; end if;
    end if;
  end process;
  process(clk, n55_q)
  begin
    if n55_q = '1' then
      n14_q <= '0';
      n14_qn <= '1';
    elsif rising_edge(clk) then
      if (n15_o='1') then n14_q <= not n14_q; n14_qn <= not n14_qn; end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n55_q  <= n54_o;
      n55_qn <= not (n54_o);
    end if;
  end process;

  -- output drivers
  limit_reached <= n30_eq;
  current(0) <= n31_o;
  current(1) <= n34_o;
  current(2) <= n37_o;
  current(3) <= n40_o;
  current(4) <= n43_o;
  current(5) <= n46_o;
  current(6) <= n49_o;
  current(7) <= n52_o;
  comp_b_bus(0) <= n71_o;
  comp_b_bus(1) <= n74_o;
  comp_b_bus(2) <= n77_o;
  comp_b_bus(3) <= n80_o;
  comp_b_bus(4) <= n83_o;
  comp_b_bus(5) <= n86_o;
  comp_b_bus(6) <= n89_o;
  comp_b_bus(7) <= n92_o;

end Behavioral;