-- ============================================================
-- Entity: n_8bit_1_clk_delay
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: n_8bit_1_clk_delay

entity n_8bit_1_clk_delay is
  Port (
    n_8bit_in : in  STD_LOGIC_VECTOR(7 downto 0);
    clk : in  STD_LOGIC;
    n_8bit_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end n_8bit_1_clk_delay;

architecture Behavioral of n_8bit_1_clk_delay is
  signal n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n5_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
  signal n7_q : STD_LOGIC := '0';
  signal n7_qn : STD_LOGIC := '1';
  signal n8_q : STD_LOGIC := '0';
  signal n8_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n9_y <= n_8bit_in(7);
  n10_y <= n_8bit_in(6);
  n11_y <= n_8bit_in(5);
  n12_y <= n_8bit_in(4);
  n13_y <= n_8bit_in(3);
  n14_y <= n_8bit_in(2);
  n15_y <= n_8bit_in(1);
  n16_y <= n_8bit_in(0);

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      n1_q  <= n9_y;
      n1_qn <= not (n9_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n2_q  <= n10_y;
      n2_qn <= not (n10_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n3_q  <= n11_y;
      n3_qn <= not (n11_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n4_q  <= n12_y;
      n4_qn <= not (n12_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n5_q  <= n13_y;
      n5_qn <= not (n13_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n6_q  <= n14_y;
      n6_qn <= not (n14_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n7_q  <= n15_y;
      n7_qn <= not (n15_y);
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n8_q  <= n16_y;
      n8_qn <= not (n16_y);
    end if;
  end process;

  -- output drivers
  n_8bit_out(7) <= n1_q;
  n_8bit_out(6) <= n2_q;
  n_8bit_out(5) <= n3_q;
  n_8bit_out(4) <= n4_q;
  n_8bit_out(3) <= n5_q;
  n_8bit_out(2) <= n6_q;
  n_8bit_out(1) <= n7_q;
  n_8bit_out(0) <= n8_q;

end Behavioral;