-- ============================================================
-- Entity: start_stop_controller
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: start_stop_controller

entity start_stop_controller is
  Port (
    target_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    toggle_output : in  STD_LOGIC;
    current_bcd : in  STD_LOGIC_VECTOR(7 downto 0);
    start_flag : out STD_LOGIC;
    error_flag : out STD_LOGIC
  );
end start_stop_controller;

architecture Behavioral of start_stop_controller is
  signal n1_gt, n1_lt, n2_o, n3_o, n4_gt, n4_lt, n20_o : STD_LOGIC;
  signal compm_b_bus : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_gt <= '1' when unsigned(target_bcd) > unsigned(current_bcd) else '0';
  n1_lt <= '1' when unsigned(target_bcd) < unsigned(current_bcd) else '0';
  n2_o <= not n20_o;
  n3_o <= n2_o and toggle_output;
  n4_gt <= '1' when unsigned(target_bcd) > unsigned(compm_b_bus) else '0';
  n4_lt <= '1' when unsigned(target_bcd) < unsigned(compm_b_bus) else '0';
  n20_o <= n1_lt or n4_gt;

  -- output drivers
  start_flag <= n3_o;
  error_flag <= n20_o;
  compm_b_bus(6) <= STD_LOGIC'('0');
  compm_b_bus(5) <= STD_LOGIC'('0');
  compm_b_bus(4) <= STD_LOGIC'('1');
  compm_b_bus(3) <= STD_LOGIC'('1');
  compm_b_bus(2) <= STD_LOGIC'('0');
  compm_b_bus(1) <= STD_LOGIC'('0');
  compm_b_bus(0) <= STD_LOGIC'('1');
  compm_b_bus(7) <= STD_LOGIC'('1');

end Behavioral;