-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
  Port (
    in1_msb : in  STD_LOGIC;
    in2 : in  STD_LOGIC;
    in3 : in  STD_LOGIC;
    in4_lsb : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC
  );
end hex_7seg;

architecture Behavioral of hex_7seg is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in1_msb and in2 and n40_o and in4_lsb;
  n2_o <= in1_msb and n39_o and in3 and in4_lsb;
  n3_o <= n36_o and in2 and n37_o and n38_o;
  n4_o <= n33_o and n34_o and n35_o and in4_lsb;
  n5_o <= n4_o or n3_o or n2_o or n1_o;
  n6_o <= in2 and in3 and n44_o;
  n7_o <= in1_msb and in3 and in4_lsb;
  n8_o <= in1_msb and in2 and n43_o;
  n9_o <= n41_o and in2 and n42_o and in4_lsb;
  n10_o <= n9_o or n8_o or n7_o or n6_o;
  n11_o <= in1_msb and in2 and n48_o;
  n12_o <= in1_msb and in2 and in3;
  n13_o <= n45_o and n46_o and in3 and n47_o;
  n14_o <= n13_o or n12_o or n11_o;
  n15_o <= in2 and in3 and in4_lsb;
  n16_o <= in1_msb and n55_o and in3 and n56_o;
  n17_o <= n52_o and in2 and n53_o and n54_o;
  n18_o <= n49_o and n50_o and n51_o and in4_lsb;
  n19_o <= n18_o or n17_o or n16_o or n15_o;
  n20_o <= n60_o and n61_o and in4_lsb;
  n21_o <= n59_o and in4_lsb;
  n22_o <= n57_o and in2 and n58_o;
  n23_o <= n22_o or n21_o or n20_o;
  n24_o <= in1_msb and in2 and n67_o and in4_lsb;
  n25_o <= n66_o and in3 and in4_lsb;
  n26_o <= n64_o and n65_o and in4_lsb;
  n27_o <= n62_o and n63_o and in3;
  n28_o <= n27_o or n26_o or n25_o or n24_o;
  n29_o <= in1_msb and in2 and n72_o and n73_o;
  n30_o <= n71_o and in2 and in3 and in4_lsb;
  n31_o <= n68_o and n69_o and n70_o;
  n32_o <= n31_o or n30_o or n29_o;
  n33_o <= not in1_msb;
  n34_o <= not in2;
  n35_o <= not in3;
  n36_o <= not in1_msb;
  n37_o <= not in3;
  n38_o <= not in4_lsb;
  n39_o <= not in2;
  n40_o <= not in3;
  n41_o <= not in1_msb;
  n42_o <= not in3;
  n43_o <= not in4_lsb;
  n44_o <= not in4_lsb;
  n45_o <= not in1_msb;
  n46_o <= not in2;
  n47_o <= not in4_lsb;
  n48_o <= not in4_lsb;
  n49_o <= not in1_msb;
  n50_o <= not in2;
  n51_o <= not in3;
  n52_o <= not in1_msb;
  n53_o <= not in3;
  n54_o <= not in4_lsb;
  n55_o <= not in2;
  n56_o <= not in4_lsb;
  n57_o <= not in1_msb;
  n58_o <= not in3;
  n59_o <= not in1_msb;
  n60_o <= not in2;
  n61_o <= not in3;
  n62_o <= not in1_msb;
  n63_o <= not in2;
  n64_o <= not in1_msb;
  n65_o <= not in2;
  n66_o <= not in1_msb;
  n67_o <= not in3;
  n68_o <= not in1_msb;
  n69_o <= not in2;
  n70_o <= not in3;
  n71_o <= not in1_msb;
  n72_o <= not in3;
  n73_o <= not in4_lsb;

  -- output drivers
  a <= n5_o;
  b <= n10_o;
  c <= n14_o;
  d <= n19_o;
  e <= n23_o;
  f <= n28_o;
  g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: fa1
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: fa1

entity fa1 is
  Port (
    lhs : in  STD_LOGIC;
    rhs : in  STD_LOGIC;
    carry_in : in  STD_LOGIC;
    carry_out : out STD_LOGIC;
    sum : out STD_LOGIC
  );
end fa1;

architecture Behavioral of fa1 is
  signal n1_o, n2_o, n3_o, n4_o, n5_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= lhs xor rhs;
  n2_o <= n1_o xor carry_in;
  n3_o <= lhs and rhs;
  n4_o <= n1_o and carry_in;
  n5_o <= n3_o or n4_o;

  -- output drivers
  carry_out <= n5_o;
  sum <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: fas8
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: fas8

entity fas8 is
  Port (
    lhs_0_lsb : in  STD_LOGIC;
    rhs_0_lsb : in  STD_LOGIC;
    lhs_1 : in  STD_LOGIC;
    rhs_1 : in  STD_LOGIC;
    lhs_2 : in  STD_LOGIC;
    rhs_2 : in  STD_LOGIC;
    lhs_3 : in  STD_LOGIC;
    rhs_3 : in  STD_LOGIC;
    lhs_4 : in  STD_LOGIC;
    rhs_4 : in  STD_LOGIC;
    lhs_5 : in  STD_LOGIC;
    rhs_5 : in  STD_LOGIC;
    lhs_6 : in  STD_LOGIC;
    rhs_6 : in  STD_LOGIC;
    lhs_7_msb : in  STD_LOGIC;
    rhs_7_msb : in  STD_LOGIC;
    sub : in  STD_LOGIC;
    sum_0 : out STD_LOGIC;
    sum_1 : out STD_LOGIC;
    sum_2 : out STD_LOGIC;
    sum_3 : out STD_LOGIC;
    sum_4 : out STD_LOGIC;
    sum_5 : out STD_LOGIC;
    sum_6 : out STD_LOGIC;
    sum_7 : out STD_LOGIC;
    carry_out : out STD_LOGIC
  );
end fas8;

architecture Behavioral of fas8 is
  component fa1
    Port (
      lhs : in  STD_LOGIC;
      rhs : in  STD_LOGIC;
      carry_in : in  STD_LOGIC;
      carry_out : out STD_LOGIC;
      sum : out STD_LOGIC
    );
  end component;
  signal n1_carry_out, n1_sum, n2_o, n3_carry_out, n3_sum, n4_o, n5_carry_out, n5_sum, n6_o, n7_carry_out, n7_sum, n8_o, n9_carry_out, n9_sum, n10_o, n11_carry_out, n11_sum, n12_o, n13_carry_out, n13_sum, n14_o, n15_carry_out, n15_sum, n16_o : STD_LOGIC;
begin

  -- combinational logic
  n2_o <= sub xor rhs_0_lsb;
  n4_o <= sub xor rhs_1;
  n6_o <= sub xor rhs_2;
  n8_o <= sub xor rhs_3;
  n10_o <= sub xor rhs_4;
  n12_o <= sub xor rhs_5;
  n14_o <= sub xor rhs_6;
  n16_o <= sub xor rhs_7_msb;

  -- sub-component instantiations
  u_0_c5272 : fa1 port map (
    lhs => lhs_0_lsb,
    rhs => n2_o,
    carry_in => sub,
    carry_out => n1_carry_out,
    sum => n1_sum
  );
  u_1_c5316 : fa1 port map (
    lhs => lhs_1,
    rhs => n4_o,
    carry_in => n1_carry_out,
    carry_out => n3_carry_out,
    sum => n3_sum
  );
  u_2_c5325 : fa1 port map (
    lhs => lhs_2,
    rhs => n6_o,
    carry_in => n3_carry_out,
    carry_out => n5_carry_out,
    sum => n5_sum
  );
  u_3_c5334 : fa1 port map (
    lhs => lhs_3,
    rhs => n8_o,
    carry_in => n5_carry_out,
    carry_out => n7_carry_out,
    sum => n7_sum
  );
  u_4_c5343 : fa1 port map (
    lhs => lhs_4,
    rhs => n10_o,
    carry_in => n7_carry_out,
    carry_out => n9_carry_out,
    sum => n9_sum
  );
  u_5_c5352 : fa1 port map (
    lhs => lhs_5,
    rhs => n12_o,
    carry_in => n9_carry_out,
    carry_out => n11_carry_out,
    sum => n11_sum
  );
  u_6_c5361 : fa1 port map (
    lhs => lhs_6,
    rhs => n14_o,
    carry_in => n11_carry_out,
    carry_out => n13_carry_out,
    sum => n13_sum
  );
  u_7_c5370 : fa1 port map (
    lhs => lhs_7_msb,
    rhs => n16_o,
    carry_in => n13_carry_out,
    carry_out => n15_carry_out,
    sum => n15_sum
  );

  -- output drivers
  sum_0 <= n1_sum;
  sum_1 <= n3_sum;
  sum_2 <= n5_sum;
  sum_3 <= n7_sum;
  sum_4 <= n9_sum;
  sum_5 <= n11_sum;
  sum_6 <= n13_sum;
  sum_7 <= n15_sum;
  carry_out <= n15_carry_out;

end Behavioral;

-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n4_o, n5_o, n7_o, n9_o, n10_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n3_qn;
  n5_o <= trigger and n1_q;
  n7_o <= n2_q and n1_q;
  n9_o <= n3_q or n7_o;
  n10_o <= trigger and n9_o;
  n12_o <= trigger and n3_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (n4_o='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      if (n10_o='1') then n3_q <= not n3_q; n3_qn <= not n3_qn; end if;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod2_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod5_sync port map (
    trigger => n2_mod2_out,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c10682 : mod2_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod2_out => n2_mod2_out
  );

  -- output drivers
  mod10_out <= n1_mod5_out;

end Behavioral;

-- ============================================================
-- Entity: debounce_button
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_button

entity debounce_button is
  Port (
    button_signal : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    debounce_signal : out STD_LOGIC
  );
end debounce_button;

architecture Behavioral of debounce_button is
  component mod50_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod50_out : out STD_LOGIC
    );
  end component;
  signal n7_o, n9_mod50_out : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n7_o <= n3_q and n6_qn;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n1_q  <= button_signal;
      n1_qn <= not (button_signal);
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n2_q  <= n1_q;
      n2_qn <= not (n1_q);
    end if;
  end process;
  process(clk_50mhz, n2_qn)
  begin
    if n2_qn = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk_50mhz) then
      if    (n9_mod50_out='0' and STD_LOGIC'('0')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n9_mod50_out='1' and STD_LOGIC'('0')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n9_mod50_out='1' and STD_LOGIC'('0')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n6_q  <= n3_q;
      n6_qn <= not (n3_q);
    end if;
  end process;

  -- sub-component instantiations
  u_0_c16763 : mod50_sync port map (
    trigger => clk_1khz,
    clk => clk_50mhz,
    reset => n2_qn,
    mod50_out => n9_mod50_out
  );

  -- output drivers
  debounce_signal <= n7_o;

end Behavioral;

-- ============================================================
-- Entity: mod50k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50k_sync

entity mod50k_sync is
  Port (
    clk : in  STD_LOGIC;
    mod50k_out : out STD_LOGIC
  );
end mod50k_sync;

architecture Behavioral of mod50k_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c9232 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n1_mod5_out
  );
  u_1_c9233 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n2_mod10_out
  );
  u_2_c9234 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n3_mod10_out
  );
  u_3_c9235 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n4_mod10_out
  );
  u_4_c9236 : mod10_sync port map (
    trigger => n4_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n5_mod10_out
  );

  -- output drivers
  mod50k_out <= n5_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= trigger and n1_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: and_8bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_8bit_1bit

entity and_8bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC;
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end and_8bit_1bit;

architecture Behavioral of and_8bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n16_y and b;
  n2_o <= n17_y and b;
  n3_o <= n18_y and b;
  n4_o <= n19_y and b;
  n5_o <= n20_y and b;
  n6_o <= n21_y and b;
  n7_o <= n22_y and b;
  n8_o <= n23_y and b;
  n16_y <= a(7);
  n17_y <= a(6);
  n18_y <= a(5);
  n19_y <= a(4);
  n20_y <= a(3);
  n21_y <= a(2);
  n22_y <= a(1);
  n23_y <= a(0);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: or_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_8bit

entity or_8bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC_VECTOR(7 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end or_8bit;

architecture Behavioral of or_8bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y, n24_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n24_y or n23_y;
  n2_o <= n22_y or n21_y;
  n3_o <= n20_y or n19_y;
  n4_o <= n18_y or n17_y;
  n5_o <= n16_y or n15_y;
  n6_o <= n14_y or n13_y;
  n7_o <= n12_y or n11_y;
  n8_o <= n10_y or n9_y;
  n9_y <= b(0);
  n10_y <= a(0);
  n11_y <= b(1);
  n12_y <= a(1);
  n13_y <= b(2);
  n14_y <= a(2);
  n15_y <= b(3);
  n16_y <= a(3);
  n17_y <= b(4);
  n18_y <= a(4);
  n19_y <= b(5);
  n20_y <= a(5);
  n21_y <= b(6);
  n22_y <= a(6);
  n23_y <= b(7);
  n24_y <= a(7);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: hex_7seg_multiplexer
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg_multiplexer

entity hex_7seg_multiplexer is
  Port (
    d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    data_out : out STD_LOGIC_VECTOR(3 downto 0);
    d3 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d0 : out STD_LOGIC
  );
end hex_7seg_multiplexer;

architecture Behavioral of hex_7seg_multiplexer is
  component and_4bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC;
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component or_4bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC_VECTOR(3 downto 0);
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  signal n4_o, n6_o, n7_o, n8_o, n9_o, n23_o, n24_o, n26_o, n27_o : STD_LOGIC;
  signal n10_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n11_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n12_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n14_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n15_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n16_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n2_q;
  n6_o <= n23_o and n24_o;
  n7_o <= n26_o and n2_q;
  n8_o <= n1_q and n27_o;
  n9_o <= n1_q and n2_q;
  n23_o <= not n1_q;
  n24_o <= not n2_q;
  n26_o <= not n1_q;
  n27_o <= not n2_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n4_o='0' and n4_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n4_o='1' and n4_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n4_o='1' and n4_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (trigger='0' and trigger='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (trigger='1' and trigger='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (trigger='1' and trigger='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c14777 : and_4bit_1bit port map (
    a => d3_data,
    b => n9_o,
    out_data => n10_out_data
  );
  u_1_c14779 : and_4bit_1bit port map (
    a => d2_data,
    b => n8_o,
    out_data => n11_out_data
  );
  u_2_c14781 : and_4bit_1bit port map (
    a => d1_data,
    b => n7_o,
    out_data => n12_out_data
  );
  u_3_c14783 : and_4bit_1bit port map (
    a => d0_data,
    b => n6_o,
    out_data => n13_out_data
  );
  u_4_c14875 : or_4bit port map (
    a => n11_out_data,
    b => n15_out_data,
    out_data => n14_out_data
  );
  u_5_c14876 : or_4bit port map (
    a => n12_out_data,
    b => n13_out_data,
    out_data => n15_out_data
  );
  u_6_c14877 : or_4bit port map (
    a => n10_out_data,
    b => n14_out_data,
    out_data => n16_out_data
  );

  -- output drivers
  data_out <= n16_out_data;
  d3 <= n6_o;
  d2 <= n7_o;
  d1 <= n8_o;
  d0 <= n9_o;

end Behavioral;

-- ============================================================
-- Entity: and_4bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_4bit_1bit

entity and_4bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC;
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end and_4bit_1bit;

architecture Behavioral of and_4bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n8_y, n9_y, n10_y, n11_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n8_y and b;
  n2_o <= n9_y and b;
  n3_o <= n10_y and b;
  n4_o <= n11_y and b;
  n8_y <= a(3);
  n9_y <= a(2);
  n10_y <= a(1);
  n11_y <= a(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: or_4bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_4bit

entity or_4bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC_VECTOR(3 downto 0);
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end or_4bit;

architecture Behavioral of or_4bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n5_y or n6_y;
  n2_o <= n7_y or n8_y;
  n3_o <= n9_y or n10_y;
  n4_o <= n11_y or n12_y;
  n5_y <= a(3);
  n6_y <= b(3);
  n7_y <= a(2);
  n8_y <= b(2);
  n9_y <= a(1);
  n10_y <= b(1);
  n11_y <= a(0);
  n12_y <= b(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: add8_bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: add8_bit

entity add8_bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    sum_8bit : out STD_LOGIC_VECTOR(7 downto 0);
    carry_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end add8_bit;

architecture Behavioral of add8_bit is
  component fas8
    Port (
      lhs_0_lsb : in  STD_LOGIC;
      rhs_0_lsb : in  STD_LOGIC;
      lhs_1 : in  STD_LOGIC;
      rhs_1 : in  STD_LOGIC;
      lhs_2 : in  STD_LOGIC;
      rhs_2 : in  STD_LOGIC;
      lhs_3 : in  STD_LOGIC;
      rhs_3 : in  STD_LOGIC;
      lhs_4 : in  STD_LOGIC;
      rhs_4 : in  STD_LOGIC;
      lhs_5 : in  STD_LOGIC;
      rhs_5 : in  STD_LOGIC;
      lhs_6 : in  STD_LOGIC;
      rhs_6 : in  STD_LOGIC;
      lhs_7_msb : in  STD_LOGIC;
      rhs_7_msb : in  STD_LOGIC;
      sub : in  STD_LOGIC;
      sum_0 : out STD_LOGIC;
      sum_1 : out STD_LOGIC;
      sum_2 : out STD_LOGIC;
      sum_3 : out STD_LOGIC;
      sum_4 : out STD_LOGIC;
      sum_5 : out STD_LOGIC;
      sum_6 : out STD_LOGIC;
      sum_7 : out STD_LOGIC;
      carry_out : out STD_LOGIC
    );
  end component;
  signal n1_sum_0, n1_sum_1, n1_sum_2, n1_sum_3, n1_sum_4, n1_sum_5, n1_sum_6, n1_sum_7, n1_carry_out, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y : STD_LOGIC;
begin

  -- combinational logic
  n2_y <= lhs(0);
  n3_y <= rhs(0);
  n4_y <= lhs(1);
  n5_y <= rhs(1);
  n6_y <= lhs(2);
  n7_y <= rhs(2);
  n8_y <= lhs(3);
  n9_y <= rhs(3);
  n10_y <= lhs(4);
  n11_y <= rhs(4);
  n12_y <= lhs(5);
  n13_y <= rhs(5);
  n14_y <= lhs(6);
  n15_y <= rhs(6);
  n16_y <= lhs(7);
  n17_y <= rhs(7);

  -- sub-component instantiations
  u_0_c15849 : fas8 port map (
    lhs_0_lsb => n2_y,
    rhs_0_lsb => n3_y,
    lhs_1 => n4_y,
    rhs_1 => n5_y,
    lhs_2 => n6_y,
    rhs_2 => n7_y,
    lhs_3 => n8_y,
    rhs_3 => n9_y,
    lhs_4 => n10_y,
    rhs_4 => n11_y,
    lhs_5 => n12_y,
    rhs_5 => n13_y,
    lhs_6 => n14_y,
    rhs_6 => n15_y,
    lhs_7_msb => n16_y,
    rhs_7_msb => n17_y,
    sub => STD_LOGIC'('0'),
    sum_0 => n1_sum_0,
    sum_1 => n1_sum_1,
    sum_2 => n1_sum_2,
    sum_3 => n1_sum_3,
    sum_4 => n1_sum_4,
    sum_5 => n1_sum_5,
    sum_6 => n1_sum_6,
    sum_7 => n1_sum_7,
    carry_out => n1_carry_out
  );

  -- output drivers
  sum_8bit(0) <= n1_sum_0;
  sum_8bit(1) <= n1_sum_1;
  sum_8bit(2) <= n1_sum_2;
  sum_8bit(3) <= n1_sum_3;
  sum_8bit(4) <= n1_sum_4;
  sum_8bit(5) <= n1_sum_5;
  sum_8bit(6) <= n1_sum_6;
  sum_8bit(7) <= n1_sum_7;
  carry_out(0) <= n1_carry_out;
  carry_out(1) <= STD_LOGIC'('0');
  carry_out(2) <= STD_LOGIC'('0');
  carry_out(3) <= STD_LOGIC'('0');
  carry_out(4) <= STD_LOGIC'('0');
  carry_out(5) <= STD_LOGIC'('0');
  carry_out(6) <= STD_LOGIC'('0');
  carry_out(7) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: sub8_bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: sub8_bit

entity sub8_bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    sub_8bit : out STD_LOGIC_VECTOR(7 downto 0);
    carry_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end sub8_bit;

architecture Behavioral of sub8_bit is
  component fas8
    Port (
      lhs_0_lsb : in  STD_LOGIC;
      rhs_0_lsb : in  STD_LOGIC;
      lhs_1 : in  STD_LOGIC;
      rhs_1 : in  STD_LOGIC;
      lhs_2 : in  STD_LOGIC;
      rhs_2 : in  STD_LOGIC;
      lhs_3 : in  STD_LOGIC;
      rhs_3 : in  STD_LOGIC;
      lhs_4 : in  STD_LOGIC;
      rhs_4 : in  STD_LOGIC;
      lhs_5 : in  STD_LOGIC;
      rhs_5 : in  STD_LOGIC;
      lhs_6 : in  STD_LOGIC;
      rhs_6 : in  STD_LOGIC;
      lhs_7_msb : in  STD_LOGIC;
      rhs_7_msb : in  STD_LOGIC;
      sub : in  STD_LOGIC;
      sum_0 : out STD_LOGIC;
      sum_1 : out STD_LOGIC;
      sum_2 : out STD_LOGIC;
      sum_3 : out STD_LOGIC;
      sum_4 : out STD_LOGIC;
      sum_5 : out STD_LOGIC;
      sum_6 : out STD_LOGIC;
      sum_7 : out STD_LOGIC;
      carry_out : out STD_LOGIC
    );
  end component;
  signal n1_sum_0, n1_sum_1, n1_sum_2, n1_sum_3, n1_sum_4, n1_sum_5, n1_sum_6, n1_sum_7, n1_carry_out, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y : STD_LOGIC;
begin

  -- combinational logic
  n2_y <= lhs(0);
  n3_y <= rhs(0);
  n4_y <= lhs(1);
  n5_y <= rhs(1);
  n6_y <= lhs(2);
  n7_y <= rhs(2);
  n8_y <= lhs(3);
  n9_y <= rhs(3);
  n10_y <= lhs(4);
  n11_y <= rhs(4);
  n12_y <= lhs(5);
  n13_y <= rhs(5);
  n14_y <= lhs(6);
  n15_y <= rhs(6);
  n16_y <= lhs(7);
  n17_y <= rhs(7);

  -- sub-component instantiations
  u_0_c16145 : fas8 port map (
    lhs_0_lsb => n2_y,
    rhs_0_lsb => n3_y,
    lhs_1 => n4_y,
    rhs_1 => n5_y,
    lhs_2 => n6_y,
    rhs_2 => n7_y,
    lhs_3 => n8_y,
    rhs_3 => n9_y,
    lhs_4 => n10_y,
    rhs_4 => n11_y,
    lhs_5 => n12_y,
    rhs_5 => n13_y,
    lhs_6 => n14_y,
    rhs_6 => n15_y,
    lhs_7_msb => n16_y,
    rhs_7_msb => n17_y,
    sub => STD_LOGIC'('1'),
    sum_0 => n1_sum_0,
    sum_1 => n1_sum_1,
    sum_2 => n1_sum_2,
    sum_3 => n1_sum_3,
    sum_4 => n1_sum_4,
    sum_5 => n1_sum_5,
    sum_6 => n1_sum_6,
    sum_7 => n1_sum_7,
    carry_out => n1_carry_out
  );

  -- output drivers
  sub_8bit(0) <= n1_sum_0;
  sub_8bit(1) <= n1_sum_1;
  sub_8bit(2) <= n1_sum_2;
  sub_8bit(3) <= n1_sum_3;
  sub_8bit(4) <= n1_sum_4;
  sub_8bit(5) <= n1_sum_5;
  sub_8bit(6) <= n1_sum_6;
  sub_8bit(7) <= n1_sum_7;
  carry_out(0) <= n1_carry_out;
  carry_out(1) <= STD_LOGIC'('0');
  carry_out(2) <= STD_LOGIC'('0');
  carry_out(3) <= STD_LOGIC'('0');
  carry_out(4) <= STD_LOGIC'('0');
  carry_out(5) <= STD_LOGIC'('0');
  carry_out(6) <= STD_LOGIC'('0');
  carry_out(7) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: xor_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: xor_8bit

entity xor_8bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    xor_8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end xor_8bit;

architecture Behavioral of xor_8bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y, n24_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n9_y xor n10_y;
  n2_o <= n11_y xor n12_y;
  n3_o <= n13_y xor n14_y;
  n4_o <= n15_y xor n16_y;
  n5_o <= n17_y xor n18_y;
  n6_o <= n19_y xor n20_y;
  n7_o <= n21_y xor n22_y;
  n8_o <= n23_y xor n24_y;
  n9_y <= lhs(7);
  n10_y <= rhs(7);
  n11_y <= lhs(6);
  n12_y <= rhs(6);
  n13_y <= lhs(5);
  n14_y <= rhs(5);
  n15_y <= lhs(4);
  n16_y <= rhs(4);
  n17_y <= lhs(3);
  n18_y <= rhs(3);
  n19_y <= lhs(2);
  n20_y <= rhs(2);
  n21_y <= lhs(1);
  n22_y <= rhs(1);
  n23_y <= lhs(0);
  n24_y <= rhs(0);

  -- output drivers
  xor_8bit(7) <= n1_o;
  xor_8bit(6) <= n2_o;
  xor_8bit(5) <= n3_o;
  xor_8bit(4) <= n4_o;
  xor_8bit(3) <= n5_o;
  xor_8bit(2) <= n6_o;
  xor_8bit(1) <= n7_o;
  xor_8bit(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: shl_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: shl_8bit

entity shl_8bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    shl_8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end shl_8bit;

architecture Behavioral of shl_8bit is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n15_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= in0(6);
  n2_y <= in0(5);
  n3_y <= in0(4);
  n4_y <= in0(3);
  n5_y <= in0(2);
  n6_y <= in0(1);
  n15_y <= in0(0);

  -- output drivers
  shl_8bit(7) <= n1_y;
  shl_8bit(6) <= n2_y;
  shl_8bit(5) <= n3_y;
  shl_8bit(4) <= n4_y;
  shl_8bit(3) <= n5_y;
  shl_8bit(2) <= n6_y;
  shl_8bit(1) <= n15_y;
  shl_8bit(0) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: mod50_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50_sync

entity mod50_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod50_out : out STD_LOGIC
  );
end mod50_sync;

architecture Behavioral of mod50_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c16652 : mod5_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c16653 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => reset,
    mod10_out => n2_mod10_out
  );

  -- output drivers
  mod50_out <= n2_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: lab10
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab10

entity lab10 is
  Port (
    operator : in  STD_LOGIC_VECTOR(2 downto 0);
    data : in  STD_LOGIC_VECTOR(7 downto 0);
    step : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d3 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d0 : out STD_LOGIC;
    carry_led : out STD_LOGIC;
    overflow_led : out STD_LOGIC;
    zero_led : out STD_LOGIC
  );
end lab10;

architecture Behavioral of lab10 is
  component debounce_button
    Port (
      button_signal : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      debounce_signal : out STD_LOGIC
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      mod50k_out : out STD_LOGIC
    );
  end component;
  component hex_7seg_multiplexer
    Port (
      d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      data_out : out STD_LOGIC_VECTOR(3 downto 0);
      d3 : out STD_LOGIC;
      d2 : out STD_LOGIC;
      d1 : out STD_LOGIC;
      d0 : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component splitter8_4bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      msb : out STD_LOGIC_VECTOR(3 downto 0);
      lsb : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component alu
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sel : in  STD_LOGIC_VECTOR(2 downto 0);
      product : out STD_LOGIC_VECTOR(7 downto 0);
      flag : out STD_LOGIC_VECTOR(2 downto 0)
    );
  end component;
  component register_8bit
    Port (
      set_in : in  STD_LOGIC_VECTOR(7 downto 0);
      set : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      stored : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component register_3bit
    Port (
      set_in : in  STD_LOGIC_VECTOR(2 downto 0);
      set : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      stored : out STD_LOGIC_VECTOR(2 downto 0)
    );
  end component;
  signal n1_debounce_signal, n2_debounce_signal, n3_mod50k_out, n6_d3, n6_d2, n6_d1, n6_d0, n7_a, n7_b, n7_c, n7_d, n7_e, n7_f, n7_g, n8_y, n9_y, n10_y, n11_y, n17_y, n18_y, n19_y : STD_LOGIC;
  signal n6_data_out : STD_LOGIC_VECTOR(3 downto 0);
  signal n12_msb : STD_LOGIC_VECTOR(3 downto 0);
  signal n12_lsb : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_msb : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_lsb : STD_LOGIC_VECTOR(3 downto 0);
  signal n25_product : STD_LOGIC_VECTOR(7 downto 0);
  signal n25_flag : STD_LOGIC_VECTOR(2 downto 0);
  signal n27_stored : STD_LOGIC_VECTOR(7 downto 0);
  signal n29_stored : STD_LOGIC_VECTOR(2 downto 0);
begin

  -- combinational logic
  n8_y <= n6_data_out(3);
  n9_y <= n6_data_out(2);
  n10_y <= n6_data_out(1);
  n11_y <= n6_data_out(0);
  n17_y <= n29_stored(2);
  n18_y <= n29_stored(1);
  n19_y <= n29_stored(0);

  -- sub-component instantiations
  u_0_c18624 : debounce_button port map (
    button_signal => step,
    clk_50mhz => clk,
    clk_1khz => n3_mod50k_out,
    debounce_signal => n1_debounce_signal
  );
  u_1_c18625 : debounce_button port map (
    button_signal => reset,
    clk_50mhz => clk,
    clk_1khz => n3_mod50k_out,
    debounce_signal => n2_debounce_signal
  );
  u_2_c18627 : mod50k_sync port map (
    clk => clk,
    mod50k_out => n3_mod50k_out
  );
  u_3_c18653 : hex_7seg_multiplexer port map (
    d3_data => n12_msb,
    d2_data => n12_lsb,
    d1_data => n13_msb,
    d0_data => n13_lsb,
    trigger => n3_mod50k_out,
    clk => clk,
    data_out => n6_data_out,
    d3 => n6_d3,
    d2 => n6_d2,
    d1 => n6_d1,
    d0 => n6_d0
  );
  u_4_c18654 : hex_7seg port map (
    in1_msb => n8_y,
    in2 => n9_y,
    in3 => n10_y,
    in4_lsb => n11_y,
    a => n7_a,
    b => n7_b,
    c => n7_c,
    d => n7_d,
    e => n7_e,
    f => n7_f,
    g => n7_g
  );
  u_5_c18789 : splitter8_4bit port map (
    in0 => data,
    msb => n12_msb,
    lsb => n12_lsb
  );
  u_6_c18790 : splitter8_4bit port map (
    in0 => n27_stored,
    msb => n13_msb,
    lsb => n13_lsb
  );
  u_7_c19942 : alu port map (
    lhs => n27_stored,
    rhs => data,
    sel => operator,
    product => n25_product,
    flag => n25_flag
  );
  u_8_c20590 : register_8bit port map (
    set_in => n25_product,
    set => n1_debounce_signal,
    clk => clk,
    reset => n2_debounce_signal,
    stored => n27_stored
  );
  u_9_c21223 : register_3bit port map (
    set_in => n25_flag,
    set => n1_debounce_signal,
    clk => clk,
    reset => n2_debounce_signal,
    stored => n29_stored
  );

  -- output drivers
  a <= n7_a;
  b <= n7_b;
  c <= n7_c;
  d <= n7_d;
  e <= n7_e;
  f <= n7_f;
  g <= n7_g;
  d3 <= n6_d3;
  d2 <= n6_d2;
  d1 <= n6_d1;
  d0 <= n6_d0;
  carry_led <= n17_y;
  overflow_led <= n18_y;
  zero_led <= n19_y;

end Behavioral;

-- ============================================================
-- Entity: splitter8_4bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: splitter8_4bit

entity splitter8_4bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    msb : out STD_LOGIC_VECTOR(3 downto 0);
    lsb : out STD_LOGIC_VECTOR(3 downto 0)
  );
end splitter8_4bit;

architecture Behavioral of splitter8_4bit is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= in0(7);
  n2_y <= in0(6);
  n3_y <= in0(5);
  n4_y <= in0(4);
  n5_y <= in0(3);
  n6_y <= in0(2);
  n7_y <= in0(1);
  n8_y <= in0(0);

  -- output drivers
  msb(3) <= n1_y;
  msb(2) <= n2_y;
  msb(1) <= n3_y;
  msb(0) <= n4_y;
  lsb(3) <= n5_y;
  lsb(2) <= n6_y;
  lsb(1) <= n7_y;
  lsb(0) <= n8_y;

end Behavioral;

-- ============================================================
-- Entity: alu
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: alu

entity alu is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    sel : in  STD_LOGIC_VECTOR(2 downto 0);
    product : out STD_LOGIC_VECTOR(7 downto 0);
    flag : out STD_LOGIC_VECTOR(2 downto 0)
  );
end alu;

architecture Behavioral of alu is
  component add8_bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sum_8bit : out STD_LOGIC_VECTOR(7 downto 0);
      carry_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component sub8_bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sub_8bit : out STD_LOGIC_VECTOR(7 downto 0);
      carry_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component xor_8bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      xor_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component or_8bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC_VECTOR(7 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component and_8bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      and_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component mux8_1_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      in1 : in  STD_LOGIC_VECTOR(7 downto 0);
      in2 : in  STD_LOGIC_VECTOR(7 downto 0);
      in3 : in  STD_LOGIC_VECTOR(7 downto 0);
      in4 : in  STD_LOGIC_VECTOR(7 downto 0);
      in5 : in  STD_LOGIC_VECTOR(7 downto 0);
      in6 : in  STD_LOGIC_VECTOR(7 downto 0);
      in7 : in  STD_LOGIC_VECTOR(7 downto 0);
      sel : in  STD_LOGIC_VECTOR(2 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component shl8_n
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      shl8_n : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n22_y, n23_y, n24_eq, n40_o, n41_o, n42_y, n43_y, n44_y, n45_y, n46_y, n47_y, n48_o, n49_o, n50_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n64_o, n65_y, n66_y, n67_o, n76_o, n77_y, n78_y, n83_o : STD_LOGIC;
  signal n1_sum_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n1_carry_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n2_sub_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n2_carry_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n3_xor_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n4_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n5_and_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n6_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n10_shl8_n : STD_LOGIC_VECTOR(7 downto 0);
  signal comp_a_bus : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n22_y <= n1_carry_out(0);
  n23_y <= n2_carry_out(0);
  n24_eq <= '1' when comp_a_bus = n6_output else '0';
  n40_o <= n48_o and n49_o and n44_y;
  n41_o <= n50_o and n46_y and n57_o;
  n42_y <= sel(2);
  n43_y <= sel(1);
  n44_y <= sel(0);
  n45_y <= sel(2);
  n46_y <= sel(1);
  n47_y <= sel(0);
  n48_o <= not n42_y;
  n49_o <= not n43_y;
  n50_o <= not n45_y;
  n56_o <= not n23_y;
  n57_o <= not n47_y;
  n58_o <= n22_y and n40_o;
  n59_o <= n56_o and n41_o;
  n60_o <= n58_o or n59_o;
  n61_o <= n40_o or n41_o;
  n64_o <= n61_o and n76_o and n67_o;
  n65_y <= lhs(7);
  n66_y <= rhs(7);
  n67_o <= not (n65_y xor n83_o);
  n76_o <= n77_y xor n78_y;
  n77_y <= lhs(7);
  n78_y <= n6_output(7);
  n83_o <= n66_y xor n41_o;

  -- sub-component instantiations
  u_0_c18928 : add8_bit port map (
    lhs => lhs,
    rhs => rhs,
    sum_8bit => n1_sum_8bit,
    carry_out => n1_carry_out
  );
  u_1_c18929 : sub8_bit port map (
    lhs => lhs,
    rhs => rhs,
    sub_8bit => n2_sub_8bit,
    carry_out => n2_carry_out
  );
  u_2_c18930 : xor_8bit port map (
    lhs => lhs,
    rhs => rhs,
    xor_8bit => n3_xor_8bit
  );
  u_3_c18933 : or_8bit port map (
    a => lhs,
    b => rhs,
    output => n4_output
  );
  u_4_c19101 : and_8bit port map (
    lhs => lhs,
    rhs => rhs,
    and_8bit => n5_and_8bit
  );
  u_5_c19348 : mux8_1_8bit port map (
    in0 => lhs,
    in1 => n1_sum_8bit,
    in2 => n2_sub_8bit,
    in3 => n3_xor_8bit,
    in4 => n10_shl8_n,
    in5 => n5_and_8bit,
    in6 => n4_output,
    in7 => rhs,
    sel => sel,
    output => n6_output
  );
  u_6_c19435 : shl8_n port map (
    lhs => lhs,
    rhs => rhs,
    shl8_n => n10_shl8_n
  );

  -- output drivers
  product <= n6_output;
  flag(2) <= n60_o;
  flag(1) <= n64_o;
  flag(0) <= n24_eq;
  comp_a_bus(0) <= STD_LOGIC'('0');
  comp_a_bus(1) <= STD_LOGIC'('0');
  comp_a_bus(2) <= STD_LOGIC'('0');
  comp_a_bus(3) <= STD_LOGIC'('0');
  comp_a_bus(4) <= STD_LOGIC'('0');
  comp_a_bus(5) <= STD_LOGIC'('0');
  comp_a_bus(6) <= STD_LOGIC'('0');
  comp_a_bus(7) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: and_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_8bit

entity and_8bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    and_8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end and_8bit;

architecture Behavioral of and_8bit is
  signal n1_y, n2_o, n3_y, n5_y, n6_o, n7_y, n9_y, n10_o, n11_y, n13_y, n14_o, n15_y, n17_y, n18_o, n19_y, n21_y, n22_o, n23_y, n25_y, n26_o, n27_y, n29_y, n30_o, n31_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= lhs(7);
  n2_o <= n1_y and n3_y;
  n3_y <= rhs(7);
  n5_y <= lhs(6);
  n6_o <= n5_y and n7_y;
  n7_y <= rhs(6);
  n9_y <= lhs(5);
  n10_o <= n9_y and n11_y;
  n11_y <= rhs(5);
  n13_y <= lhs(4);
  n14_o <= n13_y and n15_y;
  n15_y <= rhs(4);
  n17_y <= lhs(3);
  n18_o <= n17_y and n19_y;
  n19_y <= rhs(3);
  n21_y <= lhs(2);
  n22_o <= n21_y and n23_y;
  n23_y <= rhs(2);
  n25_y <= lhs(1);
  n26_o <= n25_y and n27_y;
  n27_y <= rhs(1);
  n29_y <= lhs(0);
  n30_o <= n29_y and n31_y;
  n31_y <= rhs(0);

  -- output drivers
  and_8bit(7) <= n2_o;
  and_8bit(6) <= n6_o;
  and_8bit(5) <= n10_o;
  and_8bit(4) <= n14_o;
  and_8bit(3) <= n18_o;
  and_8bit(2) <= n22_o;
  and_8bit(1) <= n26_o;
  and_8bit(0) <= n30_o;

end Behavioral;

-- ============================================================
-- Entity: mux8_1_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mux8_1_8bit

entity mux8_1_8bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    in1 : in  STD_LOGIC_VECTOR(7 downto 0);
    in2 : in  STD_LOGIC_VECTOR(7 downto 0);
    in3 : in  STD_LOGIC_VECTOR(7 downto 0);
    in4 : in  STD_LOGIC_VECTOR(7 downto 0);
    in5 : in  STD_LOGIC_VECTOR(7 downto 0);
    in6 : in  STD_LOGIC_VECTOR(7 downto 0);
    in7 : in  STD_LOGIC_VECTOR(7 downto 0);
    sel : in  STD_LOGIC_VECTOR(2 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end mux8_1_8bit;

architecture Behavioral of mux8_1_8bit is
  component and_8bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC;
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component or_8bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC_VECTOR(7 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_y, n22_y, n23_y, n24_y, n25_y, n26_y, n27_y, n28_y, n29_y, n30_y, n31_y, n32_y, n33_y, n34_y, n35_y, n36_y, n37_y, n38_y, n39_y, n40_y, n41_y, n42_y, n43_y, n44_y : STD_LOGIC;
  signal n68_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n69_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n70_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n71_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n72_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n73_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n74_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n75_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n76_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n77_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n78_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n79_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n80_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n81_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n82_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_o <= n9_o and n10_o and n11_o;
  n2_o <= n12_o and n13_o and n26_y;
  n3_o <= n14_o and n28_y and n15_o;
  n4_o <= n16_o and n31_y and n32_y;
  n5_o <= n33_y and n17_o and n18_o;
  n6_o <= n36_y and n19_o and n38_y;
  n7_o <= n39_y and n40_y and n20_o;
  n8_o <= n42_y and n43_y and n44_y;
  n9_o <= not n21_y;
  n10_o <= not n22_y;
  n11_o <= not n23_y;
  n12_o <= not n24_y;
  n13_o <= not n25_y;
  n14_o <= not n27_y;
  n15_o <= not n29_y;
  n16_o <= not n30_y;
  n17_o <= not n34_y;
  n18_o <= not n35_y;
  n19_o <= not n37_y;
  n20_o <= not n41_y;
  n21_y <= sel(2);
  n22_y <= sel(1);
  n23_y <= sel(0);
  n24_y <= sel(2);
  n25_y <= sel(1);
  n26_y <= sel(0);
  n27_y <= sel(2);
  n28_y <= sel(1);
  n29_y <= sel(0);
  n30_y <= sel(2);
  n31_y <= sel(1);
  n32_y <= sel(0);
  n33_y <= sel(2);
  n34_y <= sel(1);
  n35_y <= sel(0);
  n36_y <= sel(2);
  n37_y <= sel(1);
  n38_y <= sel(0);
  n39_y <= sel(2);
  n40_y <= sel(1);
  n41_y <= sel(0);
  n42_y <= sel(2);
  n43_y <= sel(1);
  n44_y <= sel(0);

  -- sub-component instantiations
  u_0_c19294 : and_8bit_1bit port map (
    a => in0,
    b => n1_o,
    output => n68_output
  );
  u_1_c19295 : and_8bit_1bit port map (
    a => in1,
    b => n2_o,
    output => n69_output
  );
  u_2_c19302 : and_8bit_1bit port map (
    a => in2,
    b => n3_o,
    output => n70_output
  );
  u_3_c19303 : and_8bit_1bit port map (
    a => in3,
    b => n4_o,
    output => n71_output
  );
  u_4_c19304 : and_8bit_1bit port map (
    a => in4,
    b => n5_o,
    output => n72_output
  );
  u_5_c19305 : and_8bit_1bit port map (
    a => in5,
    b => n6_o,
    output => n73_output
  );
  u_6_c19306 : and_8bit_1bit port map (
    a => in6,
    b => n7_o,
    output => n74_output
  );
  u_7_c19307 : and_8bit_1bit port map (
    a => in7,
    b => n8_o,
    output => n75_output
  );
  u_8_c19324 : or_8bit port map (
    a => n68_output,
    b => n69_output,
    output => n76_output
  );
  u_9_c19325 : or_8bit port map (
    a => n70_output,
    b => n71_output,
    output => n77_output
  );
  u_10_c19326 : or_8bit port map (
    a => n72_output,
    b => n73_output,
    output => n78_output
  );
  u_11_c19327 : or_8bit port map (
    a => n74_output,
    b => n75_output,
    output => n79_output
  );
  u_12_c19336 : or_8bit port map (
    a => n76_output,
    b => n77_output,
    output => n80_output
  );
  u_13_c19338 : or_8bit port map (
    a => n78_output,
    b => n79_output,
    output => n81_output
  );
  u_14_c19343 : or_8bit port map (
    a => n80_output,
    b => n81_output,
    output => n82_output
  );

  -- output drivers
  output <= n82_output;

end Behavioral;

-- ============================================================
-- Entity: shl8_n
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: shl8_n

entity shl8_n is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    shl8_n : out STD_LOGIC_VECTOR(7 downto 0)
  );
end shl8_n;

architecture Behavioral of shl8_n is
  component shl_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      shl_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component mux8_1_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      in1 : in  STD_LOGIC_VECTOR(7 downto 0);
      in2 : in  STD_LOGIC_VECTOR(7 downto 0);
      in3 : in  STD_LOGIC_VECTOR(7 downto 0);
      in4 : in  STD_LOGIC_VECTOR(7 downto 0);
      in5 : in  STD_LOGIC_VECTOR(7 downto 0);
      in6 : in  STD_LOGIC_VECTOR(7 downto 0);
      in7 : in  STD_LOGIC_VECTOR(7 downto 0);
      sel : in  STD_LOGIC_VECTOR(2 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component and_8bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC;
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n30_y, n31_y, n32_y, n36_gt, n36_lt : STD_LOGIC;
  signal n1_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n2_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n3_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n4_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n5_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n6_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n7_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n8_output : STD_LOGIC_VECTOR(7 downto 0);
  signal sch_sch19103_sel_bus : STD_LOGIC_VECTOR(2 downto 0);
  signal n9_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n10_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n11_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n12_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n13_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n14_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n15_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n16_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n17_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n18_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n19_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n20_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n21_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n22_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n23_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n24_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n25_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n26_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n27_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n28_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n29_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal compm_b_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n60_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n30_y <= rhs(2);
  n31_y <= rhs(1);
  n32_y <= rhs(0);
  n36_gt <= '1' when unsigned(rhs) > unsigned(compm_b_bus) else '0';
  n36_lt <= '1' when unsigned(rhs) < unsigned(compm_b_bus) else '0';

  -- sub-component instantiations
  u_0_c19961 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n1_shl_8bit
  );
  u_1_c20046 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n2_shl_8bit
  );
  u_2_c20047 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n3_shl_8bit
  );
  u_3_c20048 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n4_shl_8bit
  );
  u_4_c20049 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n5_shl_8bit
  );
  u_5_c20050 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n6_shl_8bit
  );
  u_6_c20051 : shl_8bit port map (
    in0 => lhs,
    shl_8bit => n7_shl_8bit
  );
  u_7_c20053 : mux8_1_8bit port map (
    in0 => lhs,
    in1 => n1_shl_8bit,
    in2 => n9_shl_8bit,
    in3 => n11_shl_8bit,
    in4 => n14_shl_8bit,
    in5 => n18_shl_8bit,
    in6 => n23_shl_8bit,
    in7 => n29_shl_8bit,
    sel => sch_sch19103_sel_bus,
    output => n8_output
  );
  u_8_c20071 : shl_8bit port map (
    in0 => n2_shl_8bit,
    shl_8bit => n9_shl_8bit
  );
  u_9_c20072 : shl_8bit port map (
    in0 => n3_shl_8bit,
    shl_8bit => n10_shl_8bit
  );
  u_10_c20073 : shl_8bit port map (
    in0 => n10_shl_8bit,
    shl_8bit => n11_shl_8bit
  );
  u_11_c20074 : shl_8bit port map (
    in0 => n4_shl_8bit,
    shl_8bit => n12_shl_8bit
  );
  u_12_c20075 : shl_8bit port map (
    in0 => n12_shl_8bit,
    shl_8bit => n13_shl_8bit
  );
  u_13_c20078 : shl_8bit port map (
    in0 => n13_shl_8bit,
    shl_8bit => n14_shl_8bit
  );
  u_14_c20079 : shl_8bit port map (
    in0 => n5_shl_8bit,
    shl_8bit => n15_shl_8bit
  );
  u_15_c20080 : shl_8bit port map (
    in0 => n15_shl_8bit,
    shl_8bit => n16_shl_8bit
  );
  u_16_c20081 : shl_8bit port map (
    in0 => n16_shl_8bit,
    shl_8bit => n17_shl_8bit
  );
  u_17_c20082 : shl_8bit port map (
    in0 => n17_shl_8bit,
    shl_8bit => n18_shl_8bit
  );
  u_18_c20083 : shl_8bit port map (
    in0 => n6_shl_8bit,
    shl_8bit => n19_shl_8bit
  );
  u_19_c20084 : shl_8bit port map (
    in0 => n19_shl_8bit,
    shl_8bit => n20_shl_8bit
  );
  u_20_c20085 : shl_8bit port map (
    in0 => n20_shl_8bit,
    shl_8bit => n21_shl_8bit
  );
  u_21_c20086 : shl_8bit port map (
    in0 => n21_shl_8bit,
    shl_8bit => n22_shl_8bit
  );
  u_22_c20087 : shl_8bit port map (
    in0 => n22_shl_8bit,
    shl_8bit => n23_shl_8bit
  );
  u_23_c20088 : shl_8bit port map (
    in0 => n7_shl_8bit,
    shl_8bit => n24_shl_8bit
  );
  u_24_c20089 : shl_8bit port map (
    in0 => n24_shl_8bit,
    shl_8bit => n25_shl_8bit
  );
  u_25_c20090 : shl_8bit port map (
    in0 => n25_shl_8bit,
    shl_8bit => n26_shl_8bit
  );
  u_26_c20091 : shl_8bit port map (
    in0 => n26_shl_8bit,
    shl_8bit => n27_shl_8bit
  );
  u_27_c20092 : shl_8bit port map (
    in0 => n27_shl_8bit,
    shl_8bit => n28_shl_8bit
  );
  u_28_c20093 : shl_8bit port map (
    in0 => n28_shl_8bit,
    shl_8bit => n29_shl_8bit
  );
  u_29_c20241 : and_8bit_1bit port map (
    a => n8_output,
    b => n36_lt,
    output => n60_output
  );

  -- output drivers
  shl8_n <= n60_output;
  sch_sch19103_sel_bus(2) <= n30_y;
  sch_sch19103_sel_bus(1) <= n31_y;
  sch_sch19103_sel_bus(0) <= n32_y;
  compm_b_bus(7) <= STD_LOGIC'('0');
  compm_b_bus(6) <= STD_LOGIC'('0');
  compm_b_bus(5) <= STD_LOGIC'('0');
  compm_b_bus(4) <= STD_LOGIC'('0');
  compm_b_bus(3) <= STD_LOGIC'('1');
  compm_b_bus(2) <= STD_LOGIC'('0');
  compm_b_bus(1) <= STD_LOGIC'('0');
  compm_b_bus(0) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: register_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: register_8bit

entity register_8bit is
  Port (
    set_in : in  STD_LOGIC_VECTOR(7 downto 0);
    set : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    stored : out STD_LOGIC_VECTOR(7 downto 0)
  );
end register_8bit;

architecture Behavioral of register_8bit is
  signal n24_o, n25_o, n26_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n70_y, n72_y, n74_y, n76_y, n78_y, n80_y, n82_y, n84_y : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n5_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
  signal n7_q : STD_LOGIC := '0';
  signal n7_qn : STD_LOGIC := '1';
  signal n8_q : STD_LOGIC := '0';
  signal n8_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n24_o <= set and n72_y;
  n25_o <= set and n26_o;
  n26_o <= not n72_y;
  n34_o <= set and n70_y;
  n35_o <= set and n36_o;
  n36_o <= not n70_y;
  n37_o <= set and n74_y;
  n38_o <= set and n39_o;
  n39_o <= not n74_y;
  n40_o <= set and n76_y;
  n41_o <= set and n42_o;
  n42_o <= not n76_y;
  n43_o <= set and n78_y;
  n44_o <= set and n45_o;
  n45_o <= not n78_y;
  n46_o <= set and n80_y;
  n47_o <= set and n48_o;
  n48_o <= not n80_y;
  n49_o <= set and n82_y;
  n50_o <= set and n51_o;
  n51_o <= not n82_y;
  n52_o <= set and n84_y;
  n53_o <= set and n54_o;
  n54_o <= not n84_y;
  n70_y <= set_in(7);
  n72_y <= set_in(6);
  n74_y <= set_in(5);
  n76_y <= set_in(4);
  n78_y <= set_in(3);
  n80_y <= set_in(2);
  n82_y <= set_in(1);
  n84_y <= set_in(0);

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if    (n34_o='0' and n35_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n34_o='1' and n35_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n34_o='1' and n35_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if    (n24_o='0' and n25_o='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (n24_o='1' and n25_o='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (n24_o='1' and n25_o='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      if    (n37_o='0' and n38_o='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n37_o='1' and n38_o='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n37_o='1' and n38_o='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif rising_edge(clk) then
      if    (n40_o='0' and n41_o='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (n40_o='1' and n41_o='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (n40_o='1' and n41_o='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n5_q <= '0';
      n5_qn <= '1';
    elsif rising_edge(clk) then
      if    (n43_o='0' and n44_o='1') then n5_q <= '0'; n5_qn <= '1';
      elsif (n43_o='1' and n44_o='0') then n5_q <= '1'; n5_qn <= '0';
      elsif (n43_o='1' and n44_o='1') then n5_q <= not n5_q; n5_qn <= n5_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n6_q <= '0';
      n6_qn <= '1';
    elsif rising_edge(clk) then
      if    (n46_o='0' and n47_o='1') then n6_q <= '0'; n6_qn <= '1';
      elsif (n46_o='1' and n47_o='0') then n6_q <= '1'; n6_qn <= '0';
      elsif (n46_o='1' and n47_o='1') then n6_q <= not n6_q; n6_qn <= n6_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n7_q <= '0';
      n7_qn <= '1';
    elsif rising_edge(clk) then
      if    (n49_o='0' and n50_o='1') then n7_q <= '0'; n7_qn <= '1';
      elsif (n49_o='1' and n50_o='0') then n7_q <= '1'; n7_qn <= '0';
      elsif (n49_o='1' and n50_o='1') then n7_q <= not n7_q; n7_qn <= n7_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n8_q <= '0';
      n8_qn <= '1';
    elsif rising_edge(clk) then
      if    (n52_o='0' and n53_o='1') then n8_q <= '0'; n8_qn <= '1';
      elsif (n52_o='1' and n53_o='0') then n8_q <= '1'; n8_qn <= '0';
      elsif (n52_o='1' and n53_o='1') then n8_q <= not n8_q; n8_qn <= n8_q;
      end if;
    end if;
  end process;

  -- output drivers
  stored(7) <= n1_q;
  stored(6) <= n2_q;
  stored(5) <= n3_q;
  stored(4) <= n4_q;
  stored(3) <= n5_q;
  stored(2) <= n6_q;
  stored(1) <= n7_q;
  stored(0) <= n8_q;

end Behavioral;

-- ============================================================
-- Entity: register_3bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: register_3bit

entity register_3bit is
  Port (
    set_in : in  STD_LOGIC_VECTOR(2 downto 0);
    set : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    stored : out STD_LOGIC_VECTOR(2 downto 0)
  );
end register_3bit;

architecture Behavioral of register_3bit is
  signal n9_o, n10_o, n11_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_y, n22_y, n24_y : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n9_o <= set and n22_y;
  n10_o <= set and n11_o;
  n11_o <= not n22_y;
  n14_o <= set and n20_y;
  n15_o <= set and n16_o;
  n16_o <= not n20_y;
  n17_o <= set and n24_y;
  n18_o <= set and n19_o;
  n19_o <= not n24_y;
  n20_y <= set_in(2);
  n22_y <= set_in(1);
  n24_y <= set_in(0);

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if    (n14_o='0' and n15_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n14_o='1' and n15_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n14_o='1' and n15_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if    (n9_o='0' and n10_o='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (n9_o='1' and n10_o='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (n9_o='1' and n10_o='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      if    (n17_o='0' and n18_o='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n17_o='1' and n18_o='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n17_o='1' and n18_o='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;

  -- output drivers
  stored(2) <= n1_q;
  stored(1) <= n2_q;
  stored(0) <= n3_q;

end Behavioral;
