-- ============================================================
-- Entity: and_4bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_4bit_1bit

entity and_4bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC;
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end and_4bit_1bit;

architecture Behavioral of and_4bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n8_y, n9_y, n10_y, n11_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n8_y and b;
  n2_o <= n9_y and b;
  n3_o <= n10_y and b;
  n4_o <= n11_y and b;
  n8_y <= a(3);
  n9_y <= a(2);
  n10_y <= a(1);
  n11_y <= a(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;