-- ============================================================
-- Entity: demux1_4_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: demux1_4_8bit

entity demux1_4_8bit is
  Port (
    input : in  STD_LOGIC_VECTOR(7 downto 0);
    selector : in  STD_LOGIC_VECTOR(1 downto 0);
    out0 : out STD_LOGIC_VECTOR(7 downto 0);
    out1 : out STD_LOGIC_VECTOR(7 downto 0);
    out2 : out STD_LOGIC_VECTOR(7 downto 0);
    out3 : out STD_LOGIC_VECTOR(7 downto 0)
  );
end demux1_4_8bit;

architecture Behavioral of demux1_4_8bit is
  component and_8bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC;
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n13_y, n14_y, n18_o, n19_o : STD_LOGIC;
  signal n9_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n10_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n11_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n12_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_o <= n5_o and n6_o;
  n2_o <= n7_o and n19_o;
  n3_o <= n18_o and n8_o;
  n4_o <= n18_o and n19_o;
  n5_o <= not n18_o;
  n6_o <= not n19_o;
  n7_o <= not n18_o;
  n8_o <= not n19_o;
  n13_y <= selector(0);
  n14_y <= selector(1);
  n18_o <= n14_y;
  n19_o <= n13_y;

  -- sub-component instantiations
  u_0_c15453 : and_8bit_1bit port map (
    a => input,
    b => n1_o,
    output => n9_output
  );
  u_1_c15454 : and_8bit_1bit port map (
    a => input,
    b => n2_o,
    output => n10_output
  );
  u_2_c15455 : and_8bit_1bit port map (
    a => input,
    b => n3_o,
    output => n11_output
  );
  u_3_c15456 : and_8bit_1bit port map (
    a => input,
    b => n4_o,
    output => n12_output
  );

  -- output drivers
  out0 <= n9_output;
  out1 <= n10_output;
  out2 <= n11_output;
  out3 <= n12_output;

end Behavioral;