-- ============================================================
-- Entity: hex_7seg_decoder
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg_decoder

entity hex_7seg_decoder is
  Port (
    d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
    clk_trigger : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    data_out : out STD_LOGIC_VECTOR(3 downto 0);
    d3 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d0 : out STD_LOGIC
  );
end hex_7seg_decoder;

architecture Behavioral of hex_7seg_decoder is
  component and_4bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC;
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component or_4bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC_VECTOR(3 downto 0);
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  signal n4_o, n6_o, n7_o, n8_o, n9_o, n23_o, n24_o, n26_o, n27_o : STD_LOGIC;
  signal n10_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n11_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n12_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n14_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n15_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n16_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= clk_trigger and n2_q;
  n6_o <= n23_o and n24_o;
  n7_o <= n26_o and n2_q;
  n8_o <= n1_q and n27_o;
  n9_o <= n1_q and n2_q;
  n23_o <= not n1_q;
  n24_o <= not n2_q;
  n26_o <= not n1_q;
  n27_o <= not n2_q;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if    (n4_o='0' and n4_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n4_o='1' and n4_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n4_o='1' and n4_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if    (clk_trigger='0' and clk_trigger='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (clk_trigger='1' and clk_trigger='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (clk_trigger='1' and clk_trigger='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c14777 : and_4bit_1bit port map (
    a => d3_data,
    b => n9_o,
    out_data => n10_out_data
  );
  u_1_c14779 : and_4bit_1bit port map (
    a => d2_data,
    b => n8_o,
    out_data => n11_out_data
  );
  u_2_c14781 : and_4bit_1bit port map (
    a => d1_data,
    b => n7_o,
    out_data => n12_out_data
  );
  u_3_c14783 : and_4bit_1bit port map (
    a => d0_data,
    b => n6_o,
    out_data => n13_out_data
  );
  u_4_c14875 : or_4bit port map (
    a => n11_out_data,
    b => n15_out_data,
    out_data => n14_out_data
  );
  u_5_c14876 : or_4bit port map (
    a => n12_out_data,
    b => n13_out_data,
    out_data => n15_out_data
  );
  u_6_c14877 : or_4bit port map (
    a => n10_out_data,
    b => n14_out_data,
    out_data => n16_out_data
  );

  -- output drivers
  data_out <= n16_out_data;
  d3 <= n6_o;
  d2 <= n7_o;
  d1 <= n8_o;
  d0 <= n9_o;

end Behavioral;