-- ============================================================
-- Entity: lab9_mode_selector
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab9_mode_selector

entity lab9_mode_selector is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mode : out STD_LOGIC_VECTOR(1 downto 0)
  );
end lab9_mode_selector;

architecture Behavioral of lab9_mode_selector is
  signal n4_o, n10_o, n11_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n2_q;
  n10_o <= n1_q;
  n11_o <= n2_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n4_o='0' and n4_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n4_o='1' and n4_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n4_o='1' and n4_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (trigger='0' and trigger='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (trigger='1' and trigger='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (trigger='1' and trigger='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;

  -- output drivers
  mode(0) <= n11_o;
  mode(1) <= n10_o;

end Behavioral;