library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab9

entity lab9 is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    push_button : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab9;

architecture Behavioral of lab9 is
  component hex_7seg_decoder
    Port (
      d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
      clk_trigger : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      data_out : out STD_LOGIC_VECTOR(3 downto 0);
      d3 : out STD_LOGIC;
      d2 : out STD_LOGIC;
      d1 : out STD_LOGIC;
      d0 : out STD_LOGIC
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      mod50k_out : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component debounce_button
    Port (
      button_signal : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      debounce_signal : out STD_LOGIC
    );
  end component;
  component lab9_mode_selector
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mode : out STD_LOGIC_VECTOR(1 downto 0)
    );
  end component;
  component demux1_4_8bit
    Port (
      input : in  STD_LOGIC_VECTOR(7 downto 0);
      selector : in  STD_LOGIC_VECTOR(1 downto 0);
      out0 : out STD_LOGIC_VECTOR(7 downto 0);
      out1 : out STD_LOGIC_VECTOR(7 downto 0);
      out2 : out STD_LOGIC_VECTOR(7 downto 0);
      out3 : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component mux4_1_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      in1 : in  STD_LOGIC_VECTOR(7 downto 0);
      in2 : in  STD_LOGIC_VECTOR(7 downto 0);
      in3 : in  STD_LOGIC_VECTOR(7 downto 0);
      selector : in  STD_LOGIC_VECTOR(1 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component add8_bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sum_8bit : out STD_LOGIC_VECTOR(7 downto 0);
      carry_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component sub8_bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sub_8bit : out STD_LOGIC_VECTOR(7 downto 0);
      carry_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component xor_8bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      xor_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component shl_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      shl_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_d3, n1_d2, n1_d1, n1_d0, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n31_mod50k_out, n32_a, n32_b, n32_c, n32_d, n32_e, n32_f, n32_g, n33_y, n34_y, n35_y, n36_y, n41_debounce_signal, n52_y, n53_y, n54_y, n55_y, n56_y, n57_y, n58_y, n59_y : STD_LOGIC;
  signal n1_data_out : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d1_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d0_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d3_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d2_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal n44_mode : STD_LOGIC_VECTOR(1 downto 0);
  signal n46_out0 : STD_LOGIC_VECTOR(7 downto 0);
  signal n46_out1 : STD_LOGIC_VECTOR(7 downto 0);
  signal n46_out2 : STD_LOGIC_VECTOR(7 downto 0);
  signal n46_out3 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out0 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out1 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out2 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out3 : STD_LOGIC_VECTOR(7 downto 0);
  signal n49_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n50_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n82_sum_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n82_carry_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n83_sub_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n83_carry_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n84_xor_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n85_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n2_y <= n49_output(7);
  n3_y <= n49_output(6);
  n4_y <= n49_output(5);
  n5_y <= n49_output(4);
  n6_y <= n49_output(3);
  n7_y <= n49_output(2);
  n8_y <= n49_output(1);
  n9_y <= n49_output(0);
  n33_y <= n1_data_out(3);
  n34_y <= n1_data_out(2);
  n35_y <= n1_data_out(1);
  n36_y <= n1_data_out(0);
  n52_y <= n50_output(7);
  n53_y <= n50_output(6);
  n54_y <= n50_output(5);
  n55_y <= n50_output(4);
  n56_y <= n50_output(3);
  n57_y <= n50_output(2);
  n58_y <= n50_output(1);
  n59_y <= n50_output(0);

  -- sub-component instantiations
  u_0_c14991 : hex_7seg_decoder port map (
    d3_data => sch_sch14611_d3_data_bus,
    d2_data => sch_sch14611_d2_data_bus,
    d1_data => sch_sch14611_d1_data_bus,
    d0_data => sch_sch14611_d0_data_bus,
    clk_trigger => n31_mod50k_out,
    clk_50mhz => clk,
    data_out => n1_data_out,
    d3 => n1_d3,
    d2 => n1_d2,
    d1 => n1_d1,
    d0 => n1_d0
  );
  u_1_c15079 : mod50k_sync port map (
    clk => clk,
    mod50k_out => n31_mod50k_out
  );
  u_2_c15092 : hex_7seg port map (
    in1_msb => n33_y,
    in2 => n34_y,
    in3 => n35_y,
    in4_lsb => n36_y,
    a => n32_a,
    b => n32_b,
    c => n32_c,
    d => n32_d,
    e => n32_e,
    f => n32_f,
    g => n32_g
  );
  u_3_c15210 : debounce_button port map (
    button_signal => push_button,
    clk_50mhz => clk,
    clk_1khz => n31_mod50k_out,
    debounce_signal => n41_debounce_signal
  );
  u_4_c15306 : lab9_mode_selector port map (
    trigger => n41_debounce_signal,
    clk => clk,
    mode => n44_mode
  );
  u_5_c15523 : demux1_4_8bit port map (
    input => lhs,
    selector => n44_mode,
    out0 => n46_out0,
    out1 => n46_out1,
    out2 => n46_out2,
    out3 => n46_out3
  );
  u_6_c15528 : demux1_4_8bit port map (
    input => rhs,
    selector => n44_mode,
    out0 => n47_out0,
    out1 => n47_out1,
    out2 => n47_out2,
    out3 => n47_out3
  );
  u_7_c15655 : mux4_1_8bit port map (
    in0 => n82_sum_8bit,
    in1 => n83_sub_8bit,
    in2 => n84_xor_8bit,
    in3 => n85_shl_8bit,
    selector => n44_mode,
    output => n49_output
  );
  u_8_c15668 : mux4_1_8bit port map (
    in0 => n82_carry_out,
    in1 => n83_carry_out,
    in2 => (others => '0'),
    in3 => (others => '0'),
    selector => n44_mode,
    output => n50_output
  );
  u_9_c16319 : add8_bit port map (
    lhs => n46_out0,
    rhs => n47_out0,
    sum_8bit => n82_sum_8bit,
    carry_out => n82_carry_out
  );
  u_10_c16325 : sub8_bit port map (
    lhs => n46_out1,
    rhs => n47_out1,
    sub_8bit => n83_sub_8bit,
    carry_out => n83_carry_out
  );
  u_11_c16585 : xor_8bit port map (
    lhs => n46_out2,
    rhs => n47_out2,
    xor_8bit => n84_xor_8bit
  );
  u_12_c16586 : shl_8bit port map (
    in0 => n46_out3,
    shl_8bit => n85_shl_8bit
  );

  -- output drivers
  a <= n32_a;
  b <= n32_b;
  c <= n32_c;
  d <= n32_d;
  e <= n32_e;
  f <= n32_f;
  g <= n32_g;
  d0 <= n1_d0;
  d1 <= n1_d1;
  d2 <= n1_d2;
  d3 <= n1_d3;
  sch_sch14611_d1_data_bus(3) <= n2_y;
  sch_sch14611_d1_data_bus(2) <= n3_y;
  sch_sch14611_d1_data_bus(1) <= n4_y;
  sch_sch14611_d1_data_bus(0) <= n5_y;
  sch_sch14611_d0_data_bus(3) <= n6_y;
  sch_sch14611_d0_data_bus(2) <= n7_y;
  sch_sch14611_d0_data_bus(1) <= n8_y;
  sch_sch14611_d0_data_bus(0) <= n9_y;
  sch_sch14611_d3_data_bus(3) <= n52_y;
  sch_sch14611_d3_data_bus(2) <= n53_y;
  sch_sch14611_d3_data_bus(1) <= n54_y;
  sch_sch14611_d3_data_bus(0) <= n55_y;
  sch_sch14611_d2_data_bus(3) <= n56_y;
  sch_sch14611_d2_data_bus(2) <= n57_y;
  sch_sch14611_d2_data_bus(1) <= n58_y;
  sch_sch14611_d2_data_bus(0) <= n59_y;

end Behavioral;
