-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
  Port (
    in1_msb : in  STD_LOGIC;
    in2 : in  STD_LOGIC;
    in3 : in  STD_LOGIC;
    in4_lsb : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC
  );
end hex_7seg;

architecture Behavioral of hex_7seg is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in1_msb and in2 and n40_o and in4_lsb;
  n2_o <= in1_msb and n39_o and in3 and in4_lsb;
  n3_o <= n36_o and in2 and n37_o and n38_o;
  n4_o <= n33_o and n34_o and n35_o and in4_lsb;
  n5_o <= n4_o or n3_o or n2_o or n1_o;
  n6_o <= in2 and in3 and n44_o;
  n7_o <= in1_msb and in3 and in4_lsb;
  n8_o <= in1_msb and in2 and n43_o;
  n9_o <= n41_o and in2 and n42_o and in4_lsb;
  n10_o <= n9_o or n8_o or n7_o or n6_o;
  n11_o <= in1_msb and in2 and n48_o;
  n12_o <= in1_msb and in2 and in3;
  n13_o <= n45_o and n46_o and in3 and n47_o;
  n14_o <= n13_o or n12_o or n11_o;
  n15_o <= in2 and in3 and in4_lsb;
  n16_o <= in1_msb and n55_o and in3 and n56_o;
  n17_o <= n52_o and in2 and n53_o and n54_o;
  n18_o <= n49_o and n50_o and n51_o and in4_lsb;
  n19_o <= n18_o or n17_o or n16_o or n15_o;
  n20_o <= n60_o and n61_o and in4_lsb;
  n21_o <= n59_o and in4_lsb;
  n22_o <= n57_o and in2 and n58_o;
  n23_o <= n22_o or n21_o or n20_o;
  n24_o <= in1_msb and in2 and n67_o and in4_lsb;
  n25_o <= n66_o and in3 and in4_lsb;
  n26_o <= n64_o and n65_o and in4_lsb;
  n27_o <= n62_o and n63_o and in3;
  n28_o <= n27_o or n26_o or n25_o or n24_o;
  n29_o <= in1_msb and in2 and n72_o and n73_o;
  n30_o <= n71_o and in2 and in3 and in4_lsb;
  n31_o <= n68_o and n69_o and n70_o;
  n32_o <= n31_o or n30_o or n29_o;
  n33_o <= not in1_msb;
  n34_o <= not in2;
  n35_o <= not in3;
  n36_o <= not in1_msb;
  n37_o <= not in3;
  n38_o <= not in4_lsb;
  n39_o <= not in2;
  n40_o <= not in3;
  n41_o <= not in1_msb;
  n42_o <= not in3;
  n43_o <= not in4_lsb;
  n44_o <= not in4_lsb;
  n45_o <= not in1_msb;
  n46_o <= not in2;
  n47_o <= not in4_lsb;
  n48_o <= not in4_lsb;
  n49_o <= not in1_msb;
  n50_o <= not in2;
  n51_o <= not in3;
  n52_o <= not in1_msb;
  n53_o <= not in3;
  n54_o <= not in4_lsb;
  n55_o <= not in2;
  n56_o <= not in4_lsb;
  n57_o <= not in1_msb;
  n58_o <= not in3;
  n59_o <= not in1_msb;
  n60_o <= not in2;
  n61_o <= not in3;
  n62_o <= not in1_msb;
  n63_o <= not in2;
  n64_o <= not in1_msb;
  n65_o <= not in2;
  n66_o <= not in1_msb;
  n67_o <= not in3;
  n68_o <= not in1_msb;
  n69_o <= not in2;
  n70_o <= not in3;
  n71_o <= not in1_msb;
  n72_o <= not in3;
  n73_o <= not in4_lsb;

  -- output drivers
  a <= n5_o;
  b <= n10_o;
  c <= n14_o;
  d <= n19_o;
  e <= n23_o;
  f <= n28_o;
  g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: fa1
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: fa1

entity fa1 is
  Port (
    lhs : in  STD_LOGIC;
    rhs : in  STD_LOGIC;
    carry_in : in  STD_LOGIC;
    carry_out : out STD_LOGIC;
    sum : out STD_LOGIC
  );
end fa1;

architecture Behavioral of fa1 is
  signal n1_o, n2_o, n3_o, n4_o, n5_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= lhs xor rhs;
  n2_o <= n1_o xor carry_in;
  n3_o <= lhs and rhs;
  n4_o <= n1_o and carry_in;
  n5_o <= n3_o or n4_o;

  -- output drivers
  carry_out <= n5_o;
  sum <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: fas8
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: fas8

entity fas8 is
  Port (
    lhs_0_lsb : in  STD_LOGIC;
    rhs_0_lsb : in  STD_LOGIC;
    lhs_1 : in  STD_LOGIC;
    rhs_1 : in  STD_LOGIC;
    lhs_2 : in  STD_LOGIC;
    rhs_2 : in  STD_LOGIC;
    lhs_3 : in  STD_LOGIC;
    rhs_3 : in  STD_LOGIC;
    lhs_4 : in  STD_LOGIC;
    rhs_4 : in  STD_LOGIC;
    lhs_5 : in  STD_LOGIC;
    rhs_5 : in  STD_LOGIC;
    lhs_6 : in  STD_LOGIC;
    rhs_6 : in  STD_LOGIC;
    lhs_7_msb : in  STD_LOGIC;
    rhs_7_msb : in  STD_LOGIC;
    sub : in  STD_LOGIC;
    sum_0 : out STD_LOGIC;
    sum_1 : out STD_LOGIC;
    sum_2 : out STD_LOGIC;
    sum_3 : out STD_LOGIC;
    sum_4 : out STD_LOGIC;
    sum_5 : out STD_LOGIC;
    sum_6 : out STD_LOGIC;
    sum_7 : out STD_LOGIC;
    carry_out : out STD_LOGIC
  );
end fas8;

architecture Behavioral of fas8 is
  component fa1
    Port (
      lhs : in  STD_LOGIC;
      rhs : in  STD_LOGIC;
      carry_in : in  STD_LOGIC;
      carry_out : out STD_LOGIC;
      sum : out STD_LOGIC
    );
  end component;
  signal n1_carry_out, n1_sum, n2_o, n3_carry_out, n3_sum, n4_o, n5_carry_out, n5_sum, n6_o, n7_carry_out, n7_sum, n8_o, n9_carry_out, n9_sum, n10_o, n11_carry_out, n11_sum, n12_o, n13_carry_out, n13_sum, n14_o, n15_carry_out, n15_sum, n16_o : STD_LOGIC;
begin

  -- combinational logic
  n2_o <= sub xor rhs_0_lsb;
  n4_o <= sub xor rhs_1;
  n6_o <= sub xor rhs_2;
  n8_o <= sub xor rhs_3;
  n10_o <= sub xor rhs_4;
  n12_o <= sub xor rhs_5;
  n14_o <= sub xor rhs_6;
  n16_o <= sub xor rhs_7_msb;

  -- sub-component instantiations
  u_0_c5272 : fa1 port map (
    lhs => lhs_0_lsb,
    rhs => n2_o,
    carry_in => sub,
    carry_out => n1_carry_out,
    sum => n1_sum
  );
  u_1_c5316 : fa1 port map (
    lhs => lhs_1,
    rhs => n4_o,
    carry_in => n1_carry_out,
    carry_out => n3_carry_out,
    sum => n3_sum
  );
  u_2_c5325 : fa1 port map (
    lhs => lhs_2,
    rhs => n6_o,
    carry_in => n3_carry_out,
    carry_out => n5_carry_out,
    sum => n5_sum
  );
  u_3_c5334 : fa1 port map (
    lhs => lhs_3,
    rhs => n8_o,
    carry_in => n5_carry_out,
    carry_out => n7_carry_out,
    sum => n7_sum
  );
  u_4_c5343 : fa1 port map (
    lhs => lhs_4,
    rhs => n10_o,
    carry_in => n7_carry_out,
    carry_out => n9_carry_out,
    sum => n9_sum
  );
  u_5_c5352 : fa1 port map (
    lhs => lhs_5,
    rhs => n12_o,
    carry_in => n9_carry_out,
    carry_out => n11_carry_out,
    sum => n11_sum
  );
  u_6_c5361 : fa1 port map (
    lhs => lhs_6,
    rhs => n14_o,
    carry_in => n11_carry_out,
    carry_out => n13_carry_out,
    sum => n13_sum
  );
  u_7_c5370 : fa1 port map (
    lhs => lhs_7_msb,
    rhs => n16_o,
    carry_in => n13_carry_out,
    carry_out => n15_carry_out,
    sum => n15_sum
  );

  -- output drivers
  sum_0 <= n1_sum;
  sum_1 <= n3_sum;
  sum_2 <= n5_sum;
  sum_3 <= n7_sum;
  sum_4 <= n9_sum;
  sum_5 <= n11_sum;
  sum_6 <= n13_sum;
  sum_7 <= n15_sum;
  carry_out <= n15_carry_out;

end Behavioral;

-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n4_o, n5_o, n7_o, n9_o, n10_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n3_qn;
  n5_o <= trigger and n1_q;
  n7_o <= n2_q and n1_q;
  n9_o <= n3_q or n7_o;
  n10_o <= trigger and n9_o;
  n12_o <= trigger and n3_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (n4_o='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      if (n10_o='1') then n3_q <= not n3_q; n3_qn <= not n3_qn; end if;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod2_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod5_sync port map (
    trigger => n2_mod2_out,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c10682 : mod2_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod2_out => n2_mod2_out
  );

  -- output drivers
  mod10_out <= n1_mod5_out;

end Behavioral;

-- ============================================================
-- Entity: debounce_button
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_button

entity debounce_button is
  Port (
    button_signal : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    debounce_signal : out STD_LOGIC
  );
end debounce_button;

architecture Behavioral of debounce_button is
  component mod50_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod50_out : out STD_LOGIC
    );
  end component;
  signal n9_o, n12_mod50_out : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n8_q : STD_LOGIC := '0';
  signal n8_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n9_o <= n3_q and n8_qn;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n1_q  <= button_signal;
      n1_qn <= not (button_signal);
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n2_q  <= n1_q;
      n2_qn <= not (n1_q);
    end if;
  end process;
  process(clk_50mhz, n2_qn)
  begin
    if n2_qn = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk_50mhz) then
      if    (n12_mod50_out='0' and STD_LOGIC'('0')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n12_mod50_out='1' and STD_LOGIC'('0')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n12_mod50_out='1' and STD_LOGIC'('0')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n8_q  <= n3_q;
      n8_qn <= not (n3_q);
    end if;
  end process;

  -- sub-component instantiations
  u_0_c16763 : mod50_sync port map (
    trigger => clk_1khz,
    clk => clk_50mhz,
    reset => n2_qn,
    mod50_out => n12_mod50_out
  );

  -- output drivers
  debounce_signal <= n9_o;

end Behavioral;

-- ============================================================
-- Entity: mod50k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50k_sync

entity mod50k_sync is
  Port (
    clk : in  STD_LOGIC;
    mod50k_out : out STD_LOGIC
  );
end mod50k_sync;

architecture Behavioral of mod50k_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c9232 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n1_mod5_out
  );
  u_1_c9233 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n2_mod10_out
  );
  u_2_c9234 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n3_mod10_out
  );
  u_3_c9235 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n4_mod10_out
  );
  u_4_c9236 : mod10_sync port map (
    trigger => n4_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n5_mod10_out
  );

  -- output drivers
  mod50k_out <= n5_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= trigger and n1_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: and_8bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_8bit_1bit

entity and_8bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC;
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end and_8bit_1bit;

architecture Behavioral of and_8bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n16_y and b;
  n2_o <= n17_y and b;
  n3_o <= n18_y and b;
  n4_o <= n19_y and b;
  n5_o <= n20_y and b;
  n6_o <= n21_y and b;
  n7_o <= n22_y and b;
  n8_o <= n23_y and b;
  n16_y <= a(7);
  n17_y <= a(6);
  n18_y <= a(5);
  n19_y <= a(4);
  n20_y <= a(3);
  n21_y <= a(2);
  n22_y <= a(1);
  n23_y <= a(0);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: or_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_8bit

entity or_8bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC_VECTOR(7 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end or_8bit;

architecture Behavioral of or_8bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y, n24_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n24_y or n23_y;
  n2_o <= n22_y or n21_y;
  n3_o <= n20_y or n19_y;
  n4_o <= n18_y or n17_y;
  n5_o <= n16_y or n15_y;
  n6_o <= n14_y or n13_y;
  n7_o <= n12_y or n11_y;
  n8_o <= n10_y or n9_y;
  n9_y <= b(0);
  n10_y <= a(0);
  n11_y <= b(1);
  n12_y <= a(1);
  n13_y <= b(2);
  n14_y <= a(2);
  n15_y <= b(3);
  n16_y <= a(3);
  n17_y <= b(4);
  n18_y <= a(4);
  n19_y <= b(5);
  n20_y <= a(5);
  n21_y <= b(6);
  n22_y <= a(6);
  n23_y <= b(7);
  n24_y <= a(7);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: hex_7seg_decoder
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg_decoder

entity hex_7seg_decoder is
  Port (
    d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
    clk_trigger : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    data_out : out STD_LOGIC_VECTOR(3 downto 0);
    d3 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d0 : out STD_LOGIC
  );
end hex_7seg_decoder;

architecture Behavioral of hex_7seg_decoder is
  component and_4bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC;
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component or_4bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC_VECTOR(3 downto 0);
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  signal n4_o, n6_o, n7_o, n8_o, n9_o, n23_o, n24_o, n26_o, n27_o : STD_LOGIC;
  signal n10_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n11_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n12_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n14_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n15_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n16_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= clk_trigger and n2_q;
  n6_o <= n23_o and n24_o;
  n7_o <= n26_o and n2_q;
  n8_o <= n1_q and n27_o;
  n9_o <= n1_q and n2_q;
  n23_o <= not n1_q;
  n24_o <= not n2_q;
  n26_o <= not n1_q;
  n27_o <= not n2_q;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if    (n4_o='0' and n4_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n4_o='1' and n4_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n4_o='1' and n4_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if    (clk_trigger='0' and clk_trigger='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (clk_trigger='1' and clk_trigger='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (clk_trigger='1' and clk_trigger='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c14777 : and_4bit_1bit port map (
    a => d3_data,
    b => n9_o,
    out_data => n10_out_data
  );
  u_1_c14779 : and_4bit_1bit port map (
    a => d2_data,
    b => n8_o,
    out_data => n11_out_data
  );
  u_2_c14781 : and_4bit_1bit port map (
    a => d1_data,
    b => n7_o,
    out_data => n12_out_data
  );
  u_3_c14783 : and_4bit_1bit port map (
    a => d0_data,
    b => n6_o,
    out_data => n13_out_data
  );
  u_4_c14875 : or_4bit port map (
    a => n11_out_data,
    b => n15_out_data,
    out_data => n14_out_data
  );
  u_5_c14876 : or_4bit port map (
    a => n12_out_data,
    b => n13_out_data,
    out_data => n15_out_data
  );
  u_6_c14877 : or_4bit port map (
    a => n10_out_data,
    b => n14_out_data,
    out_data => n16_out_data
  );

  -- output drivers
  data_out <= n16_out_data;
  d3 <= n6_o;
  d2 <= n7_o;
  d1 <= n8_o;
  d0 <= n9_o;

end Behavioral;

-- ============================================================
-- Entity: and_4bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_4bit_1bit

entity and_4bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC;
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end and_4bit_1bit;

architecture Behavioral of and_4bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n8_y, n9_y, n10_y, n11_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n8_y and b;
  n2_o <= n9_y and b;
  n3_o <= n10_y and b;
  n4_o <= n11_y and b;
  n8_y <= a(3);
  n9_y <= a(2);
  n10_y <= a(1);
  n11_y <= a(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: or_4bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_4bit

entity or_4bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC_VECTOR(3 downto 0);
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end or_4bit;

architecture Behavioral of or_4bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n5_y or n6_y;
  n2_o <= n7_y or n8_y;
  n3_o <= n9_y or n10_y;
  n4_o <= n11_y or n12_y;
  n5_y <= a(3);
  n6_y <= b(3);
  n7_y <= a(2);
  n8_y <= b(2);
  n9_y <= a(1);
  n10_y <= b(1);
  n11_y <= a(0);
  n12_y <= b(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: lab9
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab9

entity lab9 is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    push_button : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab9;

architecture Behavioral of lab9 is
  component hex_7seg_decoder
    Port (
      d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
      clk_trigger : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      data_out : out STD_LOGIC_VECTOR(3 downto 0);
      d3 : out STD_LOGIC;
      d2 : out STD_LOGIC;
      d1 : out STD_LOGIC;
      d0 : out STD_LOGIC
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      mod50k_out : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component debounce_button
    Port (
      button_signal : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      debounce_signal : out STD_LOGIC
    );
  end component;
  component lab9_mode_selector
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mode : out STD_LOGIC_VECTOR(1 downto 0)
    );
  end component;
  component demux1_4_8bit
    Port (
      input : in  STD_LOGIC_VECTOR(7 downto 0);
      selector : in  STD_LOGIC_VECTOR(1 downto 0);
      out0 : out STD_LOGIC_VECTOR(7 downto 0);
      out1 : out STD_LOGIC_VECTOR(7 downto 0);
      out2 : out STD_LOGIC_VECTOR(7 downto 0);
      out3 : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component mux4_1_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      in1 : in  STD_LOGIC_VECTOR(7 downto 0);
      in2 : in  STD_LOGIC_VECTOR(7 downto 0);
      in3 : in  STD_LOGIC_VECTOR(7 downto 0);
      selector : in  STD_LOGIC_VECTOR(1 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component add8_bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sum_8bit : out STD_LOGIC_VECTOR(7 downto 0);
      carry_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component sub8_bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      sub_8bit : out STD_LOGIC_VECTOR(7 downto 0);
      carry_out : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component xor_8bit
    Port (
      lhs : in  STD_LOGIC_VECTOR(7 downto 0);
      rhs : in  STD_LOGIC_VECTOR(7 downto 0);
      xor_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component shl_8bit
    Port (
      in0 : in  STD_LOGIC_VECTOR(7 downto 0);
      shl_8bit : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_d3, n1_d2, n1_d1, n1_d0, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n31_mod50k_out, n32_a, n32_b, n32_c, n32_d, n32_e, n32_f, n32_g, n33_y, n34_y, n35_y, n36_y, n41_debounce_signal, n52_y, n53_y, n54_y, n55_y, n56_y, n57_y, n58_y, n59_y : STD_LOGIC;
  signal n1_data_out : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d1_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d0_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d3_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal sch_sch14611_d2_data_bus : STD_LOGIC_VECTOR(3 downto 0);
  signal n44_mode : STD_LOGIC_VECTOR(1 downto 0);
  signal n46_out0 : STD_LOGIC_VECTOR(7 downto 0);
  signal n46_out1 : STD_LOGIC_VECTOR(7 downto 0);
  signal n46_out2 : STD_LOGIC_VECTOR(7 downto 0);
  signal n46_out3 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out0 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out1 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out2 : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_out3 : STD_LOGIC_VECTOR(7 downto 0);
  signal n49_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n50_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n82_sum_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n82_carry_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n83_sub_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n83_carry_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n84_xor_8bit : STD_LOGIC_VECTOR(7 downto 0);
  signal n85_shl_8bit : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n2_y <= n49_output(7);
  n3_y <= n49_output(6);
  n4_y <= n49_output(5);
  n5_y <= n49_output(4);
  n6_y <= n49_output(3);
  n7_y <= n49_output(2);
  n8_y <= n49_output(1);
  n9_y <= n49_output(0);
  n33_y <= n1_data_out(3);
  n34_y <= n1_data_out(2);
  n35_y <= n1_data_out(1);
  n36_y <= n1_data_out(0);
  n52_y <= n50_output(7);
  n53_y <= n50_output(6);
  n54_y <= n50_output(5);
  n55_y <= n50_output(4);
  n56_y <= n50_output(3);
  n57_y <= n50_output(2);
  n58_y <= n50_output(1);
  n59_y <= n50_output(0);

  -- sub-component instantiations
  u_0_c14991 : hex_7seg_decoder port map (
    d3_data => sch_sch14611_d3_data_bus,
    d2_data => sch_sch14611_d2_data_bus,
    d1_data => sch_sch14611_d1_data_bus,
    d0_data => sch_sch14611_d0_data_bus,
    clk_trigger => n31_mod50k_out,
    clk_50mhz => clk,
    data_out => n1_data_out,
    d3 => n1_d3,
    d2 => n1_d2,
    d1 => n1_d1,
    d0 => n1_d0
  );
  u_1_c15079 : mod50k_sync port map (
    clk => clk,
    mod50k_out => n31_mod50k_out
  );
  u_2_c15092 : hex_7seg port map (
    in1_msb => n33_y,
    in2 => n34_y,
    in3 => n35_y,
    in4_lsb => n36_y,
    a => n32_a,
    b => n32_b,
    c => n32_c,
    d => n32_d,
    e => n32_e,
    f => n32_f,
    g => n32_g
  );
  u_3_c15210 : debounce_button port map (
    button_signal => push_button,
    clk_50mhz => clk,
    clk_1khz => n31_mod50k_out,
    debounce_signal => n41_debounce_signal
  );
  u_4_c15306 : lab9_mode_selector port map (
    trigger => n41_debounce_signal,
    clk => clk,
    mode => n44_mode
  );
  u_5_c15523 : demux1_4_8bit port map (
    input => lhs,
    selector => n44_mode,
    out0 => n46_out0,
    out1 => n46_out1,
    out2 => n46_out2,
    out3 => n46_out3
  );
  u_6_c15528 : demux1_4_8bit port map (
    input => rhs,
    selector => n44_mode,
    out0 => n47_out0,
    out1 => n47_out1,
    out2 => n47_out2,
    out3 => n47_out3
  );
  u_7_c15655 : mux4_1_8bit port map (
    in0 => n82_sum_8bit,
    in1 => n83_sub_8bit,
    in2 => n84_xor_8bit,
    in3 => n85_shl_8bit,
    selector => n44_mode,
    output => n49_output
  );
  u_8_c15668 : mux4_1_8bit port map (
    in0 => n82_carry_out,
    in1 => n83_carry_out,
    in2 => (others => '0'),
    in3 => (others => '0'),
    selector => n44_mode,
    output => n50_output
  );
  u_9_c16319 : add8_bit port map (
    lhs => n46_out0,
    rhs => n47_out0,
    sum_8bit => n82_sum_8bit,
    carry_out => n82_carry_out
  );
  u_10_c16325 : sub8_bit port map (
    lhs => n46_out1,
    rhs => n47_out1,
    sub_8bit => n83_sub_8bit,
    carry_out => n83_carry_out
  );
  u_11_c16585 : xor_8bit port map (
    lhs => n46_out2,
    rhs => n47_out2,
    xor_8bit => n84_xor_8bit
  );
  u_12_c16586 : shl_8bit port map (
    in0 => n46_out3,
    shl_8bit => n85_shl_8bit
  );

  -- output drivers
  a <= n32_a;
  b <= n32_b;
  c <= n32_c;
  d <= n32_d;
  e <= n32_e;
  f <= n32_f;
  g <= n32_g;
  d0 <= n1_d0;
  d1 <= n1_d1;
  d2 <= n1_d2;
  d3 <= n1_d3;
  sch_sch14611_d1_data_bus(3) <= n2_y;
  sch_sch14611_d1_data_bus(2) <= n3_y;
  sch_sch14611_d1_data_bus(1) <= n4_y;
  sch_sch14611_d1_data_bus(0) <= n5_y;
  sch_sch14611_d0_data_bus(3) <= n6_y;
  sch_sch14611_d0_data_bus(2) <= n7_y;
  sch_sch14611_d0_data_bus(1) <= n8_y;
  sch_sch14611_d0_data_bus(0) <= n9_y;
  sch_sch14611_d3_data_bus(3) <= n52_y;
  sch_sch14611_d3_data_bus(2) <= n53_y;
  sch_sch14611_d3_data_bus(1) <= n54_y;
  sch_sch14611_d3_data_bus(0) <= n55_y;
  sch_sch14611_d2_data_bus(3) <= n56_y;
  sch_sch14611_d2_data_bus(2) <= n57_y;
  sch_sch14611_d2_data_bus(1) <= n58_y;
  sch_sch14611_d2_data_bus(0) <= n59_y;

end Behavioral;

-- ============================================================
-- Entity: lab9_mode_selector
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab9_mode_selector

entity lab9_mode_selector is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mode : out STD_LOGIC_VECTOR(1 downto 0)
  );
end lab9_mode_selector;

architecture Behavioral of lab9_mode_selector is
  signal n4_o, n10_o, n11_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n2_q;
  n10_o <= n1_q;
  n11_o <= n2_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n4_o='0' and n4_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n4_o='1' and n4_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n4_o='1' and n4_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (trigger='0' and trigger='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (trigger='1' and trigger='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (trigger='1' and trigger='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;

  -- output drivers
  mode(0) <= n11_o;
  mode(1) <= n10_o;

end Behavioral;

-- ============================================================
-- Entity: demux1_4_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: demux1_4_8bit

entity demux1_4_8bit is
  Port (
    input : in  STD_LOGIC_VECTOR(7 downto 0);
    selector : in  STD_LOGIC_VECTOR(1 downto 0);
    out0 : out STD_LOGIC_VECTOR(7 downto 0);
    out1 : out STD_LOGIC_VECTOR(7 downto 0);
    out2 : out STD_LOGIC_VECTOR(7 downto 0);
    out3 : out STD_LOGIC_VECTOR(7 downto 0)
  );
end demux1_4_8bit;

architecture Behavioral of demux1_4_8bit is
  component and_8bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC;
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n13_y, n14_y, n18_o, n19_o : STD_LOGIC;
  signal n9_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n10_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n11_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n12_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_o <= n5_o and n6_o;
  n2_o <= n7_o and n19_o;
  n3_o <= n18_o and n8_o;
  n4_o <= n18_o and n19_o;
  n5_o <= not n18_o;
  n6_o <= not n19_o;
  n7_o <= not n18_o;
  n8_o <= not n19_o;
  n13_y <= selector(0);
  n14_y <= selector(1);
  n18_o <= n14_y;
  n19_o <= n13_y;

  -- sub-component instantiations
  u_0_c15453 : and_8bit_1bit port map (
    a => input,
    b => n1_o,
    output => n9_output
  );
  u_1_c15454 : and_8bit_1bit port map (
    a => input,
    b => n2_o,
    output => n10_output
  );
  u_2_c15455 : and_8bit_1bit port map (
    a => input,
    b => n3_o,
    output => n11_output
  );
  u_3_c15456 : and_8bit_1bit port map (
    a => input,
    b => n4_o,
    output => n12_output
  );

  -- output drivers
  out0 <= n9_output;
  out1 <= n10_output;
  out2 <= n11_output;
  out3 <= n12_output;

end Behavioral;

-- ============================================================
-- Entity: mux4_1_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mux4_1_8bit

entity mux4_1_8bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    in1 : in  STD_LOGIC_VECTOR(7 downto 0);
    in2 : in  STD_LOGIC_VECTOR(7 downto 0);
    in3 : in  STD_LOGIC_VECTOR(7 downto 0);
    selector : in  STD_LOGIC_VECTOR(1 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end mux4_1_8bit;

architecture Behavioral of mux4_1_8bit is
  component and_8bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC;
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component or_8bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC_VECTOR(7 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n16_o, n17_o, n21_y, n22_y : STD_LOGIC;
  signal n1_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n2_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n3_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n4_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n24_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n25_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n26_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n5_o <= n9_o and n10_o;
  n6_o <= n11_o and n17_o;
  n7_o <= n16_o and n12_o;
  n8_o <= n16_o and n17_o;
  n9_o <= not n16_o;
  n10_o <= not n17_o;
  n11_o <= not n16_o;
  n12_o <= not n17_o;
  n16_o <= n21_y;
  n17_o <= n22_y;
  n21_y <= selector(1);
  n22_y <= selector(0);

  -- sub-component instantiations
  u_0_c15545 : and_8bit_1bit port map (
    a => in0,
    b => n5_o,
    output => n1_output
  );
  u_1_c15546 : and_8bit_1bit port map (
    a => in1,
    b => n6_o,
    output => n2_output
  );
  u_2_c15547 : and_8bit_1bit port map (
    a => in2,
    b => n7_o,
    output => n3_output
  );
  u_3_c15548 : and_8bit_1bit port map (
    a => in3,
    b => n8_o,
    output => n4_output
  );
  u_4_c15645 : or_8bit port map (
    a => n3_output,
    b => n4_output,
    output => n24_output
  );
  u_5_c15646 : or_8bit port map (
    a => n2_output,
    b => n24_output,
    output => n25_output
  );
  u_6_c15647 : or_8bit port map (
    a => n1_output,
    b => n25_output,
    output => n26_output
  );

  -- output drivers
  output <= n26_output;

end Behavioral;

-- ============================================================
-- Entity: add8_bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: add8_bit

entity add8_bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    sum_8bit : out STD_LOGIC_VECTOR(7 downto 0);
    carry_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end add8_bit;

architecture Behavioral of add8_bit is
  component fas8
    Port (
      lhs_0_lsb : in  STD_LOGIC;
      rhs_0_lsb : in  STD_LOGIC;
      lhs_1 : in  STD_LOGIC;
      rhs_1 : in  STD_LOGIC;
      lhs_2 : in  STD_LOGIC;
      rhs_2 : in  STD_LOGIC;
      lhs_3 : in  STD_LOGIC;
      rhs_3 : in  STD_LOGIC;
      lhs_4 : in  STD_LOGIC;
      rhs_4 : in  STD_LOGIC;
      lhs_5 : in  STD_LOGIC;
      rhs_5 : in  STD_LOGIC;
      lhs_6 : in  STD_LOGIC;
      rhs_6 : in  STD_LOGIC;
      lhs_7_msb : in  STD_LOGIC;
      rhs_7_msb : in  STD_LOGIC;
      sub : in  STD_LOGIC;
      sum_0 : out STD_LOGIC;
      sum_1 : out STD_LOGIC;
      sum_2 : out STD_LOGIC;
      sum_3 : out STD_LOGIC;
      sum_4 : out STD_LOGIC;
      sum_5 : out STD_LOGIC;
      sum_6 : out STD_LOGIC;
      sum_7 : out STD_LOGIC;
      carry_out : out STD_LOGIC
    );
  end component;
  signal n1_sum_0, n1_sum_1, n1_sum_2, n1_sum_3, n1_sum_4, n1_sum_5, n1_sum_6, n1_sum_7, n1_carry_out, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y : STD_LOGIC;
begin

  -- combinational logic
  n2_y <= lhs(0);
  n3_y <= rhs(0);
  n4_y <= lhs(1);
  n5_y <= rhs(1);
  n6_y <= lhs(2);
  n7_y <= rhs(2);
  n8_y <= lhs(3);
  n9_y <= rhs(3);
  n10_y <= lhs(4);
  n11_y <= rhs(4);
  n12_y <= lhs(5);
  n13_y <= rhs(5);
  n14_y <= lhs(6);
  n15_y <= rhs(6);
  n16_y <= lhs(7);
  n17_y <= rhs(7);

  -- sub-component instantiations
  u_0_c15849 : fas8 port map (
    lhs_0_lsb => n2_y,
    rhs_0_lsb => n3_y,
    lhs_1 => n4_y,
    rhs_1 => n5_y,
    lhs_2 => n6_y,
    rhs_2 => n7_y,
    lhs_3 => n8_y,
    rhs_3 => n9_y,
    lhs_4 => n10_y,
    rhs_4 => n11_y,
    lhs_5 => n12_y,
    rhs_5 => n13_y,
    lhs_6 => n14_y,
    rhs_6 => n15_y,
    lhs_7_msb => n16_y,
    rhs_7_msb => n17_y,
    sub => STD_LOGIC'('0'),
    sum_0 => n1_sum_0,
    sum_1 => n1_sum_1,
    sum_2 => n1_sum_2,
    sum_3 => n1_sum_3,
    sum_4 => n1_sum_4,
    sum_5 => n1_sum_5,
    sum_6 => n1_sum_6,
    sum_7 => n1_sum_7,
    carry_out => n1_carry_out
  );

  -- output drivers
  sum_8bit(0) <= n1_sum_0;
  sum_8bit(1) <= n1_sum_1;
  sum_8bit(2) <= n1_sum_2;
  sum_8bit(3) <= n1_sum_3;
  sum_8bit(4) <= n1_sum_4;
  sum_8bit(5) <= n1_sum_5;
  sum_8bit(6) <= n1_sum_6;
  sum_8bit(7) <= n1_sum_7;
  carry_out(0) <= n1_carry_out;
  carry_out(1) <= STD_LOGIC'('0');
  carry_out(2) <= STD_LOGIC'('0');
  carry_out(3) <= STD_LOGIC'('0');
  carry_out(4) <= STD_LOGIC'('0');
  carry_out(5) <= STD_LOGIC'('0');
  carry_out(6) <= STD_LOGIC'('0');
  carry_out(7) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: sub8_bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: sub8_bit

entity sub8_bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    sub_8bit : out STD_LOGIC_VECTOR(7 downto 0);
    carry_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end sub8_bit;

architecture Behavioral of sub8_bit is
  component fas8
    Port (
      lhs_0_lsb : in  STD_LOGIC;
      rhs_0_lsb : in  STD_LOGIC;
      lhs_1 : in  STD_LOGIC;
      rhs_1 : in  STD_LOGIC;
      lhs_2 : in  STD_LOGIC;
      rhs_2 : in  STD_LOGIC;
      lhs_3 : in  STD_LOGIC;
      rhs_3 : in  STD_LOGIC;
      lhs_4 : in  STD_LOGIC;
      rhs_4 : in  STD_LOGIC;
      lhs_5 : in  STD_LOGIC;
      rhs_5 : in  STD_LOGIC;
      lhs_6 : in  STD_LOGIC;
      rhs_6 : in  STD_LOGIC;
      lhs_7_msb : in  STD_LOGIC;
      rhs_7_msb : in  STD_LOGIC;
      sub : in  STD_LOGIC;
      sum_0 : out STD_LOGIC;
      sum_1 : out STD_LOGIC;
      sum_2 : out STD_LOGIC;
      sum_3 : out STD_LOGIC;
      sum_4 : out STD_LOGIC;
      sum_5 : out STD_LOGIC;
      sum_6 : out STD_LOGIC;
      sum_7 : out STD_LOGIC;
      carry_out : out STD_LOGIC
    );
  end component;
  signal n1_sum_0, n1_sum_1, n1_sum_2, n1_sum_3, n1_sum_4, n1_sum_5, n1_sum_6, n1_sum_7, n1_carry_out, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y : STD_LOGIC;
begin

  -- combinational logic
  n2_y <= lhs(0);
  n3_y <= rhs(0);
  n4_y <= lhs(1);
  n5_y <= rhs(1);
  n6_y <= lhs(2);
  n7_y <= rhs(2);
  n8_y <= lhs(3);
  n9_y <= rhs(3);
  n10_y <= lhs(4);
  n11_y <= rhs(4);
  n12_y <= lhs(5);
  n13_y <= rhs(5);
  n14_y <= lhs(6);
  n15_y <= rhs(6);
  n16_y <= lhs(7);
  n17_y <= rhs(7);

  -- sub-component instantiations
  u_0_c16145 : fas8 port map (
    lhs_0_lsb => n2_y,
    rhs_0_lsb => n3_y,
    lhs_1 => n4_y,
    rhs_1 => n5_y,
    lhs_2 => n6_y,
    rhs_2 => n7_y,
    lhs_3 => n8_y,
    rhs_3 => n9_y,
    lhs_4 => n10_y,
    rhs_4 => n11_y,
    lhs_5 => n12_y,
    rhs_5 => n13_y,
    lhs_6 => n14_y,
    rhs_6 => n15_y,
    lhs_7_msb => n16_y,
    rhs_7_msb => n17_y,
    sub => STD_LOGIC'('1'),
    sum_0 => n1_sum_0,
    sum_1 => n1_sum_1,
    sum_2 => n1_sum_2,
    sum_3 => n1_sum_3,
    sum_4 => n1_sum_4,
    sum_5 => n1_sum_5,
    sum_6 => n1_sum_6,
    sum_7 => n1_sum_7,
    carry_out => n1_carry_out
  );

  -- output drivers
  sub_8bit(0) <= n1_sum_0;
  sub_8bit(1) <= n1_sum_1;
  sub_8bit(2) <= n1_sum_2;
  sub_8bit(3) <= n1_sum_3;
  sub_8bit(4) <= n1_sum_4;
  sub_8bit(5) <= n1_sum_5;
  sub_8bit(6) <= n1_sum_6;
  sub_8bit(7) <= n1_sum_7;
  carry_out(0) <= n1_carry_out;
  carry_out(1) <= STD_LOGIC'('0');
  carry_out(2) <= STD_LOGIC'('0');
  carry_out(3) <= STD_LOGIC'('0');
  carry_out(4) <= STD_LOGIC'('0');
  carry_out(5) <= STD_LOGIC'('0');
  carry_out(6) <= STD_LOGIC'('0');
  carry_out(7) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: xor_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: xor_8bit

entity xor_8bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    xor_8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end xor_8bit;

architecture Behavioral of xor_8bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y, n24_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n9_y xor n10_y;
  n2_o <= n11_y xor n12_y;
  n3_o <= n13_y xor n14_y;
  n4_o <= n15_y xor n16_y;
  n5_o <= n17_y xor n18_y;
  n6_o <= n19_y xor n20_y;
  n7_o <= n21_y xor n22_y;
  n8_o <= n23_y xor n24_y;
  n9_y <= lhs(7);
  n10_y <= rhs(7);
  n11_y <= lhs(6);
  n12_y <= rhs(6);
  n13_y <= lhs(5);
  n14_y <= rhs(5);
  n15_y <= lhs(4);
  n16_y <= rhs(4);
  n17_y <= lhs(3);
  n18_y <= rhs(3);
  n19_y <= lhs(2);
  n20_y <= rhs(2);
  n21_y <= lhs(1);
  n22_y <= rhs(1);
  n23_y <= lhs(0);
  n24_y <= rhs(0);

  -- output drivers
  xor_8bit(7) <= n1_o;
  xor_8bit(6) <= n2_o;
  xor_8bit(5) <= n3_o;
  xor_8bit(4) <= n4_o;
  xor_8bit(3) <= n5_o;
  xor_8bit(2) <= n6_o;
  xor_8bit(1) <= n7_o;
  xor_8bit(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: shl_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: shl_8bit

entity shl_8bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    shl_8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end shl_8bit;

architecture Behavioral of shl_8bit is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n15_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= in0(6);
  n2_y <= in0(5);
  n3_y <= in0(4);
  n4_y <= in0(3);
  n5_y <= in0(2);
  n6_y <= in0(1);
  n15_y <= in0(0);

  -- output drivers
  shl_8bit(7) <= n1_y;
  shl_8bit(6) <= n2_y;
  shl_8bit(5) <= n3_y;
  shl_8bit(4) <= n4_y;
  shl_8bit(3) <= n5_y;
  shl_8bit(2) <= n6_y;
  shl_8bit(1) <= n15_y;
  shl_8bit(0) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: mod50_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50_sync

entity mod50_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod50_out : out STD_LOGIC
  );
end mod50_sync;

architecture Behavioral of mod50_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c16652 : mod5_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c16653 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => reset,
    mod10_out => n2_mod10_out
  );

  -- output drivers
  mod50_out <= n2_mod10_out;

end Behavioral;
