-- ============================================================
-- Entity: mux4_1_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mux4_1_8bit

entity mux4_1_8bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    in1 : in  STD_LOGIC_VECTOR(7 downto 0);
    in2 : in  STD_LOGIC_VECTOR(7 downto 0);
    in3 : in  STD_LOGIC_VECTOR(7 downto 0);
    selector : in  STD_LOGIC_VECTOR(1 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end mux4_1_8bit;

architecture Behavioral of mux4_1_8bit is
  component and_8bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC;
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component or_8bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC_VECTOR(7 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  signal n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n16_o, n17_o, n21_y, n22_y : STD_LOGIC;
  signal n1_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n2_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n3_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n4_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n24_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n25_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n26_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n5_o <= n9_o and n10_o;
  n6_o <= n11_o and n17_o;
  n7_o <= n16_o and n12_o;
  n8_o <= n16_o and n17_o;
  n9_o <= not n16_o;
  n10_o <= not n17_o;
  n11_o <= not n16_o;
  n12_o <= not n17_o;
  n16_o <= n21_y;
  n17_o <= n22_y;
  n21_y <= selector(1);
  n22_y <= selector(0);

  -- sub-component instantiations
  u_0_c15545 : and_8bit_1bit port map (
    a => in0,
    b => n5_o,
    output => n1_output
  );
  u_1_c15546 : and_8bit_1bit port map (
    a => in1,
    b => n6_o,
    output => n2_output
  );
  u_2_c15547 : and_8bit_1bit port map (
    a => in2,
    b => n7_o,
    output => n3_output
  );
  u_3_c15548 : and_8bit_1bit port map (
    a => in3,
    b => n8_o,
    output => n4_output
  );
  u_4_c15645 : or_8bit port map (
    a => n3_output,
    b => n4_output,
    output => n24_output
  );
  u_5_c15646 : or_8bit port map (
    a => n2_output,
    b => n24_output,
    output => n25_output
  );
  u_6_c15647 : or_8bit port map (
    a => n1_output,
    b => n25_output,
    output => n26_output
  );

  -- output drivers
  output <= n26_output;

end Behavioral;