-- ============================================================
-- Entity: or_4bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_4bit

entity or_4bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC_VECTOR(3 downto 0);
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end or_4bit;

architecture Behavioral of or_4bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n5_y or n6_y;
  n2_o <= n7_y or n8_y;
  n3_o <= n9_y or n10_y;
  n4_o <= n11_y or n12_y;
  n5_y <= a(3);
  n6_y <= b(3);
  n7_y <= a(2);
  n8_y <= b(2);
  n9_y <= a(1);
  n10_y <= b(1);
  n11_y <= a(0);
  n12_y <= b(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;