-- ============================================================
-- Entity: or_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_8bit

entity or_8bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC_VECTOR(7 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end or_8bit;

architecture Behavioral of or_8bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y, n24_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n24_y or n23_y;
  n2_o <= n22_y or n21_y;
  n3_o <= n20_y or n19_y;
  n4_o <= n18_y or n17_y;
  n5_o <= n16_y or n15_y;
  n6_o <= n14_y or n13_y;
  n7_o <= n12_y or n11_y;
  n8_o <= n10_y or n9_y;
  n9_y <= b(0);
  n10_y <= a(0);
  n11_y <= b(1);
  n12_y <= a(1);
  n13_y <= b(2);
  n14_y <= a(2);
  n15_y <= b(3);
  n16_y <= a(3);
  n17_y <= b(4);
  n18_y <= a(4);
  n19_y <= b(5);
  n20_y <= a(5);
  n21_y <= b(6);
  n22_y <= a(6);
  n23_y <= b(7);
  n24_y <= a(7);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;