-- ============================================================
-- Entity: shl_8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: shl_8bit

entity shl_8bit is
  Port (
    in0 : in  STD_LOGIC_VECTOR(7 downto 0);
    shl_8bit : out STD_LOGIC_VECTOR(7 downto 0)
  );
end shl_8bit;

architecture Behavioral of shl_8bit is
  signal n1_y, n2_y, n3_y, n4_y, n5_y, n6_y, n15_y : STD_LOGIC;
begin

  -- combinational logic
  n1_y <= in0(6);
  n2_y <= in0(5);
  n3_y <= in0(4);
  n4_y <= in0(3);
  n5_y <= in0(2);
  n6_y <= in0(1);
  n15_y <= in0(0);

  -- output drivers
  shl_8bit(7) <= n1_y;
  shl_8bit(6) <= n2_y;
  shl_8bit(5) <= n3_y;
  shl_8bit(4) <= n4_y;
  shl_8bit(3) <= n5_y;
  shl_8bit(2) <= n6_y;
  shl_8bit(1) <= n15_y;
  shl_8bit(0) <= STD_LOGIC'('0');

end Behavioral;
