-- ============================================================
-- Entity: sub8_bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: sub8_bit

entity sub8_bit is
  Port (
    lhs : in  STD_LOGIC_VECTOR(7 downto 0);
    rhs : in  STD_LOGIC_VECTOR(7 downto 0);
    sub_8bit : out STD_LOGIC_VECTOR(7 downto 0);
    carry_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end sub8_bit;

architecture Behavioral of sub8_bit is
  component fas8
    Port (
      lhs_0_lsb : in  STD_LOGIC;
      rhs_0_lsb : in  STD_LOGIC;
      lhs_1 : in  STD_LOGIC;
      rhs_1 : in  STD_LOGIC;
      lhs_2 : in  STD_LOGIC;
      rhs_2 : in  STD_LOGIC;
      lhs_3 : in  STD_LOGIC;
      rhs_3 : in  STD_LOGIC;
      lhs_4 : in  STD_LOGIC;
      rhs_4 : in  STD_LOGIC;
      lhs_5 : in  STD_LOGIC;
      rhs_5 : in  STD_LOGIC;
      lhs_6 : in  STD_LOGIC;
      rhs_6 : in  STD_LOGIC;
      lhs_7_msb : in  STD_LOGIC;
      rhs_7_msb : in  STD_LOGIC;
      sub : in  STD_LOGIC;
      sum_0 : out STD_LOGIC;
      sum_1 : out STD_LOGIC;
      sum_2 : out STD_LOGIC;
      sum_3 : out STD_LOGIC;
      sum_4 : out STD_LOGIC;
      sum_5 : out STD_LOGIC;
      sum_6 : out STD_LOGIC;
      sum_7 : out STD_LOGIC;
      carry_out : out STD_LOGIC
    );
  end component;
  signal n1_sum_0, n1_sum_1, n1_sum_2, n1_sum_3, n1_sum_4, n1_sum_5, n1_sum_6, n1_sum_7, n1_carry_out, n2_y, n3_y, n4_y, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y : STD_LOGIC;
begin

  -- combinational logic
  n2_y <= lhs(0);
  n3_y <= rhs(0);
  n4_y <= lhs(1);
  n5_y <= rhs(1);
  n6_y <= lhs(2);
  n7_y <= rhs(2);
  n8_y <= lhs(3);
  n9_y <= rhs(3);
  n10_y <= lhs(4);
  n11_y <= rhs(4);
  n12_y <= lhs(5);
  n13_y <= rhs(5);
  n14_y <= lhs(6);
  n15_y <= rhs(6);
  n16_y <= lhs(7);
  n17_y <= rhs(7);

  -- sub-component instantiations
  u_0_c16145 : fas8 port map (
    lhs_0_lsb => n2_y,
    rhs_0_lsb => n3_y,
    lhs_1 => n4_y,
    rhs_1 => n5_y,
    lhs_2 => n6_y,
    rhs_2 => n7_y,
    lhs_3 => n8_y,
    rhs_3 => n9_y,
    lhs_4 => n10_y,
    rhs_4 => n11_y,
    lhs_5 => n12_y,
    rhs_5 => n13_y,
    lhs_6 => n14_y,
    rhs_6 => n15_y,
    lhs_7_msb => n16_y,
    rhs_7_msb => n17_y,
    sub => STD_LOGIC'('1'),
    sum_0 => n1_sum_0,
    sum_1 => n1_sum_1,
    sum_2 => n1_sum_2,
    sum_3 => n1_sum_3,
    sum_4 => n1_sum_4,
    sum_5 => n1_sum_5,
    sum_6 => n1_sum_6,
    sum_7 => n1_sum_7,
    carry_out => n1_carry_out
  );

  -- output drivers
  sub_8bit(0) <= n1_sum_0;
  sub_8bit(1) <= n1_sum_1;
  sub_8bit(2) <= n1_sum_2;
  sub_8bit(3) <= n1_sum_3;
  sub_8bit(4) <= n1_sum_4;
  sub_8bit(5) <= n1_sum_5;
  sub_8bit(6) <= n1_sum_6;
  sub_8bit(7) <= n1_sum_7;
  carry_out(0) <= n1_carry_out;
  carry_out(1) <= STD_LOGIC'('0');
  carry_out(2) <= STD_LOGIC'('0');
  carry_out(3) <= STD_LOGIC'('0');
  carry_out(4) <= STD_LOGIC'('0');
  carry_out(5) <= STD_LOGIC'('0');
  carry_out(6) <= STD_LOGIC'('0');
  carry_out(7) <= STD_LOGIC'('0');

end Behavioral;