-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
  Port (
    in1_msb : in  STD_LOGIC;
    in2 : in  STD_LOGIC;
    in3 : in  STD_LOGIC;
    in4_lsb : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC
  );
end hex_7seg;

architecture Behavioral of hex_7seg is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in1_msb and in2 and n40_o and in4_lsb;
  n2_o <= in1_msb and n39_o and in3 and in4_lsb;
  n3_o <= n36_o and in2 and n37_o and n38_o;
  n4_o <= n33_o and n34_o and n35_o and in4_lsb;
  n5_o <= n4_o or n3_o or n2_o or n1_o;
  n6_o <= in2 and in3 and n44_o;
  n7_o <= in1_msb and in3 and in4_lsb;
  n8_o <= in1_msb and in2 and n43_o;
  n9_o <= n41_o and in2 and n42_o and in4_lsb;
  n10_o <= n9_o or n8_o or n7_o or n6_o;
  n11_o <= in1_msb and in2 and n48_o;
  n12_o <= in1_msb and in2 and in3;
  n13_o <= n45_o and n46_o and in3 and n47_o;
  n14_o <= n13_o or n12_o or n11_o;
  n15_o <= in2 and in3 and in4_lsb;
  n16_o <= in1_msb and n55_o and in3 and n56_o;
  n17_o <= n52_o and in2 and n53_o and n54_o;
  n18_o <= n49_o and n50_o and n51_o and in4_lsb;
  n19_o <= n18_o or n17_o or n16_o or n15_o;
  n20_o <= n60_o and n61_o and in4_lsb;
  n21_o <= n59_o and in4_lsb;
  n22_o <= n57_o and in2 and n58_o;
  n23_o <= n22_o or n21_o or n20_o;
  n24_o <= in1_msb and in2 and n67_o and in4_lsb;
  n25_o <= n66_o and in3 and in4_lsb;
  n26_o <= n64_o and n65_o and in4_lsb;
  n27_o <= n62_o and n63_o and in3;
  n28_o <= n27_o or n26_o or n25_o or n24_o;
  n29_o <= in1_msb and in2 and n72_o and n73_o;
  n30_o <= n71_o and in2 and in3 and in4_lsb;
  n31_o <= n68_o and n69_o and n70_o;
  n32_o <= n31_o or n30_o or n29_o;
  n33_o <= not in1_msb;
  n34_o <= not in2;
  n35_o <= not in3;
  n36_o <= not in1_msb;
  n37_o <= not in3;
  n38_o <= not in4_lsb;
  n39_o <= not in2;
  n40_o <= not in3;
  n41_o <= not in1_msb;
  n42_o <= not in3;
  n43_o <= not in4_lsb;
  n44_o <= not in4_lsb;
  n45_o <= not in1_msb;
  n46_o <= not in2;
  n47_o <= not in4_lsb;
  n48_o <= not in4_lsb;
  n49_o <= not in1_msb;
  n50_o <= not in2;
  n51_o <= not in3;
  n52_o <= not in1_msb;
  n53_o <= not in3;
  n54_o <= not in4_lsb;
  n55_o <= not in2;
  n56_o <= not in4_lsb;
  n57_o <= not in1_msb;
  n58_o <= not in3;
  n59_o <= not in1_msb;
  n60_o <= not in2;
  n61_o <= not in3;
  n62_o <= not in1_msb;
  n63_o <= not in2;
  n64_o <= not in1_msb;
  n65_o <= not in2;
  n66_o <= not in1_msb;
  n67_o <= not in3;
  n68_o <= not in1_msb;
  n69_o <= not in2;
  n70_o <= not in3;
  n71_o <= not in1_msb;
  n72_o <= not in3;
  n73_o <= not in4_lsb;

  -- output drivers
  a <= n5_o;
  b <= n10_o;
  c <= n14_o;
  d <= n19_o;
  e <= n23_o;
  f <= n28_o;
  g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: counter_2345679
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter_2345679

entity counter_2345679 is
  Port (
    clk : in  STD_LOGIC;
    q3_msb : out STD_LOGIC;
    q2 : out STD_LOGIC;
    q1 : out STD_LOGIC;
    q0_lsb : out STD_LOGIC
  );
end counter_2345679;

architecture Behavioral of counter_2345679 is
  signal n5_o, n7_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n19_q : STD_LOGIC := '0';
  signal n19_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n5_o <= n3_qn or n2_qn;
  n7_o <= n1_q and n2_q;
  n12_o <= n1_q and n2_q and n3_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (false and n5_o = '1') then n1_q <= '0';
      elsif (true and n5_o = '0') then n1_q <= '1';
      elsif (true and n5_o = '1') then n1_q <= not n1_q;
      end if;
    end if;
  end process;
  process(clk, n19_qn)
  begin
    if n19_qn = '1' then
      n2_q <= '1';
      n2_qn <= '0';
    elsif rising_edge(clk) then
      if    (n1_q = '0' and n1_q = '1') then n2_q <= '0'; n2_qn <= '1';
      elsif (n1_q = '1' and n1_q = '0') then n2_q <= '1'; n2_qn <= '0';
      elsif (n1_q = '1' and n1_q = '1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n7_o = '0' and n7_o = '1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n7_o = '1' and n7_o = '0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n7_o = '1' and n7_o = '1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n12_o = '0' and true) then n4_q <= '0';
      elsif (n12_o = '1' and false) then n4_q <= '1';
      elsif (n12_o = '1' and true) then n4_q <= not n4_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      n19_q <= '1'; n19_qn <= '0';
    end if;
  end process;

  -- output drivers
  q3_msb <= n4_q;
  q2 <= n3_q;
  q1 <= n2_q;
  q0_lsb <= n1_q;

end Behavioral;

-- ============================================================
-- Entity: lab5_3
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab5_3

entity lab5_3 is
  Port (
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab5_3;

architecture Behavioral of lab5_3 is
  component counter_2345679
    Port (
      clk : in  STD_LOGIC;
      q3_msb : out STD_LOGIC;
      q2 : out STD_LOGIC;
      q1 : out STD_LOGIC;
      q0_lsb : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component mod50m_sync
    Port (
      clk : in  STD_LOGIC;
      clk_mod50m : out STD_LOGIC
    );
  end component;
  signal n1_q3_msb, n1_q2, n1_q1, n1_q0_lsb, n2_a, n2_b, n2_c, n2_d, n2_e, n2_f, n2_g, n4_clk_mod50m : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6233 : counter_2345679 port map (
    clk => n4_clk_mod50m,
    q3_msb => n1_q3_msb,
    q2 => n1_q2,
    q1 => n1_q1,
    q0_lsb => n1_q0_lsb
  );
  u_1_c6237 : hex_7seg port map (
    in1_msb => n1_q3_msb,
    in2 => n1_q2,
    in3 => n1_q1,
    in4_lsb => n1_q0_lsb,
    a => n2_a,
    b => n2_b,
    c => n2_c,
    d => n2_d,
    e => n2_e,
    f => n2_f,
    g => n2_g
  );
  u_2_c7040 : mod50m_sync port map (
    clk => clk,
    clk_mod50m => n4_clk_mod50m
  );

  -- output drivers
  a <= n2_a;
  b <= n2_b;
  c <= n2_c;
  d <= n2_d;
  e <= n2_e;
  f <= n2_f;
  g <= n2_g;
  d0 <= '1';
  d1 <= '0';
  d2 <= '0';
  d3 <= '0';

end Behavioral;

-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n3_o, n6_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n13_q : STD_LOGIC := '0';
begin

  -- combinational logic
  n3_o <= last_output and n1_q;
  n6_o <= n3_o and n2_q;
  n12_o <= n5_q and n2_qn and n1_qn;

  -- sequential logic (flip-flops)
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (last_output = '1') then n1_q <= not n1_q; n1_qn <= n1_q; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n3_o = '1') then n2_q <= not n2_q; n2_qn <= n2_q; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n5_q <= '0';
    elsif rising_edge(clk) then
      if (n6_o = '1') then n5_q <= not n5_q; end if;
    end if;
  end process;
  process(clk, n13_q)
  begin
    if n13_q = '1' then
      n13_q  <= '0';
    elsif rising_edge(clk) then
      n13_q  <= n12_o;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  signal n3_o, n6_o, n11_o, n17_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n5_qn : STD_LOGIC := '1';
  signal n10_q : STD_LOGIC := '0';
  signal n19_q : STD_LOGIC := '0';
begin

  -- combinational logic
  n3_o <= last_output and n1_q;
  n6_o <= n3_o and n2_q;
  n11_o <= n6_o and n5_q;
  n17_o <= n10_q and n5_qn and n2_qn and n1_q;

  -- sequential logic (flip-flops)
  process(clk, n19_q)
  begin
    if n19_q = '1' then
      n1_q <= '0';
    elsif rising_edge(clk) then
      if (last_output = '1') then n1_q <= not n1_q; end if;
    end if;
  end process;
  process(clk, n19_q)
  begin
    if n19_q = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n3_o = '1') then n2_q <= not n2_q; n2_qn <= n2_q; end if;
    end if;
  end process;
  process(clk, n19_q)
  begin
    if n19_q = '1' then
      n5_q <= '0';
      n5_qn <= '1';
    elsif rising_edge(clk) then
      if (n6_o = '1') then n5_q <= not n5_q; n5_qn <= n5_q; end if;
    end if;
  end process;
  process(clk, n19_q)
  begin
    if n19_q = '1' then
      n10_q <= '0';
    elsif rising_edge(clk) then
      if (n11_o = '1') then n10_q <= not n10_q; end if;
    end if;
  end process;
  process(clk, n19_q)
  begin
    if n19_q = '1' then
      n19_q  <= '0';
    elsif rising_edge(clk) then
      n19_q  <= n17_o;
    end if;
  end process;

  -- output drivers
  mod10_out <= n17_o;

end Behavioral;

-- ============================================================
-- Entity: mod50m_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50m_sync

entity mod50m_sync is
  Port (
    clk : in  STD_LOGIC;
    clk_mod50m : out STD_LOGIC
  );
end mod50m_sync;

architecture Behavioral of mod50m_sync is
  component mod5_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out, n6_mod10_out, n7_mod10_out, n14_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6957 : mod5_sync port map (
    last_output => '1',
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c6958 : mod10_sync port map (
    last_output => n1_mod5_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );
  u_2_c6959 : mod10_sync port map (
    last_output => n2_mod10_out,
    clk => clk,
    mod10_out => n3_mod10_out
  );
  u_3_c6960 : mod10_sync port map (
    last_output => n3_mod10_out,
    clk => clk,
    mod10_out => n4_mod10_out
  );
  u_4_c6961 : mod10_sync port map (
    last_output => n4_mod10_out,
    clk => clk,
    mod10_out => n5_mod10_out
  );
  u_5_c6962 : mod10_sync port map (
    last_output => n5_mod10_out,
    clk => clk,
    mod10_out => n6_mod10_out
  );
  u_6_c6963 : mod10_sync port map (
    last_output => n6_mod10_out,
    clk => clk,
    mod10_out => n7_mod10_out
  );
  u_7_c7002 : mod10_sync port map (
    last_output => n7_mod10_out,
    clk => clk,
    mod10_out => n14_mod10_out
  );

  -- output drivers
  clk_mod50m <= n14_mod10_out;

end Behavioral;
