-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
  Port (
    in1_msb : in  STD_LOGIC;
    in2 : in  STD_LOGIC;
    in3 : in  STD_LOGIC;
    in4_lsb : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC
  );
end hex_7seg;

architecture Behavioral of hex_7seg is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in1_msb and in2 and n40_o and in4_lsb;
  n2_o <= in1_msb and n39_o and in3 and in4_lsb;
  n3_o <= n36_o and in2 and n37_o and n38_o;
  n4_o <= n33_o and n34_o and n35_o and in4_lsb;
  n5_o <= n4_o or n3_o or n2_o or n1_o;
  n6_o <= in2 and in3 and n44_o;
  n7_o <= in1_msb and in3 and in4_lsb;
  n8_o <= in1_msb and in2 and n43_o;
  n9_o <= n41_o and in2 and n42_o and in4_lsb;
  n10_o <= n9_o or n8_o or n7_o or n6_o;
  n11_o <= in1_msb and in2 and n48_o;
  n12_o <= in1_msb and in2 and in3;
  n13_o <= n45_o and n46_o and in3 and n47_o;
  n14_o <= n13_o or n12_o or n11_o;
  n15_o <= in2 and in3 and in4_lsb;
  n16_o <= in1_msb and n55_o and in3 and n56_o;
  n17_o <= n52_o and in2 and n53_o and n54_o;
  n18_o <= n49_o and n50_o and n51_o and in4_lsb;
  n19_o <= n18_o or n17_o or n16_o or n15_o;
  n20_o <= n60_o and n61_o and in4_lsb;
  n21_o <= n59_o and in4_lsb;
  n22_o <= n57_o and in2 and n58_o;
  n23_o <= n22_o or n21_o or n20_o;
  n24_o <= in1_msb and in2 and n67_o and in4_lsb;
  n25_o <= n66_o and in3 and in4_lsb;
  n26_o <= n64_o and n65_o and in4_lsb;
  n27_o <= n62_o and n63_o and in3;
  n28_o <= n27_o or n26_o or n25_o or n24_o;
  n29_o <= in1_msb and in2 and n72_o and n73_o;
  n30_o <= n71_o and in2 and in3 and in4_lsb;
  n31_o <= n68_o and n69_o and n70_o;
  n32_o <= n31_o or n30_o or n29_o;
  n33_o <= not in1_msb;
  n34_o <= not in2;
  n35_o <= not in3;
  n36_o <= not in1_msb;
  n37_o <= not in3;
  n38_o <= not in4_lsb;
  n39_o <= not in2;
  n40_o <= not in3;
  n41_o <= not in1_msb;
  n42_o <= not in3;
  n43_o <= not in4_lsb;
  n44_o <= not in4_lsb;
  n45_o <= not in1_msb;
  n46_o <= not in2;
  n47_o <= not in4_lsb;
  n48_o <= not in4_lsb;
  n49_o <= not in1_msb;
  n50_o <= not in2;
  n51_o <= not in3;
  n52_o <= not in1_msb;
  n53_o <= not in3;
  n54_o <= not in4_lsb;
  n55_o <= not in2;
  n56_o <= not in4_lsb;
  n57_o <= not in1_msb;
  n58_o <= not in3;
  n59_o <= not in1_msb;
  n60_o <= not in2;
  n61_o <= not in3;
  n62_o <= not in1_msb;
  n63_o <= not in2;
  n64_o <= not in1_msb;
  n65_o <= not in2;
  n66_o <= not in1_msb;
  n67_o <= not in3;
  n68_o <= not in1_msb;
  n69_o <= not in2;
  n70_o <= not in3;
  n71_o <= not in1_msb;
  n72_o <= not in3;
  n73_o <= not in4_lsb;

  -- output drivers
  a <= n5_o;
  b <= n10_o;
  c <= n14_o;
  d <= n19_o;
  e <= n23_o;
  f <= n28_o;
  g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: mod_5
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_5

entity mod_5 is
  Port (
    clk : in  STD_LOGIC;
    clk_mod5 : out STD_LOGIC
  );
end mod_5;

architecture Behavioral of mod_5 is
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_o, n11_o : STD_LOGIC;
begin

  -- combinational logic
  n4_o <= not n2_q;
  n11_o <= n3_q and n4_o and n1_q;

  -- sequential logic (flip-flops)
  process(clk, n11_o)
  begin
    if n11_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(n1_qn, n11_o)
  begin
    if n11_o = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(n1_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n2_qn, n11_o)
  begin
    if n11_o = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(n2_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;

  -- output drivers
  clk_mod5 <= n11_o;

end Behavioral;

-- ============================================================
-- Entity: mod_10
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_10

entity mod_10 is
  Port (
    clk : in  STD_LOGIC;
    clk_mod10 : out STD_LOGIC
  );
end mod_10;

architecture Behavioral of mod_10 is
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_q, n4_qn, n12_o, n13_o, n18_o : STD_LOGIC;
begin

  -- combinational logic
  n12_o <= not n3_q;
  n13_o <= not n1_q;
  n18_o <= n4_q and n12_o and n2_q and n13_o;

  -- sequential logic (flip-flops)
  process(clk, n18_o)
  begin
    if n18_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(n1_qn, n18_o)
  begin
    if n18_o = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(n1_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n2_qn, n18_o)
  begin
    if n18_o = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(n2_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(n3_qn, n18_o)
  begin
    if n18_o = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif rising_edge(n3_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;

  -- output drivers
  clk_mod10 <= n18_o;

end Behavioral;

-- ============================================================
-- Entity: lab5_2
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab5_2

entity lab5_2 is
  Port (
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab5_2;

architecture Behavioral of lab5_2 is
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component mod_5
    Port (
      clk : in  STD_LOGIC;
      clk_mod5 : out STD_LOGIC
    );
  end component;
  component mod_10
    Port (
      clk : in  STD_LOGIC;
      clk_mod10 : out STD_LOGIC
    );
  end component;
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n9_a, n9_b, n9_c, n9_d, n9_e, n9_f, n9_g, n10_clk_mod5, n11_clk_mod10, n12_clk_mod10, n13_clk_mod10, n14_clk_mod10, n15_clk_mod10, n16_clk_mod10, n17_clk_mod10 : STD_LOGIC;
begin

  -- sequential logic (flip-flops)
  process(n11_clk_mod10)
  begin
    if rising_edge(n11_clk_mod10) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(n1_qn)
  begin
    if rising_edge(n1_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n2_qn)
  begin
    if rising_edge(n2_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c5850 : hex_7seg port map (
    in1_msb => STD_LOGIC'('0'),
    in2 => n3_q,
    in3 => n2_q,
    in4_lsb => n1_q,
    a => n9_a,
    b => n9_b,
    c => n9_c,
    d => n9_d,
    e => n9_e,
    f => n9_f,
    g => n9_g
  );
  u_1_c5858 : mod_5 port map (
    clk => clk,
    clk_mod5 => n10_clk_mod5
  );
  u_2_c5863 : mod_10 port map (
    clk => n17_clk_mod10,
    clk_mod10 => n11_clk_mod10
  );
  u_3_c5864 : mod_10 port map (
    clk => n16_clk_mod10,
    clk_mod10 => n12_clk_mod10
  );
  u_4_c5866 : mod_10 port map (
    clk => n10_clk_mod5,
    clk_mod10 => n13_clk_mod10
  );
  u_5_c5867 : mod_10 port map (
    clk => n13_clk_mod10,
    clk_mod10 => n14_clk_mod10
  );
  u_6_c5868 : mod_10 port map (
    clk => n14_clk_mod10,
    clk_mod10 => n15_clk_mod10
  );
  u_7_c5869 : mod_10 port map (
    clk => n15_clk_mod10,
    clk_mod10 => n16_clk_mod10
  );
  u_8_c5870 : mod_10 port map (
    clk => n12_clk_mod10,
    clk_mod10 => n17_clk_mod10
  );

  -- output drivers
  a <= n9_a;
  b <= n9_b;
  c <= n9_c;
  d <= n9_d;
  e <= n9_e;
  f <= n9_f;
  g <= n9_g;
  d0 <= STD_LOGIC'('1');
  d1 <= STD_LOGIC'('1');
  d2 <= STD_LOGIC'('1');
  d3 <= STD_LOGIC'('1');

end Behavioral;
