-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
	Port (
		in1 : in	STD_LOGIC;
		in2 : in	STD_LOGIC;
		in3 : in	STD_LOGIC;
		in4 : in	STD_LOGIC;
		a : out STD_LOGIC;
		b : out STD_LOGIC;
		c : out STD_LOGIC;
		d : out STD_LOGIC;
		e : out STD_LOGIC;
		f : out STD_LOGIC;
		g : out STD_LOGIC
	);
end hex_7seg;

architecture Behavioral of hex_7seg is
	signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

	-- combinational logic
	n1_o <= in1 and in2 and n40_o and in4;
	n2_o <= in1 and n39_o and in3 and in4;
	n3_o <= n36_o and in2 and n37_o and n38_o;
	n4_o <= n33_o and n34_o and n35_o and in4;
	n5_o <= n4_o or n3_o or n2_o or n1_o;
	n6_o <= in2 and in3 and n44_o;
	n7_o <= in1 and in3 and in4;
	n8_o <= in1 and in2 and n43_o;
	n9_o <= n41_o and in2 and n42_o and in4;
	n10_o <= n9_o or n8_o or n7_o or n6_o;
	n11_o <= in1 and in2 and n48_o;
	n12_o <= in1 and in2 and in3;
	n13_o <= n45_o and n46_o and in3 and n47_o;
	n14_o <= n13_o or n12_o or n11_o;
	n15_o <= in2 and in3 and in4;
	n16_o <= in1 and n55_o and in3 and n56_o;
	n17_o <= n52_o and in2 and n53_o and n54_o;
	n18_o <= n49_o and n50_o and n51_o and in4;
	n19_o <= n18_o or n17_o or n16_o or n15_o;
	n20_o <= n60_o and n61_o and in4;
	n21_o <= n59_o and in4;
	n22_o <= n57_o and in2 and n58_o;
	n23_o <= n22_o or n21_o or n20_o;
	n24_o <= in1 and in2 and n67_o and in4;
	n25_o <= n66_o and in3 and in4;
	n26_o <= n64_o and n65_o and in4;
	n27_o <= n62_o and n63_o and in3;
	n28_o <= n27_o or n26_o or n25_o or n24_o;
	n29_o <= in1 and in2 and n72_o and n73_o;
	n30_o <= n71_o and in2 and in3 and in4;
	n31_o <= n68_o and n69_o and n70_o;
	n32_o <= n31_o or n30_o or n29_o;
	n33_o <= not in1;
	n34_o <= not in2;
	n35_o <= not in3;
	n36_o <= not in1;
	n37_o <= not in3;
	n38_o <= not in4;
	n39_o <= not in2;
	n40_o <= not in3;
	n41_o <= not in1;
	n42_o <= not in3;
	n43_o <= not in4;
	n44_o <= not in4;
	n45_o <= not in1;
	n46_o <= not in2;
	n47_o <= not in4;
	n48_o <= not in4;
	n49_o <= not in1;
	n50_o <= not in2;
	n51_o <= not in3;
	n52_o <= not in1;
	n53_o <= not in3;
	n54_o <= not in4;
	n55_o <= not in2;
	n56_o <= not in4;
	n57_o <= not in1;
	n58_o <= not in3;
	n59_o <= not in1;
	n60_o <= not in2;
	n61_o <= not in3;
	n62_o <= not in1;
	n63_o <= not in2;
	n64_o <= not in1;
	n65_o <= not in2;
	n66_o <= not in1;
	n67_o <= not in3;
	n68_o <= not in1;
	n69_o <= not in2;
	n70_o <= not in3;
	n71_o <= not in1;
	n72_o <= not in3;
	n73_o <= not in4;

	-- output drivers
	a <= n5_o;
	b <= n10_o;
	c <= n14_o;
	d <= n19_o;
	e <= n23_o;
	f <= n28_o;
	g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: mod_5
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_5

entity mod_5 is
	Port (
		clk : in	STD_LOGIC;
		clk_mod5 : out STD_LOGIC
	);
end mod_5;

architecture Behavioral of mod_5 is
	signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_o, n5_o : STD_LOGIC;
begin

	-- combinational logic
	n4_o <= not (n3_q and n5_o and n1_q);
	n5_o <= not n2_q;

	-- sequential logic (flip-flops)
	process(clk, n4_o)
	begin
		if n4_o = '1' then
			n1_q <= '0';
			n1_qn <= '1';
		elsif rising_edge(clk) then
			if		('1'='0' and '1'='1') then n1_q <= '0'; n1_qn <= '1';
			elsif ('1'='1' and '1'='0') then n1_q <= '1'; n1_qn <= '0';
			elsif ('1'='1' and '1'='1') then n1_q <= not n1_q; n1_qn <= n1_q;
			end if;
		end if;
	end process;
	process(n1_q, n4_o)
	begin
		if n4_o = '1' then
			n2_q <= '0';
			n2_qn <= '1';
		elsif rising_edge(n1_q) then
			if		('1'='0' and '1'='1') then n2_q <= '0'; n2_qn <= '1';
			elsif ('1'='1' and '1'='0') then n2_q <= '1'; n2_qn <= '0';
			elsif ('1'='1' and '1'='1') then n2_q <= not n2_q; n2_qn <= n2_q;
			end if;
		end if;
	end process;
	process(n2_q, n4_o)
	begin
		if n4_o = '1' then
			n3_q <= '0';
			n3_qn <= '1';
		elsif rising_edge(n2_q) then
			if		('1'='0' and '1'='1') then n3_q <= '0'; n3_qn <= '1';
			elsif ('1'='1' and '1'='0') then n3_q <= '1'; n3_qn <= '0';
			elsif ('1'='1' and '1'='1') then n3_q <= not n3_q; n3_qn <= n3_q;
			end if;
		end if;
	end process;

	-- output drivers
	clk_mod5 <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: lab4
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab4

entity lab4 is
	Port (
		clk : in	STD_LOGIC;
		sw22 : in	STD_LOGIC;
		sw10 : in	STD_LOGIC;
		sw21 : in	STD_LOGIC;
		sw9 : in	STD_LOGIC;
		sw19 : in	STD_LOGIC;
		sw8 : in	STD_LOGIC;
		sw17 : in	STD_LOGIC;
		sw7 : in	STD_LOGIC;
		sw15 : in	STD_LOGIC;
		sw6 : in	STD_LOGIC;
		sw13 : in	STD_LOGIC;
		sw5 : in	STD_LOGIC;
		sw12 : in	STD_LOGIC;
		sw4 : in	STD_LOGIC;
		sw11 : in	STD_LOGIC;
		sw2 : in	STD_LOGIC;
		sub : in	STD_LOGIC;
		a : out STD_LOGIC;
		b : out STD_LOGIC;
		c : out STD_LOGIC;
		d : out STD_LOGIC;
		e : out STD_LOGIC;
		f : out STD_LOGIC;
		g : out STD_LOGIC;
		d0 : out STD_LOGIC;
		d1 : out STD_LOGIC;
		d2 : out STD_LOGIC;
		d3 : out STD_LOGIC
	);
end lab4;

architecture Behavioral of lab4 is
	component mod_5
		Port (
			clk : in	STD_LOGIC;
			clk_mod5 : out STD_LOGIC
		);
	end component;
	component mod_10
		Port (
			clk : in	STD_LOGIC;
			clk_mod10 : out STD_LOGIC
		);
	end component;
	component digit_selector
		Port (
			clk : in	STD_LOGIC;
			d3 : out STD_LOGIC;
			d2 : out STD_LOGIC;
			d1 : out STD_LOGIC;
			d0 : out STD_LOGIC
		);
	end component;
	component hex_7seg
		Port (
			in1 : in	STD_LOGIC;
			in2 : in	STD_LOGIC;
			in3 : in	STD_LOGIC;
			in4 : in	STD_LOGIC;
			a : out STD_LOGIC;
			b : out STD_LOGIC;
			c : out STD_LOGIC;
			d : out STD_LOGIC;
			e : out STD_LOGIC;
			f : out STD_LOGIC;
			g : out STD_LOGIC
		);
	end component;
	component fas8
		Port (
			lhs_0 : in	STD_LOGIC;
			rhs_0 : in	STD_LOGIC;
			lhs_1 : in	STD_LOGIC;
			rhs_1 : in	STD_LOGIC;
			lhs_2 : in	STD_LOGIC;
			rhs_2 : in	STD_LOGIC;
			lhs_3 : in	STD_LOGIC;
			rhs_3 : in	STD_LOGIC;
			lhs_4 : in	STD_LOGIC;
			rhs_4 : in	STD_LOGIC;
			lhs_5 : in	STD_LOGIC;
			rhs_5 : in	STD_LOGIC;
			lhs_6 : in	STD_LOGIC;
			rhs_6 : in	STD_LOGIC;
			lhs_7 : in	STD_LOGIC;
			rhs_7 : in	STD_LOGIC;
			sub : in	STD_LOGIC;
			sum_0 : out STD_LOGIC;
			sum_1 : out STD_LOGIC;
			sum_2 : out STD_LOGIC;
			sum_3 : out STD_LOGIC;
			sum_4 : out STD_LOGIC;
			sum_5 : out STD_LOGIC;
			sum_6 : out STD_LOGIC;
			sum_7 : out STD_LOGIC;
			carry_out : out STD_LOGIC
		);
	end component;
	signal n1_clk_mod5, n2_clk_mod10, n3_clk_mod10, n4_clk_mod10, n5_clk_mod10, n6_d3, n6_d2, n6_d1, n6_d0, n7_a, n7_b, n7_c, n7_d, n7_e, n7_f, n7_g, n8_sum_0, n8_sum_1, n8_sum_2, n8_sum_3, n8_sum_4, n8_sum_5, n8_sum_6, n8_sum_7, n8_carry_out, n9_o, n10_o, n11_o, n12_o, n17_o, n18_o, n19_o, n20_o, n25_o, n27_o, n28_o, n29_o, n30_o : STD_LOGIC;
begin

	-- combinational logic
	n9_o <= n6_d3 and n8_sum_3;
	n10_o <= n6_d3 and n8_sum_2;
	n11_o <= n6_d3 and n8_sum_1;
	n12_o <= n6_d3 and n8_sum_0;
	n17_o <= n6_d2 and n8_sum_7;
	n18_o <= n6_d2 and n8_sum_6;
	n19_o <= n6_d2 and n8_sum_5;
	n20_o <= n6_d2 and n8_sum_4;
	n25_o <= n6_d1 and n8_carry_out;
	n27_o <= n9_o or n17_o;
	n28_o <= n10_o or n18_o;
	n29_o <= n11_o or n19_o;
	n30_o <= n12_o or n20_o or n25_o;

	-- sub-component instantiations
	u_0_c4085 : mod_5 port map (
		clk => clk,
		clk_mod5 => n1_clk_mod5
	);
	u_1_c4087 : mod_10 port map (
		clk => n1_clk_mod5,
		clk_mod10 => n2_clk_mod10
	);
	u_2_c4089 : mod_10 port map (
		clk => n2_clk_mod10,
		clk_mod10 => n3_clk_mod10
	);
	u_3_c4091 : mod_10 port map (
		clk => n3_clk_mod10,
		clk_mod10 => n4_clk_mod10
	);
	u_4_c4093 : mod_10 port map (
		clk => n4_clk_mod10,
		clk_mod10 => n5_clk_mod10
	);
	u_5_c5025 : digit_selector port map (
		clk => n5_clk_mod10,
		d3 => n6_d3,
		d2 => n6_d2,
		d1 => n6_d1,
		d0 => n6_d0
	);
	u_6_c5045 : hex_7seg port map (
		in1 => n27_o,
		in2 => n28_o,
		in3 => n29_o,
		in4 => n30_o,
		a => n7_a,
		b => n7_b,
		c => n7_c,
		d => n7_d,
		e => n7_e,
		f => n7_f,
		g => n7_g
	);
	u_7_c5434 : fas8 port map (
		lhs_0 => sw11,
		rhs_0 => sw2,
		lhs_1 => sw12,
		rhs_1 => sw4,
		lhs_2 => sw13,
		rhs_2 => sw5,
		lhs_3 => sw15,
		rhs_3 => sw6,
		lhs_4 => sw17,
		rhs_4 => sw7,
		lhs_5 => sw19,
		rhs_5 => sw8,
		lhs_6 => sw21,
		rhs_6 => sw9,
		lhs_7 => sw22,
		rhs_7 => sw10,
		sub => sub,
		sum_0 => n8_sum_0,
		sum_1 => n8_sum_1,
		sum_2 => n8_sum_2,
		sum_3 => n8_sum_3,
		sum_4 => n8_sum_4,
		sum_5 => n8_sum_5,
		sum_6 => n8_sum_6,
		sum_7 => n8_sum_7,
		carry_out => n8_carry_out
	);

	-- output drivers
	a <= n7_a;
	b <= n7_b;
	c <= n7_c;
	d <= n7_d;
	e <= n7_e;
	f <= n7_f;
	g <= n7_g;
	d0 <= n6_d0;
	d1 <= n6_d1;
	d2 <= n6_d2;
	d3 <= n6_d3;

end Behavioral;

-- ============================================================
-- Entity: mod_10
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_10

entity mod_10 is
	Port (
		clk : in	STD_LOGIC;
		clk_mod10 : out STD_LOGIC
	);
end mod_10;

architecture Behavioral of mod_10 is
	signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_q, n4_qn, n12_o, n13_o, n14_o : STD_LOGIC;
begin

	-- combinational logic
	n12_o <= not (n4_q and n13_o and n2_q and n14_o);
	n13_o <= not n3_q;
	n14_o <= not n1_q;

	-- sequential logic (flip-flops)
	process(clk, n12_o)
	begin
		if n12_o = '1' then
			n1_q <= '0';
			n1_qn <= '1';
		elsif rising_edge(clk) then
			if		('1'='0' and '1'='1') then n1_q <= '0'; n1_qn <= '1';
			elsif ('1'='1' and '1'='0') then n1_q <= '1'; n1_qn <= '0';
			elsif ('1'='1' and '1'='1') then n1_q <= not n1_q; n1_qn <= n1_q;
			end if;
		end if;
	end process;
	process(n1_q, n12_o)
	begin
		if n12_o = '1' then
			n2_q <= '0';
			n2_qn <= '1';
		elsif rising_edge(n1_q) then
			if		('1'='0' and '1'='1') then n2_q <= '0'; n2_qn <= '1';
			elsif ('1'='1' and '1'='0') then n2_q <= '1'; n2_qn <= '0';
			elsif ('1'='1' and '1'='1') then n2_q <= not n2_q; n2_qn <= n2_q;
			end if;
		end if;
	end process;
	process(n2_q, n12_o)
	begin
		if n12_o = '1' then
			n3_q <= '0';
			n3_qn <= '1';
		elsif rising_edge(n2_q) then
			if		('1'='0' and '1'='1') then n3_q <= '0'; n3_qn <= '1';
			elsif ('1'='1' and '1'='0') then n3_q <= '1'; n3_qn <= '0';
			elsif ('1'='1' and '1'='1') then n3_q <= not n3_q; n3_qn <= n3_q;
			end if;
		end if;
	end process;
	process(n3_q, n12_o)
	begin
		if n12_o = '1' then
			n4_q <= '0';
			n4_qn <= '1';
		elsif rising_edge(n3_q) then
			if		('1'='0' and '1'='1') then n4_q <= '0'; n4_qn <= '1';
			elsif ('1'='1' and '1'='0') then n4_q <= '1'; n4_qn <= '0';
			elsif ('1'='1' and '1'='1') then n4_q <= not n4_q; n4_qn <= n4_q;
			end if;
		end if;
	end process;

	-- output drivers
	clk_mod10 <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: digit_selector
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: digit_selector

entity digit_selector is
	Port (
		clk : in	STD_LOGIC;
		d3 : out STD_LOGIC;
		d2 : out STD_LOGIC;
		d1 : out STD_LOGIC;
		d0 : out STD_LOGIC
	);
end digit_selector;

architecture Behavioral of digit_selector is
	signal n1_q, n1_qn, n2_q, n2_qn, n6_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o : STD_LOGIC;
begin

	-- combinational logic
	n6_o <= not (n2_q and n1_q);
	n10_o <= not (n2_q and n11_o);
	n11_o <= not n1_q;
	n12_o <= not (n13_o and n1_q);
	n13_o <= not n2_q;
	n14_o <= not (n15_o and n16_o);
	n15_o <= not n2_q;
	n16_o <= not n1_q;

	-- sequential logic (flip-flops)
	process(clk, n6_o)
	begin
		if n6_o = '1' then
			n1_q <= '0';
			n1_qn <= '1';
		elsif rising_edge(clk) then
			if		('1'='0' and '1'='1') then n1_q <= '0'; n1_qn <= '1';
			elsif ('1'='1' and '1'='0') then n1_q <= '1'; n1_qn <= '0';
			elsif ('1'='1' and '1'='1') then n1_q <= not n1_q; n1_qn <= n1_q;
			end if;
		end if;
	end process;
	process(n1_q, n6_o)
	begin
		if n6_o = '1' then
			n2_q <= '0';
			n2_qn <= '1';
		elsif rising_edge(n1_q) then
			if		('1'='0' and '1'='1') then n2_q <= '0'; n2_qn <= '1';
			elsif ('1'='1' and '1'='0') then n2_q <= '1'; n2_qn <= '0';
			elsif ('1'='1' and '1'='1') then n2_q <= not n2_q; n2_qn <= n2_q;
			end if;
		end if;
	end process;

	-- output drivers
	d3 <= n6_o;
	d2 <= n10_o;
	d1 <= n12_o;
	d0 <= n14_o;

end Behavioral;

-- ============================================================
-- Entity: fa1
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: fa1

entity fa1 is
	Port (
		lhs : in	STD_LOGIC;
		rhs : in	STD_LOGIC;
		carry_in : in	STD_LOGIC;
		carry_out : out STD_LOGIC;
		sum : out STD_LOGIC
	);
end fa1;

architecture Behavioral of fa1 is
	signal n1_o, n2_o, n3_o, n4_o, n5_o : STD_LOGIC;
begin

	-- combinational logic
	n1_o <= lhs xor rhs;
	n2_o <= n1_o xor carry_in;
	n3_o <= lhs and rhs;
	n4_o <= n1_o and carry_in;
	n5_o <= n3_o or n4_o;

	-- output drivers
	carry_out <= n5_o;
	sum <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: fas8
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: fas8

entity fas8 is
	Port (
		lhs_0 : in	STD_LOGIC;
		rhs_0 : in	STD_LOGIC;
		lhs_1 : in	STD_LOGIC;
		rhs_1 : in	STD_LOGIC;
		lhs_2 : in	STD_LOGIC;
		rhs_2 : in	STD_LOGIC;
		lhs_3 : in	STD_LOGIC;
		rhs_3 : in	STD_LOGIC;
		lhs_4 : in	STD_LOGIC;
		rhs_4 : in	STD_LOGIC;
		lhs_5 : in	STD_LOGIC;
		rhs_5 : in	STD_LOGIC;
		lhs_6 : in	STD_LOGIC;
		rhs_6 : in	STD_LOGIC;
		lhs_7 : in	STD_LOGIC;
		rhs_7 : in	STD_LOGIC;
		sub : in	STD_LOGIC;
		sum_0 : out STD_LOGIC;
		sum_1 : out STD_LOGIC;
		sum_2 : out STD_LOGIC;
		sum_3 : out STD_LOGIC;
		sum_4 : out STD_LOGIC;
		sum_5 : out STD_LOGIC;
		sum_6 : out STD_LOGIC;
		sum_7 : out STD_LOGIC;
		carry_out : out STD_LOGIC
	);
end fas8;

architecture Behavioral of fas8 is
	component fa1
		Port (
			lhs : in	STD_LOGIC;
			rhs : in	STD_LOGIC;
			carry_in : in	STD_LOGIC;
			carry_out : out STD_LOGIC;
			sum : out STD_LOGIC
		);
	end component;
	signal n1_carry_out, n1_sum, n2_o, n3_carry_out, n3_sum, n4_o, n5_carry_out, n5_sum, n6_o, n7_carry_out, n7_sum, n8_o, n9_carry_out, n9_sum, n10_o, n11_carry_out, n11_sum, n12_o, n13_carry_out, n13_sum, n14_o, n15_carry_out, n15_sum, n16_o : STD_LOGIC;
begin

	-- combinational logic
	n2_o <= sub xor rhs_0;
	n4_o <= sub xor rhs_1;
	n6_o <= sub xor rhs_2;
	n8_o <= sub xor rhs_3;
	n10_o <= sub xor rhs_4;
	n12_o <= sub xor rhs_5;
	n14_o <= sub xor rhs_6;
	n16_o <= sub xor rhs_7;

	-- sub-component instantiations
	u_0_c5272 : fa1 port map (
		lhs => lhs_0,
		rhs => n2_o,
		carry_in => sub,
		carry_out => n1_carry_out,
		sum => n1_sum
	);
	u_1_c5316 : fa1 port map (
		lhs => lhs_1,
		rhs => n4_o,
		carry_in => n1_carry_out,
		carry_out => n3_carry_out,
		sum => n3_sum
	);
	u_2_c5325 : fa1 port map (
		lhs => lhs_2,
		rhs => n6_o,
		carry_in => n3_carry_out,
		carry_out => n5_carry_out,
		sum => n5_sum
	);
	u_3_c5334 : fa1 port map (
		lhs => lhs_3,
		rhs => n8_o,
		carry_in => n5_carry_out,
		carry_out => n7_carry_out,
		sum => n7_sum
	);
	u_4_c5343 : fa1 port map (
		lhs => lhs_4,
		rhs => n10_o,
		carry_in => n7_carry_out,
		carry_out => n9_carry_out,
		sum => n9_sum
	);
	u_5_c5352 : fa1 port map (
		lhs => lhs_5,
		rhs => n12_o,
		carry_in => n9_carry_out,
		carry_out => n11_carry_out,
		sum => n11_sum
	);
	u_6_c5361 : fa1 port map (
		lhs => lhs_6,
		rhs => n14_o,
		carry_in => n11_carry_out,
		carry_out => n13_carry_out,
		sum => n13_sum
	);
	u_7_c5370 : fa1 port map (
		lhs => lhs_7,
		rhs => n16_o,
		carry_in => n13_carry_out,
		carry_out => n15_carry_out,
		sum => n15_sum
	);

	-- output drivers
	sum_0 <= n1_sum;
	sum_1 <= n3_sum;
	sum_2 <= n5_sum;
	sum_3 <= n7_sum;
	sum_4 <= n9_sum;
	sum_5 <= n11_sum;
	sum_6 <= n13_sum;
	sum_7 <= n15_sum;
	carry_out <= n15_carry_out;

end Behavioral;
