-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
	Port (
		sw22 : in	STD_LOGIC;
		sw21 : in	STD_LOGIC;
		sw19 : in	STD_LOGIC;
		sw17 : in	STD_LOGIC;
		a : out STD_LOGIC;
		b : out STD_LOGIC;
		c : out STD_LOGIC;
		d : out STD_LOGIC;
		e : out STD_LOGIC;
		f : out STD_LOGIC;
		g : out STD_LOGIC
	);
end hex_7seg;

architecture Behavioral of hex_7seg is
	signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

	-- combinational logic
	n1_o <= sw22 and sw21 and n40_o and sw17;
	n2_o <= sw22 and n39_o and sw19 and sw17;
	n3_o <= n36_o and sw21 and n37_o and n38_o;
	n4_o <= n33_o and n34_o and n35_o and sw17;
	n5_o <= n4_o or n3_o or n2_o or n1_o;
	n6_o <= sw21 and sw19 and n44_o;
	n7_o <= sw22 and sw19 and sw17;
	n8_o <= sw22 and sw21 and n43_o;
	n9_o <= n41_o and sw21 and n42_o and sw17;
	n10_o <= n9_o or n8_o or n7_o or n6_o;
	n11_o <= sw22 and sw21 and n48_o;
	n12_o <= sw22 and sw21 and sw19;
	n13_o <= n45_o and n46_o and sw19 and n47_o;
	n14_o <= n13_o or n12_o or n11_o;
	n15_o <= sw21 and sw19 and sw17;
	n16_o <= sw22 and n55_o and sw19 and n56_o;
	n17_o <= n52_o and sw21 and n53_o and n54_o;
	n18_o <= n49_o and n50_o and n51_o and sw17;
	n19_o <= n18_o or n17_o or n16_o or n15_o;
	n20_o <= n60_o and n61_o and sw17;
	n21_o <= n59_o and sw17;
	n22_o <= n57_o and sw21 and n58_o;
	n23_o <= n22_o or n21_o or n20_o;
	n24_o <= sw22 and sw21 and n67_o and sw17;
	n25_o <= n66_o and sw19 and sw17;
	n26_o <= n64_o and n65_o and sw17;
	n27_o <= n62_o and n63_o and sw19;
	n28_o <= n27_o or n26_o or n25_o or n24_o;
	n29_o <= sw22 and sw21 and n72_o and n73_o;
	n30_o <= n71_o and sw21 and sw19 and sw17;
	n31_o <= n68_o and n69_o and n70_o;
	n32_o <= n31_o or n30_o or n29_o;
	n33_o <= not sw22;
	n34_o <= not sw21;
	n35_o <= not sw19;
	n36_o <= not sw22;
	n37_o <= not sw19;
	n38_o <= not sw17;
	n39_o <= not sw21;
	n40_o <= not sw19;
	n41_o <= not sw22;
	n42_o <= not sw19;
	n43_o <= not sw17;
	n44_o <= not sw17;
	n45_o <= not sw22;
	n46_o <= not sw21;
	n47_o <= not sw17;
	n48_o <= not sw17;
	n49_o <= not sw22;
	n50_o <= not sw21;
	n51_o <= not sw19;
	n52_o <= not sw22;
	n53_o <= not sw19;
	n54_o <= not sw17;
	n55_o <= not sw21;
	n56_o <= not sw17;
	n57_o <= not sw22;
	n58_o <= not sw19;
	n59_o <= not sw22;
	n60_o <= not sw21;
	n61_o <= not sw19;
	n62_o <= not sw22;
	n63_o <= not sw21;
	n64_o <= not sw22;
	n65_o <= not sw21;
	n66_o <= not sw22;
	n67_o <= not sw19;
	n68_o <= not sw22;
	n69_o <= not sw21;
	n70_o <= not sw19;
	n71_o <= not sw22;
	n72_o <= not sw19;
	n73_o <= not sw17;

	-- output drivers
	a <= n5_o;
	b <= n10_o;
	c <= n14_o;
	d <= n19_o;
	e <= n23_o;
	f <= n28_o;
	g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: mod_5
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_5

entity mod_5 is
	Port (
		clk : in	STD_LOGIC;
		clk_mod5 : out STD_LOGIC
	);
end mod_5;

architecture Behavioral of mod_5 is
	signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_o, n5_o : STD_LOGIC;
begin

	-- combinational logic
	n4_o <= not (n3_q and n5_o and n1_q);
	n5_o <= not n2_q;

	-- sequential logic (flip-flops)
	process(clk, n4_o)
	begin
		if n4_o = '1' then
			n1_q <= '0';
			n1_qn <= '1';
		elsif rising_edge(clk) then
			if		('1'='0' and '1'='1') then n1_q <= '0'; n1_qn <= '1';
			elsif ('1'='1' and '1'='0') then n1_q <= '1'; n1_qn <= '0';
			elsif ('1'='1' and '1'='1') then n1_q <= not n1_q; n1_qn <= n1_q;
			end if;
		end if;
	end process;
	process(n1_q, n4_o)
	begin
		if n4_o = '1' then
			n2_q <= '0';
			n2_qn <= '1';
		elsif rising_edge(n1_q) then
			if		('1'='0' and '1'='1') then n2_q <= '0'; n2_qn <= '1';
			elsif ('1'='1' and '1'='0') then n2_q <= '1'; n2_qn <= '0';
			elsif ('1'='1' and '1'='1') then n2_q <= not n2_q; n2_qn <= n2_q;
			end if;
		end if;
	end process;
	process(n2_q, n4_o)
	begin
		if n4_o = '1' then
			n3_q <= '0';
			n3_qn <= '1';
		elsif rising_edge(n2_q) then
			if		('1'='0' and '1'='1') then n3_q <= '0'; n3_qn <= '1';
			elsif ('1'='1' and '1'='0') then n3_q <= '1'; n3_qn <= '0';
			elsif ('1'='1' and '1'='1') then n3_q <= not n3_q; n3_qn <= n3_q;
			end if;
		end if;
	end process;

	-- output drivers
	clk_mod5 <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: top
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: top

entity top is
	Port (
		clk : in	STD_LOGIC;
		sw22 : in	STD_LOGIC;
		sw21 : in	STD_LOGIC;
		sw19 : in	STD_LOGIC;
		sw17 : in	STD_LOGIC;
		d0 : out STD_LOGIC;
		d1 : out STD_LOGIC;
		d2 : out STD_LOGIC;
		d3 : out STD_LOGIC;
		a : out STD_LOGIC;
		b : out STD_LOGIC;
		c : out STD_LOGIC;
		d : out STD_LOGIC;
		e : out STD_LOGIC;
		f : out STD_LOGIC;
		g : out STD_LOGIC
	);
end top;

architecture Behavioral of top is
	component mod_5
		Port (
			clk : in	STD_LOGIC;
			clk_mod5 : out STD_LOGIC
		);
	end component;
	component mod_10
		Port (
			clk : in	STD_LOGIC;
			clk_mod10 : out STD_LOGIC
		);
	end component;
	component digit_selector
		Port (
			clk : in	STD_LOGIC;
			d3 : out STD_LOGIC;
			d2 : out STD_LOGIC;
			d1 : out STD_LOGIC;
			d0 : out STD_LOGIC
		);
	end component;
	component hex_7seg
		Port (
			sw22 : in	STD_LOGIC;
			sw21 : in	STD_LOGIC;
			sw19 : in	STD_LOGIC;
			sw17 : in	STD_LOGIC;
			a : out STD_LOGIC;
			b : out STD_LOGIC;
			c : out STD_LOGIC;
			d : out STD_LOGIC;
			e : out STD_LOGIC;
			f : out STD_LOGIC;
			g : out STD_LOGIC
		);
	end component;
	signal n1_clk_mod5, n2_clk_mod10, n3_clk_mod10, n4_clk_mod10, n5_clk_mod10, n6_d3, n6_d2, n6_d1, n6_d0, n7_a, n7_b, n7_c, n7_d, n7_e, n7_f, n7_g : STD_LOGIC;
begin

	-- sub-component instantiations
	u_0_c4085 : mod_5 port map (
		clk => clk,
		clk_mod5 => n1_clk_mod5
	);
	u_1_c4087 : mod_10 port map (
		clk => n1_clk_mod5,
		clk_mod10 => n2_clk_mod10
	);
	u_2_c4089 : mod_10 port map (
		clk => n2_clk_mod10,
		clk_mod10 => n3_clk_mod10
	);
	u_3_c4091 : mod_10 port map (
		clk => n3_clk_mod10,
		clk_mod10 => n4_clk_mod10
	);
	u_4_c4093 : mod_10 port map (
		clk => n4_clk_mod10,
		clk_mod10 => n5_clk_mod10
	);
	u_5_c5025 : digit_selector port map (
		clk => n5_clk_mod10,
		d3 => n6_d3,
		d2 => n6_d2,
		d1 => n6_d1,
		d0 => n6_d0
	);
	u_6_c5045 : hex_7seg port map (
		sw22 => sw22,
		sw21 => sw21,
		sw19 => sw19,
		sw17 => sw17,
		a => n7_a,
		b => n7_b,
		c => n7_c,
		d => n7_d,
		e => n7_e,
		f => n7_f,
		g => n7_g
	);

	-- output drivers
	d0 <= n6_d0;
	d1 <= n6_d1;
	d2 <= n6_d2;
	d3 <= n6_d3;
	a <= n7_a;
	b <= n7_b;
	c <= n7_c;
	d <= n7_d;
	e <= n7_e;
	f <= n7_f;
	g <= n7_g;

end Behavioral;

-- ============================================================
-- Entity: mod_10
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_10

entity mod_10 is
	Port (
		clk : in	STD_LOGIC;
		clk_mod10 : out STD_LOGIC
	);
end mod_10;

architecture Behavioral of mod_10 is
	signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_q, n4_qn, n12_o, n13_o, n14_o : STD_LOGIC;
begin

	-- combinational logic
	n12_o <= not (n4_q and n13_o and n2_q and n14_o);
	n13_o <= not n3_q;
	n14_o <= not n1_q;

	-- sequential logic (flip-flops)
	process(clk, n12_o)
	begin
		if n12_o = '1' then
			n1_q <= '0';
			n1_qn <= '1';
		elsif rising_edge(clk) then
			if		('1'='0' and '1'='1') then n1_q <= '0'; n1_qn <= '1';
			elsif ('1'='1' and '1'='0') then n1_q <= '1'; n1_qn <= '0';
			elsif ('1'='1' and '1'='1') then n1_q <= not n1_q; n1_qn <= n1_q;
			end if;
		end if;
	end process;
	process(n1_q, n12_o)
	begin
		if n12_o = '1' then
			n2_q <= '0';
			n2_qn <= '1';
		elsif rising_edge(n1_q) then
			if		('1'='0' and '1'='1') then n2_q <= '0'; n2_qn <= '1';
			elsif ('1'='1' and '1'='0') then n2_q <= '1'; n2_qn <= '0';
			elsif ('1'='1' and '1'='1') then n2_q <= not n2_q; n2_qn <= n2_q;
			end if;
		end if;
	end process;
	process(n2_q, n12_o)
	begin
		if n12_o = '1' then
			n3_q <= '0';
			n3_qn <= '1';
		elsif rising_edge(n2_q) then
			if		('1'='0' and '1'='1') then n3_q <= '0'; n3_qn <= '1';
			elsif ('1'='1' and '1'='0') then n3_q <= '1'; n3_qn <= '0';
			elsif ('1'='1' and '1'='1') then n3_q <= not n3_q; n3_qn <= n3_q;
			end if;
		end if;
	end process;
	process(n3_q, n12_o)
	begin
		if n12_o = '1' then
			n4_q <= '0';
			n4_qn <= '1';
		elsif rising_edge(n3_q) then
			if		('1'='0' and '1'='1') then n4_q <= '0'; n4_qn <= '1';
			elsif ('1'='1' and '1'='0') then n4_q <= '1'; n4_qn <= '0';
			elsif ('1'='1' and '1'='1') then n4_q <= not n4_q; n4_qn <= n4_q;
			end if;
		end if;
	end process;

	-- output drivers
	clk_mod10 <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: digit_selector
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio	(target: Xilinx Spartan-7 / Vivado)
-- Schematic: digit_selector

entity digit_selector is
	Port (
		clk : in	STD_LOGIC;
		d3 : out STD_LOGIC;
		d2 : out STD_LOGIC;
		d1 : out STD_LOGIC;
		d0 : out STD_LOGIC
	);
end digit_selector;

architecture Behavioral of digit_selector is
	signal n1_q, n1_qn, n2_q, n2_qn, n6_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o : STD_LOGIC;
begin

	-- combinational logic
	n6_o <= not (n2_q and n1_q);
	n10_o <= not (n2_q and n11_o);
	n11_o <= not n1_q;
	n12_o <= not (n13_o and n1_q);
	n13_o <= not n2_q;
	n14_o <= not (n15_o and n16_o);
	n15_o <= not n2_q;
	n16_o <= not n1_q;

	-- sequential logic (flip-flops)
	process(clk, n6_o)
	begin
		if n6_o = '1' then
			n1_q <= '0';
			n1_qn <= '1';
		elsif rising_edge(clk) then
			if		('1'='0' and '1'='1') then n1_q <= '0'; n1_qn <= '1';
			elsif ('1'='1' and '1'='0') then n1_q <= '1'; n1_qn <= '0';
			elsif ('1'='1' and '1'='1') then n1_q <= not n1_q; n1_qn <= n1_q;
			end if;
		end if;
	end process;
	process(n1_q, n6_o)
	begin
		if n6_o = '1' then
			n2_q <= '0';
			n2_qn <= '1';
		elsif rising_edge(n1_q) then
			if		('1'='0' and '1'='1') then n2_q <= '0'; n2_qn <= '1';
			elsif ('1'='1' and '1'='0') then n2_q <= '1'; n2_qn <= '0';
			elsif ('1'='1' and '1'='1') then n2_q <= not n2_q; n2_qn <= n2_q;
			end if;
		end if;
	end process;

	-- output drivers
	d3 <= n6_o;
	d2 <= n10_o;
	d1 <= n12_o;
	d0 <= n14_o;

end Behavioral;
