-- ============================================================
-- Entity: and8bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and8bit_1bit

entity and8bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC;
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end and8bit_1bit;

architecture Behavioral of and8bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n16_y and b;
  n2_o <= n17_y and b;
  n3_o <= n18_y and b;
  n4_o <= n19_y and b;
  n5_o <= n20_y and b;
  n6_o <= n21_y and b;
  n7_o <= n22_y and b;
  n8_o <= n23_y and b;
  n16_y <= a(7);
  n17_y <= a(6);
  n18_y <= a(5);
  n19_y <= a(4);
  n20_y <= a(3);
  n21_y <= a(2);
  n22_y <= a(1);
  n23_y <= a(0);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;