library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: initializer

entity initializer is
  Port (
    clk : in  STD_LOGIC;
    initial_0 : out STD_LOGIC;
    initial_1 : out STD_LOGIC
  );
end initializer;

architecture Behavioral of initializer is
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('0')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;

  -- output drivers
  initial_0 <= n1_q;
  initial_1 <= n1_qn;

end Behavioral;
