-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n4_o, n5_o, n7_o, n9_o, n10_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= last_output and n3_qn;
  n5_o <= last_output and n1_q;
  n7_o <= n2_q and n1_q;
  n9_o <= n3_q or n7_o;
  n10_o <= last_output and n9_o;
  n12_o <= last_output and n3_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if (n4_o='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if (n5_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if (n10_o='1') then n3_q <= not n3_q; n3_qn <= not n3_qn; end if;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  component mod5_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod2_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod5_sync port map (
    last_output => n2_mod2_out,
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c10682 : mod2_sync port map (
    last_output => last_output,
    clk => clk,
    mod2_out => n2_mod2_out
  );

  -- output drivers
  mod10_out <= n1_mod5_out;

end Behavioral;

-- ============================================================
-- Entity: mod50m_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50m_sync

entity mod50m_sync is
  Port (
    clk : in  STD_LOGIC;
    clk_mod50m : out STD_LOGIC
  );
end mod50m_sync;

architecture Behavioral of mod50m_sync is
  component mod5_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out, n6_mod10_out, n7_mod10_out, n14_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6957 : mod5_sync port map (
    last_output => STD_LOGIC'('1'),
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c6958 : mod10_sync port map (
    last_output => n1_mod5_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );
  u_2_c6959 : mod10_sync port map (
    last_output => n2_mod10_out,
    clk => clk,
    mod10_out => n3_mod10_out
  );
  u_3_c6960 : mod10_sync port map (
    last_output => n3_mod10_out,
    clk => clk,
    mod10_out => n4_mod10_out
  );
  u_4_c6961 : mod10_sync port map (
    last_output => n4_mod10_out,
    clk => clk,
    mod10_out => n5_mod10_out
  );
  u_5_c6962 : mod10_sync port map (
    last_output => n5_mod10_out,
    clk => clk,
    mod10_out => n6_mod10_out
  );
  u_6_c6963 : mod10_sync port map (
    last_output => n6_mod10_out,
    clk => clk,
    mod10_out => n7_mod10_out
  );
  u_7_c7002 : mod10_sync port map (
    last_output => n7_mod10_out,
    clk => clk,
    mod10_out => n14_mod10_out
  );

  -- output drivers
  clk_mod50m <= n14_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: initializer
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: initializer

entity initializer is
  Port (
    clk : in  STD_LOGIC;
    initial_0 : out STD_LOGIC;
    initial_1 : out STD_LOGIC
  );
end initializer;

architecture Behavioral of initializer is
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('0')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;

  -- output drivers
  initial_0 <= n1_q;
  initial_1 <= n1_qn;

end Behavioral;

-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= last_output and n1_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if (last_output='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: lab8_1
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab8_1

entity lab8_1 is
  Port (
    clk : in  STD_LOGIC;
    e : out STD_LOGIC;
    data : out STD_LOGIC_VECTOR(7 downto 0);
    rs : out STD_LOGIC
  );
end lab8_1;

architecture Behavioral of lab8_1 is
  component lcd_sender
    Port (
      trigger : in  STD_LOGIC;
      rs_in : in  STD_LOGIC;
      data_in : in  STD_LOGIC_VECTOR(7 downto 0);
      clk : in  STD_LOGIC;
      done : out STD_LOGIC;
      rs_out : out STD_LOGIC;
      data_out : out STD_LOGIC_VECTOR(7 downto 0);
      e : out STD_LOGIC
    );
  end component;
  component initializer
    Port (
      clk : in  STD_LOGIC;
      initial_0 : out STD_LOGIC;
      initial_1 : out STD_LOGIC
    );
  end component;
  component or8bit
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC_VECTOR(7 downto 0);
      output : out STD_LOGIC_VECTOR(7 downto 0)
    );
  end component;
  component mod50m_sync
    Port (
      clk : in  STD_LOGIC;
      clk_mod50m : out STD_LOGIC
    );
  end component;
  signal n1_done, n1_rs_out, n1_e, n2_initial_0, n2_initial_1, n3_done, n3_rs_out, n3_e, n32_done, n32_rs_out, n32_e, n47_done, n47_rs_out, n47_e, n62_done, n62_rs_out, n62_e, n77_done, n77_rs_out, n77_e, n92_done, n92_rs_out, n92_e, n107_done, n107_rs_out, n107_e, n122_done, n122_rs_out, n122_e, n137_done, n137_rs_out, n137_e, n150_done, n150_rs_out, n150_e, n167_done, n167_rs_out, n167_e, n182_done, n182_rs_out, n182_e, n197_done, n197_rs_out, n197_e, n212_done, n212_rs_out, n212_e, n227_done, n227_rs_out, n227_e, n369_o, n370_o, n372_o, n373_o, n375_o, n376_o, n378_o, n379_o, n381_o, n382_o, n384_o, n385_o, n387_o, n388_o, n390_o, n391_o, n393_o, n394_o, n396_o, n397_o, n399_o, n400_o, n402_o, n403_o, n405_o, n406_o, n408_o, n409_o, n411_o, n412_o, n414_clk_mod50m : STD_LOGIC;
  signal n1_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x38_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n3_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x0c_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n32_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x06_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n47_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x01_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n62_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x80_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n77_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x48_h_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n92_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x65_e_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n107_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x6c_l_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n122_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x6c_l_data_in_bus_1 : STD_LOGIC_VECTOR(7 downto 0);
  signal n137_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x6f_o_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n150_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x57_w_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n167_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x6f_o_data_in_bus_1 : STD_LOGIC_VECTOR(7 downto 0);
  signal n182_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x20_space_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n197_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x72_r_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n212_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x6c_l_data_in_bus_2 : STD_LOGIC_VECTOR(7 downto 0);
  signal n227_data_out : STD_LOGIC_VECTOR(7 downto 0);
  signal n_0x64_d_data_in_bus : STD_LOGIC_VECTOR(7 downto 0);
  signal n371_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n374_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n377_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n380_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n383_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n386_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n389_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n392_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n395_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n398_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n401_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n404_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n407_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n410_output : STD_LOGIC_VECTOR(7 downto 0);
  signal n413_output : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n369_o <= n1_rs_out or n3_rs_out;
  n370_o <= n1_e or n3_e;
  n372_o <= n369_o or n32_rs_out;
  n373_o <= n370_o or n32_e;
  n375_o <= n372_o or n47_rs_out;
  n376_o <= n373_o or n47_e;
  n378_o <= n375_o or n62_rs_out;
  n379_o <= n376_o or n62_e;
  n381_o <= n378_o or n77_rs_out;
  n382_o <= n379_o or n77_e;
  n384_o <= n381_o or n92_rs_out;
  n385_o <= n382_o or n92_e;
  n387_o <= n384_o or n107_rs_out;
  n388_o <= n385_o or n107_e;
  n390_o <= n387_o or n122_rs_out;
  n391_o <= n388_o or n122_e;
  n393_o <= n390_o or n137_rs_out;
  n394_o <= n391_o or n137_e;
  n396_o <= n393_o or n182_rs_out;
  n397_o <= n394_o or n182_e;
  n399_o <= n396_o or n150_rs_out;
  n400_o <= n397_o or n150_e;
  n402_o <= n399_o or n167_rs_out;
  n403_o <= n400_o or n167_e;
  n405_o <= n402_o or n197_rs_out;
  n406_o <= n403_o or n197_e;
  n408_o <= n405_o or n212_rs_out;
  n409_o <= n406_o or n212_e;
  n411_o <= n408_o or n227_rs_out;
  n412_o <= n409_o or n227_e;

  -- sub-component instantiations
  u_n_0x38 : lcd_sender port map (
    trigger => n2_initial_1,
    rs_in => STD_LOGIC'('0'),
    data_in => n_0x38_data_in_bus,
    clk => clk,
    done => n1_done,
    rs_out => n1_rs_out,
    data_out => n1_data_out,
    e => n1_e
  );
  u_1_c11139 : initializer port map (
    clk => n414_clk_mod50m,
    initial_0 => n2_initial_0,
    initial_1 => n2_initial_1
  );
  u_n_0x0c : lcd_sender port map (
    trigger => n1_done,
    rs_in => STD_LOGIC'('0'),
    data_in => n_0x0c_data_in_bus,
    clk => clk,
    done => n3_done,
    rs_out => n3_rs_out,
    data_out => n3_data_out,
    e => n3_e
  );
  u_n_0x06 : lcd_sender port map (
    trigger => n3_done,
    rs_in => STD_LOGIC'('0'),
    data_in => n_0x06_data_in_bus,
    clk => clk,
    done => n32_done,
    rs_out => n32_rs_out,
    data_out => n32_data_out,
    e => n32_e
  );
  u_n_0x01 : lcd_sender port map (
    trigger => n32_done,
    rs_in => STD_LOGIC'('0'),
    data_in => n_0x01_data_in_bus,
    clk => clk,
    done => n47_done,
    rs_out => n47_rs_out,
    data_out => n47_data_out,
    e => n47_e
  );
  u_n_0x80 : lcd_sender port map (
    trigger => n47_done,
    rs_in => STD_LOGIC'('0'),
    data_in => n_0x80_data_in_bus,
    clk => clk,
    done => n62_done,
    rs_out => n62_rs_out,
    data_out => n62_data_out,
    e => n62_e
  );
  u_n_0x48_h : lcd_sender port map (
    trigger => n62_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x48_h_data_in_bus,
    clk => clk,
    done => n77_done,
    rs_out => n77_rs_out,
    data_out => n77_data_out,
    e => n77_e
  );
  u_n_0x65_e : lcd_sender port map (
    trigger => n77_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x65_e_data_in_bus,
    clk => clk,
    done => n92_done,
    rs_out => n92_rs_out,
    data_out => n92_data_out,
    e => n92_e
  );
  u_n_0x6c_l : lcd_sender port map (
    trigger => n92_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x6c_l_data_in_bus,
    clk => clk,
    done => n107_done,
    rs_out => n107_rs_out,
    data_out => n107_data_out,
    e => n107_e
  );
  u_n_0x6c_l_1 : lcd_sender port map (
    trigger => n107_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x6c_l_data_in_bus_1,
    clk => clk,
    done => n122_done,
    rs_out => n122_rs_out,
    data_out => n122_data_out,
    e => n122_e
  );
  u_n_0x6f_o : lcd_sender port map (
    trigger => n122_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x6f_o_data_in_bus,
    clk => clk,
    done => n137_done,
    rs_out => n137_rs_out,
    data_out => n137_data_out,
    e => n137_e
  );
  u_n_0x57_w : lcd_sender port map (
    trigger => n182_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x57_w_data_in_bus,
    clk => clk,
    done => n150_done,
    rs_out => n150_rs_out,
    data_out => n150_data_out,
    e => n150_e
  );
  u_n_0x6f_o_1 : lcd_sender port map (
    trigger => n150_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x6f_o_data_in_bus_1,
    clk => clk,
    done => n167_done,
    rs_out => n167_rs_out,
    data_out => n167_data_out,
    e => n167_e
  );
  u_n_0x20_space : lcd_sender port map (
    trigger => n137_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x20_space_data_in_bus,
    clk => clk,
    done => n182_done,
    rs_out => n182_rs_out,
    data_out => n182_data_out,
    e => n182_e
  );
  u_n_0x72_r : lcd_sender port map (
    trigger => n167_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x72_r_data_in_bus,
    clk => clk,
    done => n197_done,
    rs_out => n197_rs_out,
    data_out => n197_data_out,
    e => n197_e
  );
  u_n_0x6c_l_2 : lcd_sender port map (
    trigger => n197_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x6c_l_data_in_bus_2,
    clk => clk,
    done => n212_done,
    rs_out => n212_rs_out,
    data_out => n212_data_out,
    e => n212_e
  );
  u_n_0x64_d : lcd_sender port map (
    trigger => n212_done,
    rs_in => STD_LOGIC'('1'),
    data_in => n_0x64_d_data_in_bus,
    clk => clk,
    done => n227_done,
    rs_out => n227_rs_out,
    data_out => n227_data_out,
    e => n227_e
  );
  u_chain_data : or8bit port map (
    a => n1_data_out,
    b => n3_data_out,
    output => n371_output
  );
  u_chain_data_1 : or8bit port map (
    a => n371_output,
    b => n32_data_out,
    output => n374_output
  );
  u_chain_data_2 : or8bit port map (
    a => n374_output,
    b => n47_data_out,
    output => n377_output
  );
  u_chain_data_3 : or8bit port map (
    a => n377_output,
    b => n62_data_out,
    output => n380_output
  );
  u_chain_data_4 : or8bit port map (
    a => n380_output,
    b => n77_data_out,
    output => n383_output
  );
  u_chain_data_5 : or8bit port map (
    a => n383_output,
    b => n92_data_out,
    output => n386_output
  );
  u_chain_data_6 : or8bit port map (
    a => n386_output,
    b => n107_data_out,
    output => n389_output
  );
  u_chain_data_7 : or8bit port map (
    a => n389_output,
    b => n122_data_out,
    output => n392_output
  );
  u_chain_data_8 : or8bit port map (
    a => n392_output,
    b => n137_data_out,
    output => n395_output
  );
  u_chain_data_9 : or8bit port map (
    a => n395_output,
    b => n182_data_out,
    output => n398_output
  );
  u_chain_data_10 : or8bit port map (
    a => n398_output,
    b => n150_data_out,
    output => n401_output
  );
  u_chain_data_11 : or8bit port map (
    a => n401_output,
    b => n167_data_out,
    output => n404_output
  );
  u_chain_data_12 : or8bit port map (
    a => n404_output,
    b => n197_data_out,
    output => n407_output
  );
  u_chain_data_13 : or8bit port map (
    a => n407_output,
    b => n212_data_out,
    output => n410_output
  );
  u_chain_data_14 : or8bit port map (
    a => n410_output,
    b => n227_data_out,
    output => n413_output
  );
  u_32_c14544 : mod50m_sync port map (
    clk => clk,
    clk_mod50m => n414_clk_mod50m
  );

  -- output drivers
  e <= n412_o;
  data <= n413_output;
  rs <= n411_o;
  n_0x38_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x38_data_in_bus(6) <= STD_LOGIC'('0');
  n_0x38_data_in_bus(5) <= STD_LOGIC'('1');
  n_0x38_data_in_bus(4) <= STD_LOGIC'('1');
  n_0x38_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x38_data_in_bus(2) <= STD_LOGIC'('0');
  n_0x38_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x38_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x0c_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x0c_data_in_bus(6) <= STD_LOGIC'('0');
  n_0x0c_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x0c_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x0c_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x0c_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x0c_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x0c_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x06_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x06_data_in_bus(6) <= STD_LOGIC'('0');
  n_0x06_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x06_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x06_data_in_bus(3) <= STD_LOGIC'('0');
  n_0x06_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x06_data_in_bus(1) <= STD_LOGIC'('1');
  n_0x06_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(6) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(3) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(2) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x01_data_in_bus(0) <= STD_LOGIC'('1');
  n_0x80_data_in_bus(7) <= STD_LOGIC'('1');
  n_0x80_data_in_bus(6) <= STD_LOGIC'('0');
  n_0x80_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x80_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x80_data_in_bus(3) <= STD_LOGIC'('0');
  n_0x80_data_in_bus(2) <= STD_LOGIC'('0');
  n_0x80_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x80_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x48_h_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x48_h_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x48_h_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x48_h_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x48_h_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x48_h_data_in_bus(2) <= STD_LOGIC'('0');
  n_0x48_h_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x48_h_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x65_e_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x65_e_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x65_e_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x65_e_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x65_e_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x65_e_data_in_bus(2) <= STD_LOGIC'('0');
  n_0x65_e_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x65_e_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus(5) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_1(7) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_1(6) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_1(5) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_1(4) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_1(3) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_1(2) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_1(1) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_1(0) <= STD_LOGIC'('0');
  n_0x6f_o_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x6f_o_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus(5) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x6f_o_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus(1) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus(0) <= STD_LOGIC'('1');
  n_0x57_w_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x57_w_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x57_w_data_in_bus(5) <= STD_LOGIC'('1');
  n_0x57_w_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x57_w_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x57_w_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x57_w_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x57_w_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x6f_o_data_in_bus_1(7) <= STD_LOGIC'('0');
  n_0x6f_o_data_in_bus_1(6) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus_1(5) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus_1(4) <= STD_LOGIC'('0');
  n_0x6f_o_data_in_bus_1(3) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus_1(2) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus_1(1) <= STD_LOGIC'('1');
  n_0x6f_o_data_in_bus_1(0) <= STD_LOGIC'('1');
  n_0x20_space_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x20_space_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x20_space_data_in_bus(5) <= STD_LOGIC'('1');
  n_0x20_space_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x20_space_data_in_bus(3) <= STD_LOGIC'('1');
  n_0x20_space_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x20_space_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x20_space_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x72_r_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x72_r_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x72_r_data_in_bus(5) <= STD_LOGIC'('0');
  n_0x72_r_data_in_bus(4) <= STD_LOGIC'('1');
  n_0x72_r_data_in_bus(3) <= STD_LOGIC'('0');
  n_0x72_r_data_in_bus(2) <= STD_LOGIC'('0');
  n_0x72_r_data_in_bus(1) <= STD_LOGIC'('1');
  n_0x72_r_data_in_bus(0) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_2(7) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_2(6) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_2(5) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_2(4) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_2(3) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_2(2) <= STD_LOGIC'('1');
  n_0x6c_l_data_in_bus_2(1) <= STD_LOGIC'('0');
  n_0x6c_l_data_in_bus_2(0) <= STD_LOGIC'('0');
  n_0x64_d_data_in_bus(7) <= STD_LOGIC'('0');
  n_0x64_d_data_in_bus(6) <= STD_LOGIC'('1');
  n_0x64_d_data_in_bus(5) <= STD_LOGIC'('1');
  n_0x64_d_data_in_bus(4) <= STD_LOGIC'('0');
  n_0x64_d_data_in_bus(3) <= STD_LOGIC'('0');
  n_0x64_d_data_in_bus(2) <= STD_LOGIC'('1');
  n_0x64_d_data_in_bus(1) <= STD_LOGIC'('0');
  n_0x64_d_data_in_bus(0) <= STD_LOGIC'('0');

end Behavioral;

-- ============================================================
-- Entity: lcd_sender (rewritten — replaces the JK-based version)
-- Same port interface as before, so lab8_1 doesn't need any changes.
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity lcd_sender is
  Port (
    trigger  : in  STD_LOGIC;
    rs_in    : in  STD_LOGIC;
    data_in  : in  STD_LOGIC_VECTOR(7 downto 0);
    clk      : in  STD_LOGIC;
    done     : out STD_LOGIC;
    rs_out   : out STD_LOGIC;
    data_out : out STD_LOGIC_VECTOR(7 downto 0);
    e        : out STD_LOGIC
  );
end lcd_sender;

architecture Behavioral of lcd_sender is
  type state_t is (IDLE, PULSE, WAIT_EXEC, FINISH);
  signal state   : state_t := IDLE;
  signal trig_d  : STD_LOGIC := '0';           -- for rising-edge detect on trigger
  signal cnt     : integer range 0 to 100000 := 0;
  signal e_i     : STD_LOGIC := '0';
  signal done_i  : STD_LOGIC := '0';
  signal rs_reg  : STD_LOGIC := '0';
  signal data_reg: STD_LOGIC_VECTOR(7 downto 0) := (others => '0');

  constant PULSE_CYCLES : integer := 50;      -- ~1us E pulse width (datasheet min tw = 230ns)
  constant WAIT_CYCLES  : integer := 100000;  -- ~2ms execution wait (covers 1.53ms Clear Display)
begin

  process(clk)
  begin
    if rising_edge(clk) then
      trig_d <= trigger;

      case state is
        when IDLE =>
          done_i <= '0';
          e_i    <= '0';
          if trigger = '1' and trig_d = '0' then  -- fire once per trigger edge, not every cycle it's held high
            data_reg <= data_in;
            rs_reg   <= rs_in;
            cnt      <= 0;
            e_i      <= '1';
            state    <= PULSE;
          end if;

        when PULSE =>
          if cnt < PULSE_CYCLES - 1 then
            cnt <= cnt + 1;
          else
            e_i   <= '0';
            cnt   <= 0;
            state <= WAIT_EXEC;
          end if;

        when WAIT_EXEC =>
          if cnt < WAIT_CYCLES - 1 then
            cnt <= cnt + 1;
          else
            done_i <= '1';
            state  <= FINISH;
          end if;

        when FINISH =>
          done_i <= '0';
          state  <= IDLE;
      end case;
    end if;
  end process;

  e        <= e_i;
  done     <= done_i;
  rs_out   <= rs_reg and e_i;                         -- 0 when idle, matching original wired-OR bus behavior
  data_out <= data_reg when e_i = '1' else (others => '0');

end Behavioral;

-- ============================================================
-- Entity: and8bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and8bit_1bit

entity and8bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC;
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end and8bit_1bit;

architecture Behavioral of and8bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n16_y and b;
  n2_o <= n17_y and b;
  n3_o <= n18_y and b;
  n4_o <= n19_y and b;
  n5_o <= n20_y and b;
  n6_o <= n21_y and b;
  n7_o <= n22_y and b;
  n8_o <= n23_y and b;
  n16_y <= a(7);
  n17_y <= a(6);
  n18_y <= a(5);
  n19_y <= a(4);
  n20_y <= a(3);
  n21_y <= a(2);
  n22_y <= a(1);
  n23_y <= a(0);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: or8bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or8bit

entity or8bit is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC_VECTOR(7 downto 0);
    output : out STD_LOGIC_VECTOR(7 downto 0)
  );
end or8bit;

architecture Behavioral of or8bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_y, n10_y, n11_y, n12_y, n13_y, n14_y, n15_y, n16_y, n17_y, n18_y, n19_y, n20_y, n21_y, n22_y, n23_y, n24_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n24_y or n23_y;
  n2_o <= n22_y or n21_y;
  n3_o <= n20_y or n19_y;
  n4_o <= n18_y or n17_y;
  n5_o <= n16_y or n15_y;
  n6_o <= n14_y or n13_y;
  n7_o <= n12_y or n11_y;
  n8_o <= n10_y or n9_y;
  n9_y <= b(0);
  n10_y <= a(0);
  n11_y <= b(1);
  n12_y <= a(1);
  n13_y <= b(2);
  n14_y <= a(2);
  n15_y <= b(3);
  n16_y <= a(3);
  n17_y <= b(4);
  n18_y <= a(4);
  n19_y <= b(5);
  n20_y <= a(5);
  n21_y <= b(6);
  n22_y <= a(6);
  n23_y <= b(7);
  n24_y <= a(7);

  -- output drivers
  output(7) <= n1_o;
  output(6) <= n2_o;
  output(5) <= n3_o;
  output(4) <= n4_o;
  output(3) <= n5_o;
  output(2) <= n6_o;
  output(1) <= n7_o;
  output(0) <= n8_o;

end Behavioral;

-- ============================================================
-- Entity: mod100k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod100k_sync

entity mod100k_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod100k_out : out STD_LOGIC
  );
end mod100k_sync;

architecture Behavioral of mod100k_sync is
  component mod10_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod10_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out, n6_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c14555 : mod10_sync port map (
    last_output => trigger,
    clk => clk,
    mod10_out => n1_mod10_out
  );
  u_1_c14558 : mod10_sync port map (
    last_output => n1_mod10_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );
  u_2_c14559 : mod10_sync port map (
    last_output => n2_mod10_out,
    clk => clk,
    mod10_out => n3_mod10_out
  );
  u_3_c14560 : mod10_sync port map (
    last_output => n3_mod10_out,
    clk => clk,
    mod10_out => n4_mod10_out
  );
  u_4_c14561 : mod10_sync port map (
    last_output => n4_mod10_out,
    clk => clk,
    mod10_out => n5_mod10_out
  );
  u_5_c14562 : mod10_sync port map (
    last_output => n5_mod10_out,
    clk => clk,
    mod10_out => n6_mod10_out
  );

  -- output drivers
  mod100k_out <= n6_mod10_out;

end Behavioral;
