-- ============================================================
-- Entity: mod100_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod100_sync

entity mod100_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod100_out : out STD_LOGIC
  );
end mod100_sync;

architecture Behavioral of mod100_sync is
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod10_out, n2_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod10_sync port map (
    trigger => trigger,
    clk => clk,
    mod10_out => n1_mod10_out
  );
  u_1_c10682 : mod10_sync port map (
    trigger => n1_mod10_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );

  -- output drivers
  mod100_out <= n2_mod10_out;

end Behavioral;