-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= last_output and n1_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if (last_output='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;