-- ============================================================
-- Entity: mod32_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod32_sync

entity mod32_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod32_out : out STD_LOGIC
  );
end mod32_sync;

architecture Behavioral of mod32_sync is
  component mod2_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod2_out, n2_mod2_out, n3_mod2_out, n4_mod2_out, n5_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c14297 : mod2_sync port map (
    last_output => trigger,
    clk => clk,
    mod2_out => n1_mod2_out
  );
  u_1_c14298 : mod2_sync port map (
    last_output => n1_mod2_out,
    clk => clk,
    mod2_out => n2_mod2_out
  );
  u_2_c14299 : mod2_sync port map (
    last_output => n2_mod2_out,
    clk => clk,
    mod2_out => n3_mod2_out
  );
  u_3_c14300 : mod2_sync port map (
    last_output => n3_mod2_out,
    clk => clk,
    mod2_out => n4_mod2_out
  );
  u_4_c14301 : mod2_sync port map (
    last_output => n4_mod2_out,
    clk => clk,
    mod2_out => n5_mod2_out
  );

  -- output drivers
  mod32_out <= n5_mod2_out;

end Behavioral;
