-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n4_o, n5_o, n7_o, n9_o, n10_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n3_qn;
  n5_o <= trigger and n1_q;
  n7_o <= n2_q and n1_q;
  n9_o <= n3_q or n7_o;
  n10_o <= trigger and n9_o;
  n12_o <= trigger and n3_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if (n4_o='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if (n5_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if (n10_o='1') then n3_q <= not n3_q; n3_qn <= not n3_qn; end if;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod2_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod5_sync port map (
    trigger => n2_mod2_out,
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c10682 : mod2_sync port map (
    trigger => trigger,
    clk => clk,
    mod2_out => n2_mod2_out
  );

  -- output drivers
  mod10_out <= n1_mod5_out;

end Behavioral;

-- ============================================================
-- Entity: mod50k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50k_sync

entity mod50k_sync is
  Port (
    clk : in  STD_LOGIC;
    clk_mod50k : out STD_LOGIC
  );
end mod50k_sync;

architecture Behavioral of mod50k_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c9232 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c9233 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );
  u_2_c9234 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    mod10_out => n3_mod10_out
  );
  u_3_c9235 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    mod10_out => n4_mod10_out
  );
  u_4_c9236 : mod10_sync port map (
    trigger => n4_mod10_out,
    clk => clk,
    mod10_out => n5_mod10_out
  );

  -- output drivers
  clk_mod50k <= n5_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= trigger and n1_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;
