-- ============================================================
-- Entity: hex_7seg
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg

entity hex_7seg is
  Port (
    in1_msb : in  STD_LOGIC;
    in2 : in  STD_LOGIC;
    in3 : in  STD_LOGIC;
    in4_lsb : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC
  );
end hex_7seg;

architecture Behavioral of hex_7seg is
  signal n1_o, n2_o, n3_o, n4_o, n5_o, n6_o, n7_o, n8_o, n9_o, n10_o, n11_o, n12_o, n13_o, n14_o, n15_o, n16_o, n17_o, n18_o, n19_o, n20_o, n21_o, n22_o, n23_o, n24_o, n25_o, n26_o, n27_o, n28_o, n29_o, n30_o, n31_o, n32_o, n33_o, n34_o, n35_o, n36_o, n37_o, n38_o, n39_o, n40_o, n41_o, n42_o, n43_o, n44_o, n45_o, n46_o, n47_o, n48_o, n49_o, n50_o, n51_o, n52_o, n53_o, n54_o, n55_o, n56_o, n57_o, n58_o, n59_o, n60_o, n61_o, n62_o, n63_o, n64_o, n65_o, n66_o, n67_o, n68_o, n69_o, n70_o, n71_o, n72_o, n73_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in1_msb and in2 and n40_o and in4_lsb;
  n2_o <= in1_msb and n39_o and in3 and in4_lsb;
  n3_o <= n36_o and in2 and n37_o and n38_o;
  n4_o <= n33_o and n34_o and n35_o and in4_lsb;
  n5_o <= n4_o or n3_o or n2_o or n1_o;
  n6_o <= in2 and in3 and n44_o;
  n7_o <= in1_msb and in3 and in4_lsb;
  n8_o <= in1_msb and in2 and n43_o;
  n9_o <= n41_o and in2 and n42_o and in4_lsb;
  n10_o <= n9_o or n8_o or n7_o or n6_o;
  n11_o <= in1_msb and in2 and n48_o;
  n12_o <= in1_msb and in2 and in3;
  n13_o <= n45_o and n46_o and in3 and n47_o;
  n14_o <= n13_o or n12_o or n11_o;
  n15_o <= in2 and in3 and in4_lsb;
  n16_o <= in1_msb and n55_o and in3 and n56_o;
  n17_o <= n52_o and in2 and n53_o and n54_o;
  n18_o <= n49_o and n50_o and n51_o and in4_lsb;
  n19_o <= n18_o or n17_o or n16_o or n15_o;
  n20_o <= n60_o and n61_o and in4_lsb;
  n21_o <= n59_o and in4_lsb;
  n22_o <= n57_o and in2 and n58_o;
  n23_o <= n22_o or n21_o or n20_o;
  n24_o <= in1_msb and in2 and n67_o and in4_lsb;
  n25_o <= n66_o and in3 and in4_lsb;
  n26_o <= n64_o and n65_o and in4_lsb;
  n27_o <= n62_o and n63_o and in3;
  n28_o <= n27_o or n26_o or n25_o or n24_o;
  n29_o <= in1_msb and in2 and n72_o and n73_o;
  n30_o <= n71_o and in2 and in3 and in4_lsb;
  n31_o <= n68_o and n69_o and n70_o;
  n32_o <= n31_o or n30_o or n29_o;
  n33_o <= not in1_msb;
  n34_o <= not in2;
  n35_o <= not in3;
  n36_o <= not in1_msb;
  n37_o <= not in3;
  n38_o <= not in4_lsb;
  n39_o <= not in2;
  n40_o <= not in3;
  n41_o <= not in1_msb;
  n42_o <= not in3;
  n43_o <= not in4_lsb;
  n44_o <= not in4_lsb;
  n45_o <= not in1_msb;
  n46_o <= not in2;
  n47_o <= not in4_lsb;
  n48_o <= not in4_lsb;
  n49_o <= not in1_msb;
  n50_o <= not in2;
  n51_o <= not in3;
  n52_o <= not in1_msb;
  n53_o <= not in3;
  n54_o <= not in4_lsb;
  n55_o <= not in2;
  n56_o <= not in4_lsb;
  n57_o <= not in1_msb;
  n58_o <= not in3;
  n59_o <= not in1_msb;
  n60_o <= not in2;
  n61_o <= not in3;
  n62_o <= not in1_msb;
  n63_o <= not in2;
  n64_o <= not in1_msb;
  n65_o <= not in2;
  n66_o <= not in1_msb;
  n67_o <= not in3;
  n68_o <= not in1_msb;
  n69_o <= not in2;
  n70_o <= not in3;
  n71_o <= not in1_msb;
  n72_o <= not in3;
  n73_o <= not in4_lsb;

  -- output drivers
  a <= n5_o;
  b <= n10_o;
  c <= n14_o;
  d <= n19_o;
  e <= n23_o;
  f <= n28_o;
  g <= n32_o;

end Behavioral;

-- ============================================================
-- Entity: mod5_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod5_sync

entity mod5_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod5_out : out STD_LOGIC
  );
end mod5_sync;

architecture Behavioral of mod5_sync is
  signal n4_o, n5_o, n7_o, n9_o, n10_o, n12_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= trigger and n3_qn;
  n5_o <= trigger and n1_q;
  n7_o <= n2_q and n1_q;
  n9_o <= n3_q or n7_o;
  n10_o <= trigger and n9_o;
  n12_o <= trigger and n3_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (n4_o='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, reset)
  begin
    if reset = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk) then
      if (n10_o='1') then n3_q <= not n3_q; n3_qn <= not n3_qn; end if;
    end if;
  end process;

  -- output drivers
  mod5_out <= n12_o;

end Behavioral;

-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod2_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod2_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod2_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c10681 : mod5_sync port map (
    trigger => n2_mod2_out,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c10682 : mod2_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod2_out => n2_mod2_out
  );

  -- output drivers
  mod10_out <= n1_mod5_out;

end Behavioral;

-- ============================================================
-- Entity: mod50m_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50m_sync

entity mod50m_sync is
  Port (
    clk : in  STD_LOGIC;
    mod50m_out : out STD_LOGIC
  );
end mod50m_sync;

architecture Behavioral of mod50m_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out, n6_mod10_out, n7_mod10_out, n14_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6957 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n1_mod5_out
  );
  u_1_c6958 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n2_mod10_out
  );
  u_2_c6959 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n3_mod10_out
  );
  u_3_c6960 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n4_mod10_out
  );
  u_4_c6961 : mod10_sync port map (
    trigger => n4_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n5_mod10_out
  );
  u_5_c6962 : mod10_sync port map (
    trigger => n5_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n6_mod10_out
  );
  u_6_c6963 : mod10_sync port map (
    trigger => n6_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n7_mod10_out
  );
  u_7_c7002 : mod10_sync port map (
    trigger => n7_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n14_mod10_out
  );

  -- output drivers
  mod50m_out <= n14_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: debounce_button
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: debounce_button

entity debounce_button is
  Port (
    button_signal : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    debounce_signal : out STD_LOGIC
  );
end debounce_button;

architecture Behavioral of debounce_button is
  component mod50_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod50_out : out STD_LOGIC
    );
  end component;
  signal n7_o, n9_mod50_out : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n6_q : STD_LOGIC := '0';
  signal n6_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n7_o <= n3_q and n6_qn;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n1_q  <= button_signal;
      n1_qn <= not (button_signal);
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n2_q  <= n1_q;
      n2_qn <= not (n1_q);
    end if;
  end process;
  process(clk_50mhz, n2_qn)
  begin
    if n2_qn = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(clk_50mhz) then
      if    (n9_mod50_out='0' and STD_LOGIC'('0')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n9_mod50_out='1' and STD_LOGIC'('0')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n9_mod50_out='1' and STD_LOGIC'('0')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      n6_q  <= n3_q;
      n6_qn <= not (n3_q);
    end if;
  end process;

  -- sub-component instantiations
  u_0_c16763 : mod50_sync port map (
    trigger => clk_1khz,
    clk => clk_50mhz,
    reset => n2_qn,
    mod50_out => n9_mod50_out
  );

  -- output drivers
  debounce_signal <= n7_o;

end Behavioral;

-- ============================================================
-- Entity: mod50k_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50k_sync

entity mod50k_sync is
  Port (
    clk : in  STD_LOGIC;
    mod50k_out : out STD_LOGIC
  );
end mod50k_sync;

architecture Behavioral of mod50k_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c9232 : mod5_sync port map (
    trigger => STD_LOGIC'('1'),
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod5_out => n1_mod5_out
  );
  u_1_c9233 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n2_mod10_out
  );
  u_2_c9234 : mod10_sync port map (
    trigger => n2_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n3_mod10_out
  );
  u_3_c9235 : mod10_sync port map (
    trigger => n3_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n4_mod10_out
  );
  u_4_c9236 : mod10_sync port map (
    trigger => n4_mod10_out,
    clk => clk,
    reset => STD_LOGIC'('0'),
    mod10_out => n5_mod10_out
  );

  -- output drivers
  mod50k_out <= n5_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: mod2_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod2_sync

entity mod2_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod2_out : out STD_LOGIC
  );
end mod2_sync;

architecture Behavioral of mod2_sync is
  signal n2_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= trigger and n1_q;

  -- sequential logic (flip-flops)
  process(clk, reset)
  begin
    if reset = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;

  -- output drivers
  mod2_out <= n2_o;

end Behavioral;

-- ============================================================
-- Entity: hex_7seg_decoder
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: hex_7seg_decoder

entity hex_7seg_decoder is
  Port (
    d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
    d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
    clk_trigger : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    data_out : out STD_LOGIC_VECTOR(3 downto 0);
    d3 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d0 : out STD_LOGIC
  );
end hex_7seg_decoder;

architecture Behavioral of hex_7seg_decoder is
  component and_4bit_1bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC;
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  component or_4bit
    Port (
      a : in  STD_LOGIC_VECTOR(3 downto 0);
      b : in  STD_LOGIC_VECTOR(3 downto 0);
      out_data : out STD_LOGIC_VECTOR(3 downto 0)
    );
  end component;
  signal n4_o, n6_o, n7_o, n8_o, n9_o, n23_o, n24_o, n26_o, n27_o : STD_LOGIC;
  signal n10_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n11_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n12_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n14_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n15_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n16_out_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n4_o <= clk_trigger and n2_q;
  n6_o <= n23_o and n24_o;
  n7_o <= n26_o and n2_q;
  n8_o <= n1_q and n27_o;
  n9_o <= n1_q and n2_q;
  n23_o <= not n1_q;
  n24_o <= not n2_q;
  n26_o <= not n1_q;
  n27_o <= not n2_q;

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if    (n4_o='0' and n4_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (n4_o='1' and n4_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (n4_o='1' and n4_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if    (clk_trigger='0' and clk_trigger='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (clk_trigger='1' and clk_trigger='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (clk_trigger='1' and clk_trigger='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c14777 : and_4bit_1bit port map (
    a => d3_data,
    b => n9_o,
    out_data => n10_out_data
  );
  u_1_c14779 : and_4bit_1bit port map (
    a => d2_data,
    b => n8_o,
    out_data => n11_out_data
  );
  u_2_c14781 : and_4bit_1bit port map (
    a => d1_data,
    b => n7_o,
    out_data => n12_out_data
  );
  u_3_c14783 : and_4bit_1bit port map (
    a => d0_data,
    b => n6_o,
    out_data => n13_out_data
  );
  u_4_c14875 : or_4bit port map (
    a => n11_out_data,
    b => n15_out_data,
    out_data => n14_out_data
  );
  u_5_c14876 : or_4bit port map (
    a => n12_out_data,
    b => n13_out_data,
    out_data => n15_out_data
  );
  u_6_c14877 : or_4bit port map (
    a => n10_out_data,
    b => n14_out_data,
    out_data => n16_out_data
  );

  -- output drivers
  data_out <= n16_out_data;
  d3 <= n6_o;
  d2 <= n7_o;
  d1 <= n8_o;
  d0 <= n9_o;

end Behavioral;

-- ============================================================
-- Entity: and_4bit_1bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: and_4bit_1bit

entity and_4bit_1bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC;
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end and_4bit_1bit;

architecture Behavioral of and_4bit_1bit is
  signal n1_o, n2_o, n3_o, n4_o, n8_y, n9_y, n10_y, n11_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n8_y and b;
  n2_o <= n9_y and b;
  n3_o <= n10_y and b;
  n4_o <= n11_y and b;
  n8_y <= a(3);
  n9_y <= a(2);
  n10_y <= a(1);
  n11_y <= a(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: or_4bit
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: or_4bit

entity or_4bit is
  Port (
    a : in  STD_LOGIC_VECTOR(3 downto 0);
    b : in  STD_LOGIC_VECTOR(3 downto 0);
    out_data : out STD_LOGIC_VECTOR(3 downto 0)
  );
end or_4bit;

architecture Behavioral of or_4bit is
  signal n1_o, n2_o, n3_o, n4_o, n5_y, n6_y, n7_y, n8_y, n9_y, n10_y, n11_y, n12_y : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= n5_y or n6_y;
  n2_o <= n7_y or n8_y;
  n3_o <= n9_y or n10_y;
  n4_o <= n11_y or n12_y;
  n5_y <= a(3);
  n6_y <= b(3);
  n7_y <= a(2);
  n8_y <= b(2);
  n9_y <= a(1);
  n10_y <= b(1);
  n11_y <= a(0);
  n12_y <= b(0);

  -- output drivers
  out_data(3) <= n1_o;
  out_data(2) <= n2_o;
  out_data(1) <= n3_o;
  out_data(0) <= n4_o;

end Behavioral;

-- ============================================================
-- Entity: mod50_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50_sync

entity mod50_sync is
  Port (
    trigger : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    mod50_out : out STD_LOGIC
  );
end mod50_sync;

architecture Behavioral of mod50_sync is
  component mod5_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      trigger : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c16652 : mod5_sync port map (
    trigger => trigger,
    clk => clk,
    reset => reset,
    mod5_out => n1_mod5_out
  );
  u_1_c16653 : mod10_sync port map (
    trigger => n1_mod5_out,
    clk => clk,
    reset => reset,
    mod10_out => n2_mod10_out
  );

  -- output drivers
  mod50_out <= n2_mod10_out;

end Behavioral;

-- ============================================================
-- Entity: lab7
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab7

entity lab7 is
  Port (
    m1 : in  STD_LOGIC_VECTOR(3 downto 0);
    m0 : in  STD_LOGIC_VECTOR(3 downto 0);
    s1 : in  STD_LOGIC_VECTOR(3 downto 0);
    s0 : in  STD_LOGIC_VECTOR(3 downto 0);
    set : in  STD_LOGIC;
    start_stop : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d3 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d0 : out STD_LOGIC;
    error_led : out STD_LOGIC;
    timeup_led : out STD_LOGIC
  );
end lab7;

architecture Behavioral of lab7 is
  component hex_7seg_decoder
    Port (
      d3_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d2_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d1_data : in  STD_LOGIC_VECTOR(3 downto 0);
      d0_data : in  STD_LOGIC_VECTOR(3 downto 0);
      clk_trigger : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      data_out : out STD_LOGIC_VECTOR(3 downto 0);
      d3 : out STD_LOGIC;
      d2 : out STD_LOGIC;
      d1 : out STD_LOGIC;
      d0 : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component mm_ss_counter
    Port (
      trigger : in  STD_LOGIC;
      m1_set : in  STD_LOGIC_VECTOR(3 downto 0);
      m0_set : in  STD_LOGIC_VECTOR(3 downto 0);
      s1_set : in  STD_LOGIC_VECTOR(3 downto 0);
      s0_set : in  STD_LOGIC_VECTOR(3 downto 0);
      set : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      m1_data : out STD_LOGIC_VECTOR(3 downto 0);
      m0_data : out STD_LOGIC_VECTOR(3 downto 0);
      s1_data : out STD_LOGIC_VECTOR(3 downto 0);
      s0_data : out STD_LOGIC_VECTOR(3 downto 0);
      is_zero : out STD_LOGIC
    );
  end component;
  component lab7_set_controller
    Port (
      m1 : in  STD_LOGIC_VECTOR(3 downto 0);
      m0 : in  STD_LOGIC_VECTOR(3 downto 0);
      s1 : in  STD_LOGIC_VECTOR(3 downto 0);
      s0 : in  STD_LOGIC_VECTOR(3 downto 0);
      set_signal : in  STD_LOGIC;
      set : out STD_LOGIC;
      error_flag : out STD_LOGIC
    );
  end component;
  component lab7_button_signal
    Port (
      set : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      start_stop : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      set_signal : out STD_LOGIC;
      reset_signal : out STD_LOGIC;
      start_stop_signal : out STD_LOGIC
    );
  end component;
  component lab7_freq_divider
    Port (
      clk_50mhz : in  STD_LOGIC;
      clk_1hz : out STD_LOGIC;
      clk_1khz : out STD_LOGIC
    );
  end component;
  signal n1_d3, n1_d2, n1_d1, n1_d0, n2_a, n2_b, n2_c, n2_d, n2_e, n2_f, n2_g, n3_y, n4_y, n5_y, n6_y, n11_o, n12_o, n13_is_zero, n15_set, n15_error_flag, n21_set_signal, n21_reset_signal, n21_start_stop_signal, n23_clk_1hz, n23_clk_1khz : STD_LOGIC;
  signal n1_data_out : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_m1_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_m0_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_s1_data : STD_LOGIC_VECTOR(3 downto 0);
  signal n13_s0_data : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- combinational logic
  n3_y <= n1_data_out(3);
  n4_y <= n1_data_out(2);
  n5_y <= n1_data_out(1);
  n6_y <= n1_data_out(0);
  n11_o <= not n13_is_zero;
  n12_o <= n21_start_stop_signal and n23_clk_1hz and n11_o;

  -- sub-component instantiations
  u_0_c17096 : hex_7seg_decoder port map (
    d3_data => n13_m1_data,
    d2_data => n13_m0_data,
    d1_data => n13_s1_data,
    d0_data => n13_s0_data,
    clk_trigger => n23_clk_1khz,
    clk_50mhz => clk,
    data_out => n1_data_out,
    d3 => n1_d3,
    d2 => n1_d2,
    d1 => n1_d1,
    d0 => n1_d0
  );
  u_1_c17097 : hex_7seg port map (
    in1_msb => n3_y,
    in2 => n4_y,
    in3 => n5_y,
    in4_lsb => n6_y,
    a => n2_a,
    b => n2_b,
    c => n2_c,
    d => n2_d,
    e => n2_e,
    f => n2_f,
    g => n2_g
  );
  u_2_c18187 : mm_ss_counter port map (
    trigger => n12_o,
    m1_set => m1,
    m0_set => m0,
    s1_set => s1,
    s0_set => s0,
    set => n15_set,
    reset => n21_reset_signal,
    clk => clk,
    m1_data => n13_m1_data,
    m0_data => n13_m0_data,
    s1_data => n13_s1_data,
    s0_data => n13_s0_data,
    is_zero => n13_is_zero
  );
  u_3_c18466 : lab7_set_controller port map (
    m1 => m1,
    m0 => m0,
    s1 => s1,
    s0 => s0,
    set_signal => n21_set_signal,
    set => n15_set,
    error_flag => n15_error_flag
  );
  u_4_c18562 : lab7_button_signal port map (
    set => set,
    reset => reset,
    start_stop => start_stop,
    clk_1khz => n23_clk_1khz,
    clk_50mhz => clk,
    set_signal => n21_set_signal,
    reset_signal => n21_reset_signal,
    start_stop_signal => n21_start_stop_signal
  );
  u_5_c18597 : lab7_freq_divider port map (
    clk_50mhz => clk,
    clk_1hz => n23_clk_1hz,
    clk_1khz => n23_clk_1khz
  );

  -- output drivers
  a <= n2_a;
  b <= n2_b;
  c <= n2_c;
  d <= n2_d;
  e <= n2_e;
  f <= n2_f;
  g <= n2_g;
  d3 <= n1_d3;
  d2 <= n1_d2;
  d1 <= n1_d1;
  d0 <= n1_d0;
  error_led <= n15_error_flag;
  timeup_led <= n13_is_zero;

end Behavioral;

-- ============================================================
-- Entity: mm_ss_counter
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mm_ss_counter

entity mm_ss_counter is
  Port (
    trigger : in  STD_LOGIC;
    m1_set : in  STD_LOGIC_VECTOR(3 downto 0);
    m0_set : in  STD_LOGIC_VECTOR(3 downto 0);
    s1_set : in  STD_LOGIC_VECTOR(3 downto 0);
    s0_set : in  STD_LOGIC_VECTOR(3 downto 0);
    set : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    m1_data : out STD_LOGIC_VECTOR(3 downto 0);
    m0_data : out STD_LOGIC_VECTOR(3 downto 0);
    s1_data : out STD_LOGIC_VECTOR(3 downto 0);
    s0_data : out STD_LOGIC_VECTOR(3 downto 0);
    is_zero : out STD_LOGIC
  );
end mm_ss_counter;

architecture Behavioral of mm_ss_counter is
  component counter9_0
    Port (
      trigger : in  STD_LOGIC;
      set_data : in  STD_LOGIC_VECTOR(3 downto 0);
      set : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      current : out STD_LOGIC_VECTOR(3 downto 0);
      limit_reach : out STD_LOGIC;
      is_zero : out STD_LOGIC
    );
  end component;
  component counter5_0
    Port (
      trigger : in  STD_LOGIC;
      set_data : in  STD_LOGIC_VECTOR(3 downto 0);
      set : in  STD_LOGIC;
      reset : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      current : out STD_LOGIC_VECTOR(3 downto 0);
      limit_reach : out STD_LOGIC;
      is_zero : out STD_LOGIC
    );
  end component;
  signal n1_o, n2_limit_reach, n2_is_zero, n3_limit_reach, n3_is_zero, n4_limit_reach, n4_is_zero, n5_limit_reach, n5_is_zero : STD_LOGIC;
  signal n2_current : STD_LOGIC_VECTOR(3 downto 0);
  signal n3_current : STD_LOGIC_VECTOR(3 downto 0);
  signal n4_current : STD_LOGIC_VECTOR(3 downto 0);
  signal n5_current : STD_LOGIC_VECTOR(3 downto 0);
begin

  -- combinational logic
  n1_o <= n2_is_zero and n5_is_zero and n3_is_zero and n4_is_zero;

  -- sub-component instantiations
  u_0_c17941 : counter9_0 port map (
    trigger => trigger,
    set_data => s0_set,
    set => set,
    reset => reset,
    clk => clk,
    current => n2_current,
    limit_reach => n2_limit_reach,
    is_zero => n2_is_zero
  );
  u_1_c17956 : counter9_0 port map (
    trigger => n5_limit_reach,
    set_data => m0_set,
    set => set,
    reset => reset,
    clk => clk,
    current => n3_current,
    limit_reach => n3_limit_reach,
    is_zero => n3_is_zero
  );
  u_2_c17957 : counter9_0 port map (
    trigger => n3_limit_reach,
    set_data => m1_set,
    set => set,
    reset => reset,
    clk => clk,
    current => n4_current,
    limit_reach => n4_limit_reach,
    is_zero => n4_is_zero
  );
  u_3_c18117 : counter5_0 port map (
    trigger => n2_limit_reach,
    set_data => s1_set,
    set => set,
    reset => reset,
    clk => clk,
    current => n5_current,
    limit_reach => n5_limit_reach,
    is_zero => n5_is_zero
  );

  -- output drivers
  m1_data <= n4_current;
  m0_data <= n3_current;
  s1_data <= n5_current;
  s0_data <= n2_current;
  is_zero <= n1_o;

end Behavioral;

-- ============================================================
-- Entity: counter9_0
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter9_0

entity counter9_0 is
  Port (
    trigger : in  STD_LOGIC;
    set_data : in  STD_LOGIC_VECTOR(3 downto 0);
    set : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    current : out STD_LOGIC_VECTOR(3 downto 0);
    limit_reach : out STD_LOGIC;
    is_zero : out STD_LOGIC
  );
end counter9_0;

architecture Behavioral of counter9_0 is
  signal n6_o, n8_o, n9_o, n10_o, n11_o, n15_o, n19_y0, n19_y1, n20_o, n21_o, n22_o, n23_o, n31_o, n33_o, n35_o, n37_o, n44_y0, n44_y1, n45_y0, n45_y1, n46_y0, n46_y1, n47_o, n48_o, n57_y, n58_y, n59_y, n60_y : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n6_o <= trigger and n1_qn;
  n8_o <= n6_o and n9_o;
  n9_o <= n4_q or n3_q;
  n10_o <= n6_o and n4_q;
  n11_o <= n6_o and n2_qn;
  n15_o <= n6_o and n3_qn and n2_qn;
  n19_y0 <= set when n57_y = '0' else '0';
  n19_y1 <= set when n57_y = '1' else '0';
  n20_o <= reset or n19_y0;
  n21_o <= reset or n44_y0;
  n22_o <= reset or n45_y0;
  n23_o <= reset or n46_y0;
  n31_o <= n1_q;
  n33_o <= n2_q;
  n35_o <= n3_q;
  n37_o <= n4_q;
  n44_y0 <= set when n58_y = '0' else '0';
  n44_y1 <= set when n58_y = '1' else '0';
  n45_y0 <= set when n59_y = '0' else '0';
  n45_y1 <= set when n59_y = '1' else '0';
  n46_y0 <= set when n60_y = '0' else '0';
  n46_y1 <= set when n60_y = '1' else '0';
  n47_o <= n4_qn and n3_qn and n2_qn and n1_qn;
  n48_o <= trigger and n47_o;
  n57_y <= set_data(0);
  n58_y <= set_data(1);
  n59_y <= set_data(2);
  n60_y <= set_data(3);

  -- sequential logic (flip-flops)
  process(clk, n20_o, n19_y1)
  begin
    if n20_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif n19_y1 = '1' then
      n1_q <= '1';
      n1_qn <= '0';
    elsif rising_edge(clk) then
      if    (trigger='0' and trigger='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (trigger='1' and trigger='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (trigger='1' and trigger='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk, n21_o, n44_y1)
  begin
    if n21_o = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif n44_y1 = '1' then
      n2_q <= '1';
      n2_qn <= '0';
    elsif rising_edge(clk) then
      if    (n8_o='0' and n6_o='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (n8_o='1' and n6_o='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (n8_o='1' and n6_o='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(clk, n22_o, n45_y1)
  begin
    if n22_o = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif n45_y1 = '1' then
      n3_q <= '1';
      n3_qn <= '0';
    elsif rising_edge(clk) then
      if    (n10_o='0' and n11_o='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n10_o='1' and n11_o='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n10_o='1' and n11_o='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk, n23_o, n46_y1)
  begin
    if n23_o = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif n46_y1 = '1' then
      n4_q <= '1';
      n4_qn <= '0';
    elsif rising_edge(clk) then
      if    (n15_o='0' and n6_o='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (n15_o='1' and n6_o='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (n15_o='1' and n6_o='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;

  -- output drivers
  limit_reach <= n48_o;
  is_zero <= n47_o;
  current(0) <= n31_o;
  current(1) <= n33_o;
  current(2) <= n35_o;
  current(3) <= n37_o;

end Behavioral;

-- ============================================================
-- Entity: counter5_0
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter5_0

entity counter5_0 is
  Port (
    trigger : in  STD_LOGIC;
    set_data : in  STD_LOGIC_VECTOR(3 downto 0);
    set : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    current : out STD_LOGIC_VECTOR(3 downto 0);
    limit_reach : out STD_LOGIC;
    is_zero : out STD_LOGIC
  );
end counter5_0;

architecture Behavioral of counter5_0 is
  signal n5_o, n7_o, n9_o, n12_o, n13_o, n16_o, n17_o, n18_o, n24_o, n26_o, n28_o, n34_y0, n34_y1, n35_y, n36_y0, n36_y1, n37_y, n38_y0, n38_y1, n39_y, n44_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n3_q : STD_LOGIC := '0';
  signal n3_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n5_o <= trigger and n1_qn;
  n7_o <= n4_q and n5_o;
  n9_o <= n5_o and n3_qn;
  n12_o <= n4_qn and n3_qn and n1_qn;
  n13_o <= trigger and n12_o;
  n16_o <= reset or n34_y0;
  n17_o <= reset or n36_y0;
  n18_o <= reset or n38_y0;
  n24_o <= n1_q;
  n26_o <= n3_q;
  n28_o <= n4_q;
  n34_y0 <= set when n35_y = '0' else '0';
  n34_y1 <= set when n35_y = '1' else '0';
  n35_y <= set_data(0);
  n36_y0 <= set when n37_y = '0' else '0';
  n36_y1 <= set when n37_y = '1' else '0';
  n37_y <= set_data(1);
  n38_y0 <= set when n39_y = '0' else '0';
  n38_y1 <= set when n39_y = '1' else '0';
  n39_y <= set_data(2);
  n44_o <= STD_LOGIC'('0');

  -- sequential logic (flip-flops)
  process(clk, n16_o, n34_y1)
  begin
    if n16_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif n34_y1 = '1' then
      n1_q <= '1';
      n1_qn <= '0';
    elsif rising_edge(clk) then
      if    (trigger='0' and trigger='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (trigger='1' and trigger='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (trigger='1' and trigger='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk, n17_o, n36_y1)
  begin
    if n17_o = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif n36_y1 = '1' then
      n3_q <= '1';
      n3_qn <= '0';
    elsif rising_edge(clk) then
      if    (n7_o='0' and n5_o='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n7_o='1' and n5_o='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n7_o='1' and n5_o='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk, n18_o, n38_y1)
  begin
    if n18_o = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif n38_y1 = '1' then
      n4_q <= '1';
      n4_qn <= '0';
    elsif rising_edge(clk) then
      if    (n9_o='0' and n5_o='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (n9_o='1' and n5_o='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (n9_o='1' and n5_o='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;

  -- output drivers
  limit_reach <= n13_o;
  is_zero <= n12_o;
  current(0) <= n24_o;
  current(1) <= n26_o;
  current(2) <= n28_o;
  current(3) <= n44_o;

end Behavioral;

-- ============================================================
-- Entity: lab7_set_controller
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab7_set_controller

entity lab7_set_controller is
  Port (
    m1 : in  STD_LOGIC_VECTOR(3 downto 0);
    m0 : in  STD_LOGIC_VECTOR(3 downto 0);
    s1 : in  STD_LOGIC_VECTOR(3 downto 0);
    s0 : in  STD_LOGIC_VECTOR(3 downto 0);
    set_signal : in  STD_LOGIC;
    set : out STD_LOGIC;
    error_flag : out STD_LOGIC
  );
end lab7_set_controller;

architecture Behavioral of lab7_set_controller is
  signal n1_gt, n1_lt, n2_y, n3_y, n4_y, n5_y, n8_gt, n8_lt, n9_y, n10_y, n11_y, n12_y, n15_gt, n15_lt, n16_y, n17_y, n18_y, n19_y, n20_gt, n20_lt, n21_y, n22_y, n23_y, n24_y, n39_o, n40_o, n41_o : STD_LOGIC;
begin

  -- combinational logic
  n1_gt <= '1' when unsigned'(n5_y & n4_y & n3_y & n2_y) > unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n1_lt <= '1' when unsigned'(n5_y & n4_y & n3_y & n2_y) < unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n2_y <= m1(0);
  n3_y <= m1(1);
  n4_y <= m1(2);
  n5_y <= m1(3);
  n8_gt <= '1' when unsigned'(n12_y & n11_y & n10_y & n9_y) > unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n8_lt <= '1' when unsigned'(n12_y & n11_y & n10_y & n9_y) < unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n9_y <= m0(0);
  n10_y <= m0(1);
  n11_y <= m0(2);
  n12_y <= m0(3);
  n15_gt <= '1' when unsigned'(n19_y & n18_y & n17_y & n16_y) > unsigned'(STD_LOGIC'('0') & STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n15_lt <= '1' when unsigned'(n19_y & n18_y & n17_y & n16_y) < unsigned'(STD_LOGIC'('0') & STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n16_y <= s1(0);
  n17_y <= s1(1);
  n18_y <= s1(2);
  n19_y <= s1(3);
  n20_gt <= '1' when unsigned'(n24_y & n23_y & n22_y & n21_y) > unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n20_lt <= '1' when unsigned'(n24_y & n23_y & n22_y & n21_y) < unsigned'(STD_LOGIC'('1') & STD_LOGIC'('0') & STD_LOGIC'('0') & STD_LOGIC'('1')) else '0';
  n21_y <= s0(0);
  n22_y <= s0(1);
  n23_y <= s0(2);
  n24_y <= s0(3);
  n39_o <= n1_gt or n8_gt or n15_gt or n20_gt;
  n40_o <= n41_o and set_signal;
  n41_o <= not n39_o;

  -- output drivers
  set <= n40_o;
  error_flag <= n39_o;

end Behavioral;

-- ============================================================
-- Entity: lab7_button_signal
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab7_button_signal

entity lab7_button_signal is
  Port (
    set : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    start_stop : in  STD_LOGIC;
    clk_1khz : in  STD_LOGIC;
    clk_50mhz : in  STD_LOGIC;
    set_signal : out STD_LOGIC;
    reset_signal : out STD_LOGIC;
    start_stop_signal : out STD_LOGIC
  );
end lab7_button_signal;

architecture Behavioral of lab7_button_signal is
  component debounce_button
    Port (
      button_signal : in  STD_LOGIC;
      clk_50mhz : in  STD_LOGIC;
      clk_1khz : in  STD_LOGIC;
      debounce_signal : out STD_LOGIC
    );
  end component;
  signal n1_debounce_signal, n2_debounce_signal, n3_debounce_signal : STD_LOGIC;
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
begin

  -- sequential logic (flip-flops)
  process(clk_50mhz)
  begin
    if rising_edge(clk_50mhz) then
      if (n3_debounce_signal='1') then n4_q <= not n4_q; n4_qn <= not n4_qn; end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c18523 : debounce_button port map (
    button_signal => set,
    clk_50mhz => clk_50mhz,
    clk_1khz => clk_1khz,
    debounce_signal => n1_debounce_signal
  );
  u_1_c18526 : debounce_button port map (
    button_signal => reset,
    clk_50mhz => clk_50mhz,
    clk_1khz => clk_1khz,
    debounce_signal => n2_debounce_signal
  );
  u_2_c18527 : debounce_button port map (
    button_signal => start_stop,
    clk_50mhz => clk_50mhz,
    clk_1khz => clk_1khz,
    debounce_signal => n3_debounce_signal
  );

  -- output drivers
  set_signal <= n1_debounce_signal;
  reset_signal <= n2_debounce_signal;
  start_stop_signal <= n4_q;

end Behavioral;

-- ============================================================
-- Entity: lab7_freq_divider
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab7_freq_divider

entity lab7_freq_divider is
  Port (
    clk_50mhz : in  STD_LOGIC;
    clk_1hz : out STD_LOGIC;
    clk_1khz : out STD_LOGIC
  );
end lab7_freq_divider;

architecture Behavioral of lab7_freq_divider is
  component mod50m_sync
    Port (
      clk : in  STD_LOGIC;
      mod50m_out : out STD_LOGIC
    );
  end component;
  component mod50k_sync
    Port (
      clk : in  STD_LOGIC;
      mod50k_out : out STD_LOGIC
    );
  end component;
  signal n1_mod50m_out, n2_mod50k_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c18586 : mod50m_sync port map (
    clk => clk_50mhz,
    mod50m_out => n1_mod50m_out
  );
  u_1_c18588 : mod50k_sync port map (
    clk => clk_50mhz,
    mod50k_out => n2_mod50k_out
  );

  -- output drivers
  clk_1hz <= n1_mod50m_out;
  clk_1khz <= n2_mod50k_out;

end Behavioral;
