-- ============================================================
-- Entity: counter_2345679
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter_2345679

entity counter_2345679 is
  Port (
    clk : in  STD_LOGIC;
    q3_msb : out STD_LOGIC;
    q2 : out STD_LOGIC;
    q1 : out STD_LOGIC;
    q0_lsb : out STD_LOGIC
  );
end counter_2345679;

architecture Behavioral of counter_2345679 is
  -- Main counter signals (Uninitialized)
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_q, n4_qn : STD_LOGIC;
  
  -- ONLY the Init-FF is explicitly initialized
  signal n19_q : STD_LOGIC := '0';
  signal n19_qn : STD_LOGIC := '1';
  
  -- Combinational signals
  signal n5_o, n7_o, n12_o : STD_LOGIC;
begin

  -- combinational logic
  n5_o <= n3_qn or n2_qn;
  n7_o <= n1_q and n2_q;
  n12_o <= n1_q and n2_q and n3_q;

  -- sequential logic (flip-flops)
  process(clk)
  begin
    if rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and n5_o='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and n5_o='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and n5_o='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(clk, n19_qn)
  begin
    if n19_qn = '1' then
      n2_q <= '1';
      n2_qn <= '0';
    elsif rising_edge(clk) then
      if    (n1_q='0' and n1_q='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (n1_q='1' and n1_q='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (n1_q='1' and n1_q='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n7_o='0' and n7_o='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n7_o='1' and n7_o='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n7_o='1' and n7_o='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (n12_o='0' and STD_LOGIC'('1')='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (n12_o='1' and STD_LOGIC'('1')='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (n12_o='1' and STD_LOGIC'('1')='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;
  process(clk)
  begin
    if rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('0')='1') then n19_q <= '0'; n19_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='0') then n19_q <= '1'; n19_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('0')='1') then n19_q <= not n19_q; n19_qn <= n19_q;
      end if;
    end if;
  end process;

  -- output drivers
  q3_msb <= n4_q;
  q2 <= n3_q;
  q1 <= n2_q;
  q0_lsb <= n1_q;

end Behavioral;
