----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08/02/2026 09:55:27 PM
-- Design Name: 
-- Module Name: counter_2345679 - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: counter_2345679

entity counter_2345679 is
  Port (
    clk : in  STD_LOGIC;
    q3_msb : out STD_LOGIC;
    q2 : out STD_LOGIC;
    q1 : out STD_LOGIC;
    q0_lsb : out STD_LOGIC
  );
end counter_2345679;

architecture Behavioral of counter_2345679 is
  component mod50m_async
    Port (
      clk : in  STD_LOGIC;
      clk_mod50m : out STD_LOGIC
    );
  end component;
  signal n1_clk_mod50m, n2_q, n2_qn, n3_q, n3_qn, n4_q, n4_qn, n5_q, n5_qn, n6_o, n8_o, n13_o : STD_LOGIC;
begin

  -- combinational logic
  n6_o <= n4_qn or n3_qn;
  n8_o <= n2_q and n3_q;
  n13_o <= n2_q and n3_q and n4_q;

  -- sequential logic (flip-flops)
  process(n1_clk_mod50m)
  begin
    if rising_edge(n1_clk_mod50m) then
      if    (STD_LOGIC'('1')='0' and n6_o='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and n6_o='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and n6_o='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n1_clk_mod50m)
  begin
    if rising_edge(n1_clk_mod50m) then
      if    (n2_q='0' and n2_q='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (n2_q='1' and n2_q='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (n2_q='1' and n2_q='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(n1_clk_mod50m)
  begin
    if rising_edge(n1_clk_mod50m) then
      if    (n8_o='0' and n8_o='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (n8_o='1' and n8_o='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (n8_o='1' and n8_o='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;
  process(n1_clk_mod50m)
  begin
    if rising_edge(n1_clk_mod50m) then
      if    (n13_o='0' and STD_LOGIC'('1')='1') then n5_q <= '0'; n5_qn <= '1';
      elsif (n13_o='1' and STD_LOGIC'('1')='0') then n5_q <= '1'; n5_qn <= '0';
      elsif (n13_o='1' and STD_LOGIC'('1')='1') then n5_q <= not n5_q; n5_qn <= n5_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c6112 : mod50m_async port map (
    clk => clk,
    clk_mod50m => n1_clk_mod50m
  );

  -- output drivers
  q3_msb <= n5_q;
  q2 <= n4_q;
  q1 <= n3_q;
  q0_lsb <= n2_q;

end Behavioral;