----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08/02/2026 09:54:44 PM
-- Design Name: 
-- Module Name: lab5_3 - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab5_3

entity lab5_3 is
  Port (
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab5_3;

architecture Behavioral of lab5_3 is
  component mod50m_async
    Port (
      clk : in  STD_LOGIC;
      clk_mod50m : out STD_LOGIC
    );
  end component;
  component counter_2345679
    Port (
      clk : in  STD_LOGIC;
      q3_msb : out STD_LOGIC;
      q2 : out STD_LOGIC;
      q1 : out STD_LOGIC;
      q0_lsb : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  signal n1_clk_mod50m, n2_q3_msb, n2_q2, n2_q1, n2_q0_lsb, n3_a, n3_b, n3_c, n3_d, n3_e, n3_f, n3_g : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6232 : mod50m_async port map (
    clk => clk,
    clk_mod50m => n1_clk_mod50m
  );
  u_1_c6233 : counter_2345679 port map (
    clk => n1_clk_mod50m,
    q3_msb => n2_q3_msb,
    q2 => n2_q2,
    q1 => n2_q1,
    q0_lsb => n2_q0_lsb
  );
  u_2_c6237 : hex_7seg port map (
    in1_msb => n2_q3_msb,
    in2 => n2_q2,
    in3 => n2_q1,
    in4_lsb => n2_q0_lsb,
    a => n3_a,
    b => n3_b,
    c => n3_c,
    d => n3_d,
    e => n3_e,
    f => n3_f,
    g => n3_g
  );

  -- output drivers
  a <= n3_a;
  b <= n3_b;
  c <= n3_c;
  d <= n3_d;
  e <= n3_e;
  f <= n3_f;
  g <= n3_g;
  d0 <= STD_LOGIC'('1');
  d1 <= STD_LOGIC'('1');
  d2 <= STD_LOGIC'('1');
  d3 <= STD_LOGIC'('1');

end Behavioral;
