-- ============================================================
-- Entity: lab5_3
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab5_3

entity lab5_3 is
  Port (
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab5_3;

architecture Behavioral of lab5_3 is
  component counter_2345679
    Port (
      clk : in  STD_LOGIC;
      q3_msb : out STD_LOGIC;
      q2 : out STD_LOGIC;
      q1 : out STD_LOGIC;
      q0_lsb : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component mod50m_sync
    Port (
      clk : in  STD_LOGIC;
      clk_mod50m : out STD_LOGIC
    );
  end component;
  signal n1_q3_msb, n1_q2, n1_q1, n1_q0_lsb, n2_a, n2_b, n2_c, n2_d, n2_e, n2_f, n2_g, n4_clk_mod50m : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6233 : counter_2345679 port map (
    clk => n4_clk_mod50m,
    q3_msb => n1_q3_msb,
    q2 => n1_q2,
    q1 => n1_q1,
    q0_lsb => n1_q0_lsb
  );
  u_1_c6237 : hex_7seg port map (
    in1_msb => n1_q3_msb,
    in2 => n1_q2,
    in3 => n1_q1,
    in4_lsb => n1_q0_lsb,
    a => n2_a,
    b => n2_b,
    c => n2_c,
    d => n2_d,
    e => n2_e,
    f => n2_f,
    g => n2_g
  );
  u_2_c7040 : mod50m_sync port map (
    clk => clk,
    clk_mod50m => n4_clk_mod50m
  );

  -- output drivers
  a <= n2_a;
  b <= n2_b;
  c <= n2_c;
  d <= n2_d;
  e <= n2_e;
  f <= n2_f;
  g <= n2_g;
  d0 <= STD_LOGIC'('1');
  d1 <= STD_LOGIC'('0');
  d2 <= STD_LOGIC'('0');
  d3 <= STD_LOGIC'('0');

end Behavioral;