----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08/02/2026 05:42:12 PM
-- Design Name: 
-- Module Name: lab5_2 - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab5_2

entity lab5_2 is
  Port (
    clk : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab5_2;

architecture Behavioral of lab5_2 is
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component mod50m_async
    Port (
      clk : in  STD_LOGIC;
      clk_mod50m : out STD_LOGIC
    );
  end component;
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n9_a, n9_b, n9_c, n9_d, n9_e, n9_f, n9_g, n14_clk_mod50m : STD_LOGIC;
begin

  -- sequential logic (flip-flops)
  process(n14_clk_mod50m)
  begin
    if rising_edge(n14_clk_mod50m) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(n1_qn)
  begin
    if rising_edge(n1_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n2_qn)
  begin
    if rising_edge(n2_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;

  -- sub-component instantiations
  u_0_c5850 : hex_7seg port map (
    in1_msb => STD_LOGIC'('0'),
    in2 => n3_q,
    in3 => n2_q,
    in4_lsb => n1_q,
    a => n9_a,
    b => n9_b,
    c => n9_c,
    d => n9_d,
    e => n9_e,
    f => n9_f,
    g => n9_g
  );
  u_1_c6109 : mod50m_async port map (
    clk => clk,
    clk_mod50m => n14_clk_mod50m
  );

  -- output drivers
  a <= n9_a;
  b <= n9_b;
  c <= n9_c;
  d <= n9_d;
  e <= n9_e;
  f <= n9_f;
  g <= n9_g;
  d0 <= STD_LOGIC'('0');
  d1 <= STD_LOGIC'('0');
  d2 <= STD_LOGIC'('0');
  d3 <= STD_LOGIC'('1');

end Behavioral;