-- ============================================================
-- Entity: mod10_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod10_sync

entity mod10_sync is
  Port (
    last_output : in  STD_LOGIC;
    clk : in  STD_LOGIC;
    mod10_out : out STD_LOGIC
  );
end mod10_sync;

architecture Behavioral of mod10_sync is
  signal n3_o, n6_o, n11_o, n17_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n2_q : STD_LOGIC := '0';
  signal n2_qn : STD_LOGIC := '1';
  signal n5_q : STD_LOGIC := '0';
  signal n5_qn : STD_LOGIC := '1';
  signal n10_q : STD_LOGIC := '0';
  signal n10_qn : STD_LOGIC := '1';
  signal n18_q : STD_LOGIC := '0';
  signal n18_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n3_o <= last_output and n1_q;
  n6_o <= n3_o and n2_q;
  n11_o <= n6_o and n5_q;
  n17_o <= n10_q and n5_qn and n2_q and n1_qn;

  -- sequential logic (flip-flops)
  process(clk, n18_q)
  begin
    if n18_q = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (last_output='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, n18_q)
  begin
    if n18_q = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(clk) then
      if (n3_o='1') then n2_q <= not n2_q; n2_qn <= not n2_qn; end if;
    end if;
  end process;
  process(clk, n18_q)
  begin
    if n18_q = '1' then
      n5_q <= '0';
      n5_qn <= '1';
    elsif rising_edge(clk) then
      if (n6_o='1') then n5_q <= not n5_q; n5_qn <= not n5_qn; end if;
    end if;
  end process;
  process(clk, n18_q)
  begin
    if n18_q = '1' then
      n10_q <= '0';
      n10_qn <= '1';
    elsif rising_edge(clk) then
      if (n11_o='1') then n10_q <= not n10_q; n10_qn <= not n10_qn; end if;
    end if;
  end process;
  process(clk, n18_q)
  begin
    if n18_q = '1' then
      n18_q  <= '0';
      n18_qn <= '1';
    elsif rising_edge(clk) then
      n18_q  <= n17_o;
      n18_qn <= not (n17_o);
    end if;
  end process;

  -- output drivers
  mod10_out <= n17_o;

end Behavioral;
