----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08/02/2026 09:55:00 PM
-- Design Name: 
-- Module Name: mod50m_async - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50m_async

entity mod50m_async is
  Port (
    clk : in  STD_LOGIC;
    clk_mod50m : out STD_LOGIC
  );
end mod50m_async;

architecture Behavioral of mod50m_async is
  component mod_5
    Port (
      clk : in  STD_LOGIC;
      clk_mod5 : out STD_LOGIC
    );
  end component;
  component mod_10
    Port (
      clk : in  STD_LOGIC;
      clk_mod10 : out STD_LOGIC
    );
  end component;
  signal n1_clk_mod5, n2_clk_mod10, n3_clk_mod10, n4_clk_mod10, n5_clk_mod10, n6_clk_mod10, n7_clk_mod10, n8_clk_mod10 : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6091 : mod_5 port map (
    clk => clk,
    clk_mod5 => n1_clk_mod5
  );
  u_1_c6092 : mod_10 port map (
    clk => n8_clk_mod10,
    clk_mod10 => n2_clk_mod10
  );
  u_2_c6093 : mod_10 port map (
    clk => n7_clk_mod10,
    clk_mod10 => n3_clk_mod10
  );
  u_3_c6094 : mod_10 port map (
    clk => n1_clk_mod5,
    clk_mod10 => n4_clk_mod10
  );
  u_4_c6095 : mod_10 port map (
    clk => n4_clk_mod10,
    clk_mod10 => n5_clk_mod10
  );
  u_5_c6096 : mod_10 port map (
    clk => n5_clk_mod10,
    clk_mod10 => n6_clk_mod10
  );
  u_6_c6097 : mod_10 port map (
    clk => n6_clk_mod10,
    clk_mod10 => n7_clk_mod10
  );
  u_7_c6098 : mod_10 port map (
    clk => n3_clk_mod10,
    clk_mod10 => n8_clk_mod10
  );

  -- output drivers
  clk_mod50m <= n2_clk_mod10;

end Behavioral;