-- ============================================================
-- Entity: mod50m_sync
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod50m_sync

entity mod50m_sync is
  Port (
    clk : in  STD_LOGIC;
    clk_mod50m : out STD_LOGIC
  );
end mod50m_sync;

architecture Behavioral of mod50m_sync is
  component mod5_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod5_out : out STD_LOGIC
    );
  end component;
  component mod10_sync
    Port (
      last_output : in  STD_LOGIC;
      clk : in  STD_LOGIC;
      mod10_out : out STD_LOGIC
    );
  end component;
  signal n1_mod5_out, n2_mod10_out, n3_mod10_out, n4_mod10_out, n5_mod10_out, n6_mod10_out, n7_mod10_out, n14_mod10_out : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c6957 : mod5_sync port map (
    last_output => STD_LOGIC'('1'),
    clk => clk,
    mod5_out => n1_mod5_out
  );
  u_1_c6958 : mod10_sync port map (
    last_output => n1_mod5_out,
    clk => clk,
    mod10_out => n2_mod10_out
  );
  u_2_c6959 : mod10_sync port map (
    last_output => n2_mod10_out,
    clk => clk,
    mod10_out => n3_mod10_out
  );
  u_3_c6960 : mod10_sync port map (
    last_output => n3_mod10_out,
    clk => clk,
    mod10_out => n4_mod10_out
  );
  u_4_c6961 : mod10_sync port map (
    last_output => n4_mod10_out,
    clk => clk,
    mod10_out => n5_mod10_out
  );
  u_5_c6962 : mod10_sync port map (
    last_output => n5_mod10_out,
    clk => clk,
    mod10_out => n6_mod10_out
  );
  u_6_c6963 : mod10_sync port map (
    last_output => n6_mod10_out,
    clk => clk,
    mod10_out => n7_mod10_out
  );
  u_7_c7002 : mod10_sync port map (
    last_output => n7_mod10_out,
    clk => clk,
    mod10_out => n14_mod10_out
  );

  -- output drivers
  clk_mod50m <= n14_mod10_out;

end Behavioral;
