----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08/02/2026 05:40:44 PM
-- Design Name: 
-- Module Name: mod_10 - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_10

entity mod_10 is
  Port (
    clk : in  STD_LOGIC;
    clk_mod10 : out STD_LOGIC
  );
end mod_10;

architecture Behavioral of mod_10 is
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_q, n4_qn, n12_o, n13_o, n18_o : STD_LOGIC;
begin

  -- combinational logic
  n12_o <= not n3_q;
  n13_o <= not n1_q;
  n18_o <= n4_q and n12_o and n2_q and n13_o;

  -- sequential logic (flip-flops)
  process(clk, n18_o)
  begin
    if n18_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(n1_qn, n18_o)
  begin
    if n18_o = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(n1_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n2_qn, n18_o)
  begin
    if n18_o = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(n2_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;
  process(n3_qn, n18_o)
  begin
    if n18_o = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif rising_edge(n3_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n4_q <= '0'; n4_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n4_q <= '1'; n4_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n4_q <= not n4_q; n4_qn <= n4_q;
      end if;
    end if;
  end process;

  -- output drivers
  clk_mod10 <= n18_o;

end Behavioral;