----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08/02/2026 05:40:32 PM
-- Design Name: 
-- Module Name: mod_5 - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mod_5

entity mod_5 is
  Port (
    clk : in  STD_LOGIC;
    clk_mod5 : out STD_LOGIC
  );
end mod_5;

architecture Behavioral of mod_5 is
  signal n1_q, n1_qn, n2_q, n2_qn, n3_q, n3_qn, n4_o, n11_o : STD_LOGIC;
begin

  -- combinational logic
  n4_o <= not n2_q;
  n11_o <= n3_q and n4_o and n1_q;

  -- sequential logic (flip-flops)
  process(clk, n11_o)
  begin
    if n11_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n1_q <= '0'; n1_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n1_q <= '1'; n1_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n1_q <= not n1_q; n1_qn <= n1_q;
      end if;
    end if;
  end process;
  process(n1_qn, n11_o)
  begin
    if n11_o = '1' then
      n2_q <= '0';
      n2_qn <= '1';
    elsif rising_edge(n1_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n2_q <= '0'; n2_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n2_q <= '1'; n2_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n2_q <= not n2_q; n2_qn <= n2_q;
      end if;
    end if;
  end process;
  process(n2_qn, n11_o)
  begin
    if n11_o = '1' then
      n3_q <= '0';
      n3_qn <= '1';
    elsif rising_edge(n2_qn) then
      if    (STD_LOGIC'('1')='0' and STD_LOGIC'('1')='1') then n3_q <= '0'; n3_qn <= '1';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='0') then n3_q <= '1'; n3_qn <= '0';
      elsif (STD_LOGIC'('1')='1' and STD_LOGIC'('1')='1') then n3_q <= not n3_q; n3_qn <= n3_q;
      end if;
    end if;
  end process;

  -- output drivers
  clk_mod5 <= n11_o;

end Behavioral;