-- ============================================================
-- Entity: n_8_bits_sync_counter_with_target
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: n_8_bits_sync_counter_with_target

entity n_8_bits_sync_counter_with_target is
  Port (
    trigger : in  STD_LOGIC;
    target : in  STD_LOGIC_VECTOR(7 downto 0);
    clk : in  STD_LOGIC;
    reset : in  STD_LOGIC;
    overflow : out STD_LOGIC;
    limit_reached : out STD_LOGIC;
    counting : out STD_LOGIC;
    data_out : out STD_LOGIC_VECTOR(7 downto 0)
  );
end n_8_bits_sync_counter_with_target;

architecture Behavioral of n_8_bits_sync_counter_with_target is
  component n_8_bits_comparator
    Port (
      a : in  STD_LOGIC_VECTOR(7 downto 0);
      b : in  STD_LOGIC_VECTOR(7 downto 0);
      eq : out STD_LOGIC;
      gt : out STD_LOGIC;
      lt : out STD_LOGIC
    );
  end component;
  signal n2_o, n5_o, n8_o, n10_o, n12_o, n14_o, n16_o, n23_eq, n23_gt, n23_lt, n39_o : STD_LOGIC;
  signal n1_q : STD_LOGIC := '0';
  signal n1_qn : STD_LOGIC := '1';
  signal n4_q : STD_LOGIC := '0';
  signal n4_qn : STD_LOGIC := '1';
  signal n7_q : STD_LOGIC := '0';
  signal n7_qn : STD_LOGIC := '1';
  signal n9_q : STD_LOGIC := '0';
  signal n9_qn : STD_LOGIC := '1';
  signal n11_q : STD_LOGIC := '0';
  signal n11_qn : STD_LOGIC := '1';
  signal n13_q : STD_LOGIC := '0';
  signal n13_qn : STD_LOGIC := '1';
  signal n15_q : STD_LOGIC := '0';
  signal n15_qn : STD_LOGIC := '1';
  signal n17_q : STD_LOGIC := '0';
  signal n17_qn : STD_LOGIC := '1';
  signal n37_q : STD_LOGIC := '0';
  signal n37_qn : STD_LOGIC := '1';
begin

  -- combinational logic
  n2_o <= trigger and n1_q;
  n5_o <= n2_o and n4_q;
  n8_o <= n5_o and n7_q;
  n10_o <= n8_o and n9_q;
  n12_o <= n10_o and n11_q;
  n14_o <= n12_o and n13_q;
  n16_o <= n14_o and n15_q;
  n39_o <= n37_q or reset;

  -- sequential logic (flip-flops)
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n1_q <= '0';
      n1_qn <= '1';
    elsif rising_edge(clk) then
      if (trigger='1') then n1_q <= not n1_q; n1_qn <= not n1_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n4_q <= '0';
      n4_qn <= '1';
    elsif rising_edge(clk) then
      if (n2_o='1') then n4_q <= not n4_q; n4_qn <= not n4_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n7_q <= '0';
      n7_qn <= '1';
    elsif rising_edge(clk) then
      if (n5_o='1') then n7_q <= not n7_q; n7_qn <= not n7_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n9_q <= '0';
      n9_qn <= '1';
    elsif rising_edge(clk) then
      if (n8_o='1') then n9_q <= not n9_q; n9_qn <= not n9_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n11_q <= '0';
      n11_qn <= '1';
    elsif rising_edge(clk) then
      if (n10_o='1') then n11_q <= not n11_q; n11_qn <= not n11_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n13_q <= '0';
      n13_qn <= '1';
    elsif rising_edge(clk) then
      if (n12_o='1') then n13_q <= not n13_q; n13_qn <= not n13_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n15_q <= '0';
      n15_qn <= '1';
    elsif rising_edge(clk) then
      if (n14_o='1') then n15_q <= not n15_q; n15_qn <= not n15_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n17_q <= '0';
      n17_qn <= '1';
    elsif rising_edge(clk) then
      if (n16_o='1') then n17_q <= not n17_q; n17_qn <= not n17_qn; end if;
    end if;
  end process;
  process(clk, n39_o)
  begin
    if n39_o = '1' then
      n37_q  <= '0';
      n37_qn <= '1';
    elsif rising_edge(clk) then
      n37_q  <= n23_eq;
      n37_qn <= not (n23_eq);
    end if;
  end process;

  -- sub-component instantiations
  u_0_c6776 : n_8_bits_comparator port map (
    a => target,
    b => (others => '0'),
    eq => n23_eq,
    gt => n23_gt,
    lt => n23_lt
  );

  -- output drivers
  overflow <= n23_gt;
  limit_reached <= n23_eq;
  counting <= n23_lt;
  data_out(0) <= n1_q;
  data_out(1) <= n4_q;
  data_out(2) <= n7_q;
  data_out(3) <= n9_q;
  data_out(4) <= n11_q;
  data_out(5) <= n13_q;
  data_out(6) <= n15_q;
  data_out(7) <= n17_q;

end Behavioral;

-- ============================================================
-- Entity: n_8_bits_comparator
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: n_8_bits_comparator

entity n_8_bits_comparator is
  Port (
    a : in  STD_LOGIC_VECTOR(7 downto 0);
    b : in  STD_LOGIC_VECTOR(7 downto 0);
    eq : out STD_LOGIC;
    gt : out STD_LOGIC;
    lt : out STD_LOGIC
  );
end n_8_bits_comparator;

architecture Behavioral of n_8_bits_comparator is
  signal n1_eq, n2_gt, n2_lt : STD_LOGIC;
begin

  -- combinational logic
  n1_eq <= '1' when a = b else '0';
  n2_gt <= '1' when unsigned(a) > unsigned(b) else '0';
  n2_lt <= '1' when unsigned(a) < unsigned(b) else '0';

  -- output drivers
  eq <= n1_eq;
  gt <= n2_gt;
  lt <= n2_lt;

end Behavioral;