----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 07/28/2026 09:40:11 PM
-- Design Name: 
-- Module Name: fas8 - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: fas8

entity fas8 is
  Port (
    lhs_0_lsb : in  STD_LOGIC;
    rhs_0_lsb : in  STD_LOGIC;
    lhs_1 : in  STD_LOGIC;
    rhs_1 : in  STD_LOGIC;
    lhs_2 : in  STD_LOGIC;
    rhs_2 : in  STD_LOGIC;
    lhs_3 : in  STD_LOGIC;
    rhs_3 : in  STD_LOGIC;
    lhs_4 : in  STD_LOGIC;
    rhs_4 : in  STD_LOGIC;
    lhs_5 : in  STD_LOGIC;
    rhs_5 : in  STD_LOGIC;
    lhs_6 : in  STD_LOGIC;
    rhs_6 : in  STD_LOGIC;
    lhs_7_msb : in  STD_LOGIC;
    rhs_7_msb : in  STD_LOGIC;
    sub : in  STD_LOGIC;
    sum_0 : out STD_LOGIC;
    sum_1 : out STD_LOGIC;
    sum_2 : out STD_LOGIC;
    sum_3 : out STD_LOGIC;
    sum_4 : out STD_LOGIC;
    sum_5 : out STD_LOGIC;
    sum_6 : out STD_LOGIC;
    sum_7 : out STD_LOGIC;
    carry_out : out STD_LOGIC
  );
end fas8;

architecture Behavioral of fas8 is
  component fa1
    Port (
      lhs : in  STD_LOGIC;
      rhs : in  STD_LOGIC;
      carry_in : in  STD_LOGIC;
      carry_out : out STD_LOGIC;
      sum : out STD_LOGIC
    );
  end component;
  signal n1_carry_out, n1_sum, n2_o, n3_carry_out, n3_sum, n4_o, n5_carry_out, n5_sum, n6_o, n7_carry_out, n7_sum, n8_o, n9_carry_out, n9_sum, n10_o, n11_carry_out, n11_sum, n12_o, n13_carry_out, n13_sum, n14_o, n15_carry_out, n15_sum, n16_o : STD_LOGIC;
begin

  -- combinational logic
  n2_o <= sub xor rhs_0_lsb;
  n4_o <= sub xor rhs_1;
  n6_o <= sub xor rhs_2;
  n8_o <= sub xor rhs_3;
  n10_o <= sub xor rhs_4;
  n12_o <= sub xor rhs_5;
  n14_o <= sub xor rhs_6;
  n16_o <= sub xor rhs_7_msb;

  -- sub-component instantiations
  u_0_c5272 : fa1 port map (
    lhs => lhs_0_lsb,
    rhs => n2_o,
    carry_in => sub,
    carry_out => n1_carry_out,
    sum => n1_sum
  );
  u_1_c5316 : fa1 port map (
    lhs => lhs_1,
    rhs => n4_o,
    carry_in => n1_carry_out,
    carry_out => n3_carry_out,
    sum => n3_sum
  );
  u_2_c5325 : fa1 port map (
    lhs => lhs_2,
    rhs => n6_o,
    carry_in => n3_carry_out,
    carry_out => n5_carry_out,
    sum => n5_sum
  );
  u_3_c5334 : fa1 port map (
    lhs => lhs_3,
    rhs => n8_o,
    carry_in => n5_carry_out,
    carry_out => n7_carry_out,
    sum => n7_sum
  );
  u_4_c5343 : fa1 port map (
    lhs => lhs_4,
    rhs => n10_o,
    carry_in => n7_carry_out,
    carry_out => n9_carry_out,
    sum => n9_sum
  );
  u_5_c5352 : fa1 port map (
    lhs => lhs_5,
    rhs => n12_o,
    carry_in => n9_carry_out,
    carry_out => n11_carry_out,
    sum => n11_sum
  );
  u_6_c5361 : fa1 port map (
    lhs => lhs_6,
    rhs => n14_o,
    carry_in => n11_carry_out,
    carry_out => n13_carry_out,
    sum => n13_sum
  );
  u_7_c5370 : fa1 port map (
    lhs => lhs_7_msb,
    rhs => n16_o,
    carry_in => n13_carry_out,
    carry_out => n15_carry_out,
    sum => n15_sum
  );

  -- output drivers
  sum_0 <= n1_sum;
  sum_1 <= n3_sum;
  sum_2 <= n5_sum;
  sum_3 <= n7_sum;
  sum_4 <= n9_sum;
  sum_5 <= n11_sum;
  sum_6 <= n13_sum;
  sum_7 <= n15_sum;
  carry_out <= n15_carry_out;

end Behavioral;