----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 07/28/2026 04:02:46 PM
-- Design Name: 
-- Module Name: top - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: Testing multiplexing by routing anodes to hex decoder
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: lab4

entity lab4 is
  Port (
    clk : in  STD_LOGIC;
    sw22 : in  STD_LOGIC;
    sw10 : in  STD_LOGIC;
    sw21 : in  STD_LOGIC;
    sw9 : in  STD_LOGIC;
    sw19 : in  STD_LOGIC;
    sw8 : in  STD_LOGIC;
    sw17 : in  STD_LOGIC;
    sw7 : in  STD_LOGIC;
    sw15 : in  STD_LOGIC;
    sw6 : in  STD_LOGIC;
    sw13 : in  STD_LOGIC;
    sw5 : in  STD_LOGIC;
    sw12 : in  STD_LOGIC;
    sw4 : in  STD_LOGIC;
    sw11 : in  STD_LOGIC;
    sw2 : in  STD_LOGIC;
    sub : in  STD_LOGIC;
    a : out STD_LOGIC;
    b : out STD_LOGIC;
    c : out STD_LOGIC;
    d : out STD_LOGIC;
    e : out STD_LOGIC;
    f : out STD_LOGIC;
    g : out STD_LOGIC;
    d0 : out STD_LOGIC;
    d1 : out STD_LOGIC;
    d2 : out STD_LOGIC;
    d3 : out STD_LOGIC
  );
end lab4;

architecture Behavioral of lab4 is
  component mod_5
    Port (
      clk : in  STD_LOGIC;
      clk_mod5 : out STD_LOGIC
    );
  end component;
  component mod_10
    Port (
      clk : in  STD_LOGIC;
      clk_mod10 : out STD_LOGIC
    );
  end component;
  component digit_selector
    Port (
      clk : in  STD_LOGIC;
      d3 : out STD_LOGIC;
      d2 : out STD_LOGIC;
      d1 : out STD_LOGIC;
      d0 : out STD_LOGIC
    );
  end component;
  component hex_7seg
    Port (
      in1_msb : in  STD_LOGIC;
      in2 : in  STD_LOGIC;
      in3 : in  STD_LOGIC;
      in4_lsb : in  STD_LOGIC;
      a : out STD_LOGIC;
      b : out STD_LOGIC;
      c : out STD_LOGIC;
      d : out STD_LOGIC;
      e : out STD_LOGIC;
      f : out STD_LOGIC;
      g : out STD_LOGIC
    );
  end component;
  component fas8
    Port (
      lhs_0_lsb : in  STD_LOGIC;
      rhs_0_lsb : in  STD_LOGIC;
      lhs_1 : in  STD_LOGIC;
      rhs_1 : in  STD_LOGIC;
      lhs_2 : in  STD_LOGIC;
      rhs_2 : in  STD_LOGIC;
      lhs_3 : in  STD_LOGIC;
      rhs_3 : in  STD_LOGIC;
      lhs_4 : in  STD_LOGIC;
      rhs_4 : in  STD_LOGIC;
      lhs_5 : in  STD_LOGIC;
      rhs_5 : in  STD_LOGIC;
      lhs_6 : in  STD_LOGIC;
      rhs_6 : in  STD_LOGIC;
      lhs_7_msb : in  STD_LOGIC;
      rhs_7_msb : in  STD_LOGIC;
      sub : in  STD_LOGIC;
      sum_0 : out STD_LOGIC;
      sum_1 : out STD_LOGIC;
      sum_2 : out STD_LOGIC;
      sum_3 : out STD_LOGIC;
      sum_4 : out STD_LOGIC;
      sum_5 : out STD_LOGIC;
      sum_6 : out STD_LOGIC;
      sum_7 : out STD_LOGIC;
      carry_out : out STD_LOGIC
    );
  end component;
  signal n1_clk_mod5, n2_clk_mod10, n3_clk_mod10, n4_clk_mod10, n5_clk_mod10, n6_d3, n6_d2, n6_d1, n6_d0, n7_a, n7_b, n7_c, n7_d, n7_e, n7_f, n7_g, n8_sum_0, n8_sum_1, n8_sum_2, n8_sum_3, n8_sum_4, n8_sum_5, n8_sum_6, n8_sum_7, n8_carry_out, n9_o, n10_o, n11_o, n12_o, n17_o, n18_o, n19_o, n20_o, n25_o, n27_o, n28_o, n29_o, n30_o : STD_LOGIC;
begin

  -- combinational logic
  n9_o <= n6_d3 and n8_sum_3;
  n10_o <= n6_d3 and n8_sum_2;
  n11_o <= n6_d3 and n8_sum_1;
  n12_o <= n6_d3 and n8_sum_0;
  n17_o <= n6_d2 and n8_sum_7;
  n18_o <= n6_d2 and n8_sum_6;
  n19_o <= n6_d2 and n8_sum_5;
  n20_o <= n6_d2 and n8_sum_4;
  n25_o <= n6_d1 and n8_carry_out;
  n27_o <= n9_o or n17_o;
  n28_o <= n10_o or n18_o;
  n29_o <= n11_o or n19_o;
  n30_o <= n12_o or n20_o or n25_o;

  -- sub-component instantiations
  u_0_c4085 : mod_5 port map (
    clk => clk,
    clk_mod5 => n1_clk_mod5
  );
  u_1_c4087 : mod_10 port map (
    clk => n1_clk_mod5,
    clk_mod10 => n2_clk_mod10
  );
  u_2_c4089 : mod_10 port map (
    clk => n2_clk_mod10,
    clk_mod10 => n3_clk_mod10
  );
  u_3_c4091 : mod_10 port map (
    clk => n3_clk_mod10,
    clk_mod10 => n4_clk_mod10
  );
  u_4_c4093 : mod_10 port map (
    clk => n4_clk_mod10,
    clk_mod10 => n5_clk_mod10
  );
  u_5_c5025 : digit_selector port map (
    clk => n5_clk_mod10,
    d3 => n6_d3,
    d2 => n6_d2,
    d1 => n6_d1,
    d0 => n6_d0
  );
  u_6_c5045 : hex_7seg port map (
    in1_msb => n27_o,
    in2 => n28_o,
    in3 => n29_o,
    in4_lsb => n30_o,
    a => n7_a,
    b => n7_b,
    c => n7_c,
    d => n7_d,
    e => n7_e,
    f => n7_f,
    g => n7_g
  );
  u_7_c5434 : fas8 port map (
    lhs_0_lsb => sw11,
    rhs_0_lsb => sw2,
    lhs_1 => sw12,
    rhs_1 => sw4,
    lhs_2 => sw13,
    rhs_2 => sw5,
    lhs_3 => sw15,
    rhs_3 => sw6,
    lhs_4 => sw17,
    rhs_4 => sw7,
    lhs_5 => sw19,
    rhs_5 => sw8,
    lhs_6 => sw21,
    rhs_6 => sw9,
    lhs_7_msb => sw22,
    rhs_7_msb => sw10,
    sub => sub,
    sum_0 => n8_sum_0,
    sum_1 => n8_sum_1,
    sum_2 => n8_sum_2,
    sum_3 => n8_sum_3,
    sum_4 => n8_sum_4,
    sum_5 => n8_sum_5,
    sum_6 => n8_sum_6,
    sum_7 => n8_sum_7,
    carry_out => n8_carry_out
  );

  -- output drivers
  a <= n7_a;
  b <= n7_b;
  c <= n7_c;
  d <= n7_d;
  e <= n7_e;
  f <= n7_f;
  g <= n7_g;
  d0 <= STD_LOGIC'('0');
  d1 <= n6_d1;
  d2 <= n6_d2;
  d3 <= n6_d3;

end Behavioral;